### ISSUE TITLE
Stop the chat from animating away when chat is disabled

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1007]
When an instance's chat is disabled you see the chat sidebar animate away due to a global css transition taking place.

This should be changed so specifically this hiding of chat does not animate and just disappears immediately.   For an example of this visit http://goth.land.

1. Page loads.
2. Chat is visible.
3. Chat animates away.

**Comment by controlfreakstudio** [comment]
given the nature of that global div transition and how wide it reaches, I couldn't conjure a css selesctor means to split this up
I can manually prove an alternative div id for app-container will kill the transition just need to variable that into the app.js html

need a little guidance on the best place you'd want to get the extraAppClasses available to test and make a dynamic div id name

**Comment by gabek** [comment]
@gingervitis If you have any thoughts, chime in!

**Comment by gingervitis** [comment]
I think we'll just reverse the logic.
So instead of the chat animating away onLoad when it is disabled , we'll animate it _in_ onLoad when it is determined that chat is enabled. Or maybe not even animate it, just show it so it doesn't look as jarring when the page loads?

I'll put something up later today.
