### ISSUE TITLE
Exteme studdering and high latency when more than 1 video configuration exists

### ISSUE THREAD

**Issue by andrewfer000** [owncast/owncast#1072]
I stream to my server at 1080p@60fps at a bitrate for 4200 kbps (H.264 NVENC) with 128 kbps audio (ACC). I want to have a second lower resolution configuration for mobile viewing so 720p@60fps at a bitrate for 2100 kbps (H.264 NVENC) with 128 kbps audio (ACC). I also have the latency at the minimum. Both options are at the highest CPU usage or it does not work at all. When there is just the one 1080p@60 stream the latency is 5 seconds with no studdering but with the 720p@60 stream enabled along side the main stream it causes the latency to go up to 15 seconds and the video constantly studders. My OBS also constantly drops bitrate. Is this a bug or is the multiple output thing still a WIP? 

My VPS specs
3x 3.8 GHz Intel CPU
60GB Storage
6GB RAM
libx264 encoder

**Comment by gabek** [comment]
First, please take a look at the two pieces of documentation that may answer some things for you:
- https://owncast.online/docs/troubleshooting/#buffering-and-video-playback-issues
- https://owncast.online/docs/video/

You didn't mention your hardware utilization, but it sounds like it's maxed out?

In short:

- Turning your CPU usage up won't make things better, it will make it significantly worse if your system can't handle it.
- Don't set the latency at the minimum (far left) put it in the middle somewhere if you're experiencing issues.
- Maybe turn your low resolution to the lowest CPU usage since it's your low quality version anyway.

So it sounds like you're using too much CPU and you need to adjust your settings to find a place where you're using less than you are now.  Resizing + re-encoding a 1080p stream to 720p takes time on your CPU, and you telling it to "work as slow and take as much CPU as you like" is going to end badly.  You need it to take less CPU time or get a more powerful server.

Like the documentation says, we can't give a specific answer for your specific configuration, but please read the documentation, ask questions about specific settings if you have them, and experiment with what works best with your current server.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>
<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/video/">Video</a></strong></div><div>Configure your video to manage the quality and hardware performance.</div></blockquote>

**Comment by GTXCrusader** [comment]
I can also echo Gabek's comments by adding that you need insanely powerful CPUs to be able to handle "Highest" CPU Usage Settings.

Re-test your streams by setting your CPU Usage on both streams to "Lowest" and try again.

Also, having latency to "Lowest" also means there is less room for error, and the incredibly high encoding times is very likely causing even more stuttering problems.

To also assist in lowering CPU demands, set your OBS to match your better quality setting (1080/60p @ 4200kbps) on the streaming server. It'll effectively work less to re-encode the data stream, allowing for more CPU time for your 720p setting.

If you get it stable with "Lowest" CPU Usage, then focus on your 720p setting and allow more CPU time for that, as compressing streams requires more CPU time anyways and you'll get a better result (eg: Your high quality stream will have a "Lowest" CPU Usage, with your 720p stream having, say, "Low" or "Medium").
