### ISSUE TITLE
Cleanup paths and make them configurable

### ISSUE THREAD

**Issue by ctsde-markus** [owncast/owncast#1082]
In the process of building the FreeBSD port for owncast an experienced commiter brought up some security considerations regarding writable files/directories to me.

The hier manpage of FreeBSD makes it clear that database files and variable data in general should go to /var/... (that makes it clear what to backup) and this consideration is reasonable to me.

I then tried to make a simple patch for the `transcoder.log` file only to find out that i would not only patch a config file, but parts of the source itself. So i tried to do that for `data` - which is defined in `config/constants.go` but already in `config/defaults.go` the `DatabaseFilePath` isn't built from the `DataDirectory` constant, but is defined as `data/backup.db`.

It would make porting owncast way easier if i could rely on `config/constants.go` and `config/defaults.go` to define paths for files and directories that need to be writable by the user running owncast.

What needs to be configurable from my perspective:

- backup
- data
- hls
- transcoder.log

While we are at it, we should collect the writeable files in a subdirectory in `webroot` like `webroot/local` (or something else)

- thumbnail.jpg
- (anything else?)

When this is done we could easy move `backup`, `data` and `hls` to `/var/db/owncast`. `transcoder.log` to `/var/log/owncast/transcoder.log` (or somewhere else). And have only `webroot/local` writeable for the user running owncast.

**Comment by gabek** [comment]
Some other requests for customization have come through lately, resulting in a `-logdir` from: https://github.com/owncast/owncast/issues/1040.  

In general, as long as additional config options don't show up in the admin, adding command line flags isn't the worst thing in the world if there's valid use cases.  So data and backup could fall into that.

I'd like to simplify where hls segments are stored, since right now it depends on if you're using remote storage or not where the segments live, so it it makes sense to change that: https://github.com/owncast/owncast/issues/875.  Early on we had a flag for customizing the hls path but nobody used it, so it got pulled, so I figure we'd just move it under `data` since that's where user-writable data lives.

**Comment by ctsde-markus** [comment]
For me it would be cool enough if i could rely on patching paths in config/*.go files to have the files where i (or the used UNIX) would like to see it. But command line switches are fine too.

**Comment by fufexan** [comment]
What's the status on this? I'd also want to have Owncast write to `/var/lib/owncast`. Currently it fails to start because the binary is in a read-only location.

**Comment by gabek** [comment]
I feel like this issue is a bit inactionable at this point, since the items listed above are a mix of directories, single files, things that are already configurable, etc.

I'm going to close this, but feel free to file specific issues for specific single requests so they can all be tracked and worked on if needed.
