### ISSUE TITLE
"Easy" minio support broken

### ISSUE THREAD

**Issue by TheReal1604** [owncast/owncast#1100]
Hey peops! 

Thanks for this great software - I setup a little s3 minio storage system with a owncast server using it and stumbled over the following issue:

Minio is configured for the domain:

abc.mystorage.com

If I setup owncast like the docs stated, owncast tries to put the video here:

stream.abc.mystorage.com/hls/....

As a small and simple setup doesnt support virtualhost s3 style path access, do you have an idea how to restore the compatibility with a minio setup?

 Thanks!

**Comment by gabek** [comment]
Since I don't use Minio myself, I can't say specifically what people have done to their setups to make it work, but I believe people have made it work in the past.  We changed quite some time ago from using path-style to host-style due to AWS deprecating their path style.

Hopefully somebody that uses Minio can chime in with how to support virtualhosts.
