### ISSUE TITLE
P2P HLS

### ISSUE THREAD

**Issue by Ruxton** [owncast/owncast#112]
Given the nature of this product, having a peer2peer option in the player would definitely help deal with bandwidth issues as the stream grew.

There's a few implementations out their  that might give you some ideas.
https://github.com/streamroot/clappr-p2phls-plugin
https://github.com/flavioribeiro/clappr-p2phls-stats-plugin

https://github.com/Novage/p2p-media-loader
http://novage.com.ua/p2p-media-loader/demo.html

**Comment by gabek** [comment]
Cool!  I wasn't familiar with p2phls.  I popped my stream into their demo page to use their supported player and opened a few copies of the player to see if I could see any p2p activity.  I didn't seem to see anything different, the video was still being pulled from the same place.  Maybe it requires a lot of peers.  Or maybe the trackers were down or something.

In general I could see this being an experimental option if we could see some real world benefits come from it.

**Comment by geekgonecrazy** [comment]
This is the sort of tech being used in peer tube right?  I wonder how it would really help at large scale.  Might actually make big difference.  But sharing controls for sure would be important

**Comment by gabek** [comment]
I find this super cool, but I fear there may be a lot of variables in play.

While I know some of the above projects mention that there are no dependancies, I think you're using somebody else's WebTorrent tracker to seed segments to the network.  With PeerTube each PeerTube instance is its own WebTorrent tracker.  Relying on some random 3rd party or building torrent support into Owncast both feels like risk and/or complexity with questionable results.

And the reason I say questionable results is because we're focused on live right now, and adding peering into the mix would add delay to a process that's already under a time crunch.  I can't see things getting seeded to peers fast enough for anybody to actually take advantage of it.  By the time that segment is peered to somewhere else, that point of time is already past and you've moved on.

However, I'd like to revisit this when the day comes where Owncast supports recordings, because that starts to make way more sense when the segments can be seeded without the restrictions of it needing to be in real-time.

**Comment by geekgonecrazy** [comment]
I wonder if ipfs could be utilized... 

https://blog.fission.codes/experimenting-with-hls-video-streaming-and-ipfs/ maybe too slow for streaming.  But playback maybe

**Comment by gabek** [comment]
We actually had IPFS support, but it got removed: https://github.com/owncast/owncast/issues/74

It worked better than you'd think, but not as good as I'd like.  The amount of stuff needed to host a IPFS node within an Owncast instance was a lot. The final straw to remove it was it actually maxed out the resources on @mattdsteele's machine when building it and would fail.

**Comment by zhoreeq** [comment]
Peertube has added P2P live streaming just recently https://framablog.org/2021/01/07/peertube-v3-its-a-live-a-liiiiive/

**Comment by nicopace** [comment]
Also, @darkdrgn2k and @benhylau worked some time ago on a similar project, publishing an HLS stream to IPFS:
https://github.com/tomeshnet/ipfs-live-streaming

<blockquote><img src="https://opengraph.githubassets.com/883eff64bd68e2e6e581fdccc40199f92d885c70bbac00bfd7c12e8ca29ccf1a/tomeshnet/ipfs-live-streaming" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tomeshnet/ipfs-live-streaming">GitHub - tomeshnet/ipfs-live-streaming: Like HTTP live streaming, but with IPFS which is maybe better?</a></strong></div><div>Like HTTP live streaming, but with IPFS which is maybe better? - GitHub - tomeshnet/ipfs-live-streaming: Like HTTP live streaming, but with IPFS which is maybe better?</div></blockquote>

**Comment by gabek** [comment]
Yeah it's doable, and we did have it from the earliest versions.  But it's certainly not great for people doing live content. We already get asked for lower and lower latency, and to add IPFS into the mix would exponentially increase it.  Plus the amount of extra complexity required to run an IPFS node inside Owncast itself was too much.

As seen [here](https://github.com/tomeshnet/ipfs-live-streaming/issues/68) from the project you just linked to:

> In all cases observed latency is between 1 to 1.5 min, although I have seen as much as 2 min occasionally.

Previously:

> We actually had IPFS support, but it got removed: #74
> 
> It worked better than you'd think, but not as good as I'd like. The amount of stuff needed to host a IPFS node within an Owncast instance was a lot. The final straw to remove it was it actually maxed out the resources on @mattdsteele's machine when building it and would fail.

**Comment by rektide** [comment]
Just a shout out to https://pkg.go.dev/github.com/anacrolix/torrent/tracker , which is a well reputed Go-based (which seems to be owncast's preference) tracker with good webtorrent support. I suggest this because I believe it could be a good option to embed into Owncast to provide the needed tracker capabilities out of the box, without relying on other people's systems. I know a little less about what it takes to seed p2p hls / webtorrent.

<blockquote><img src="/static/shared/icon/favicon.ico" width="48" align="right"><div><strong><a href="https://pkg.go.dev/github.com/anacrolix/torrent/tracker">tracker package - github.com/anacrolix/torrent/tracker - pkg.go.dev</a></strong></div></blockquote>

**Comment by gabek** [comment]
@ForestJohnson If you get a chance, I'd love to hear about your work with WebTorrent, from the client and server/tracker side, and its performance. Like mentioned above, if there's a fit for p2p with Owncast I'm totally game, knowing the following:

- Owncast is live
- Streams are generally relatively small, so the number of seeders would be limited
- Latency is something people are very sensitive about

**Comment by ForestJohnson** [comment]
With the browser, HTTP server, torrent tracker, and torrent seed all on the same computer, I was able to get the latency from `DOMContentLoaded`  to `Torrent download complete`  down to about 250ms.  

But I think there's a more fundamental problem with webtorrent where torrents are immutable, can't add new content to them (new HLS segments)  but also each torrent in webtorrent has to have its own swarm, and peer connections can't be shared between swarms AFAIK.   So all the peers would have to reconnect for each HLS segment file. 

I'm not sure what to do about that..  I'm not sure i have the energy to write a brand new p2p protocol for my solution right now. Someone also suggested IPFS/libp2p, and I may try that out as well, but for now I might just stick with webtorrent and say its only properly efficient for static content.

When my little hack project is more complete and I've tested it with various workloads, I'll do a demo and share the repo / docker images. 

Edit:  I wrote more technical in-depth about it on the issue on the WebTorrent  repo:  https://github.com/webtorrent/webtorrent/issues/1993#issuecomment-1005085536

**Comment by ForestJohnson** [comment]
Ok I gave up on bittorrent, I think for p2p streaming you would want a protocol more similar to Apache Kafka.  BitTorrent is 100% P2P with no authority server (besides perhaps the tracker, but the tracker is not really involved in distribution).  

I think the proper protocol would be like "state communism": it would attempt "from each according to their means, to each according to their needs"   based on central planning. Imagine a sort of tree structure with the streamer at the root, the viewers on fiber internet as the trunk, and the viewers with the lowest upload speeds at the leaves.  The centralization of distribution planning would help keep the latency down & distribute the bandwidth load as much as possible while also ensuring that viewers get the bytes they need in time.  

Theoretically it would add `log(n)*avgPeerPingMilliseconds` extra stream delay if you have `n` viewers. The base of that `log` would be the ratio between fastest peers' upload bandwidth and the average bit rate of the stream, i.e. how many copies of the stream can the average "fast peer" upload at once.

Also its important to note that for streaming, P2P will probably always be a "cost-cutting" or "optimization" method, not a rock solid 100% solution. TLDR is that most people's upload speed is quite bad. If the bit rate of the stream is greater than the average viewers upload speed, additional / bigger upload pipes will always be needed to scale.  Also, if folks are viewing your stream over LTE/5G or from behind a restrictive firewall, they probably won't be able to participate in the P2P network at all; they won't be able to download from other viewers.

The good news is the streamer can also set up "dedicated seed nodes" to essentially run their own CDN. And those seed nodes don't need to be fancy or run in "the cloud", it would just be "any internet connected computer running a little seeding program". The dedicated seed nodes would probably also be able to serve bytes to LTE/5G users, in a typical "home server" context they can leverage uPnP to open a port on the router, something WebRTC in the browser cannot do.

In the best case scenario this would offer a lower stream delay than an off-the-shelf object storage system, things like Amazon S3 and Backblaze were never designed for low latency and sometimes their latency can be quite high (at least in my experience). But this p2p thing could have a "push" mode specifically for live streaming use cases where the web browser will start downloading bytes for a stream segment before it's even requested by the video player. 

I want this in-browser p2p CDN thingy for other reasons besides video streaming, video streaming is just the biggest baddest use case or problem to throw at it. Honestly its really hard and I'm intimidated, I worry maybe my time would be better spent on something else.

**Comment by tarumes** [comment]
i tested this https://github.com/novage/p2p-media-loader
for a few month on a nginx-rtmp instance
it works pretty well and you can save up to 50% of all viewers traffic

i also found this a few days ago
https://github.com/cdnbye/hlsjs-p2p-engine

i think it would be a great expansion
also the latency is not extremely worsened by p2p

<blockquote><img src="https://opengraph.githubassets.com/3a602d48431e56182381d3adabdb2e3e63044e2533f03b8fc0dcec2029df4671/Novage/p2p-media-loader" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Novage/p2p-media-loader">GitHub - Novage/p2p-media-loader: An open-source engine for P2P streaming of live and on demand video directly in a web browser HTML page</a></strong></div><div>An open-source engine for P2P streaming of live and on demand video directly in a web browser HTML page - GitHub - Novage/p2p-media-loader: An open-source engine for P2P streaming of live and on de...</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/5de23b9962e4c7745d472b81115139e035470c98a1a50222cf2a82bd3bfcf316/cdnbye/hlsjs-p2p-engine" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/cdnbye/hlsjs-p2p-engine">GitHub - cdnbye/hlsjs-p2p-engine: Let your viewers become your unlimitedly scalable CDN.</a></strong></div><div>Let your viewers become your unlimitedly scalable CDN. - GitHub - cdnbye/hlsjs-p2p-engine: Let your viewers become your unlimitedly scalable CDN.</div></blockquote>

**Comment by gabek** [comment]
Just a reminder that we'd have to build a torrent tracker into Owncast as well, so it's not just a client-side thing.

**Comment by tarumes** [comment]
i maybe will look into that
but also there are hundrets of public STUN/webtorrent servers available

and there sould be no need for a bundled tracker server because a single server can handle +40k clients

**Comment by gabek** [comment]
> but also there are hundrets of public STUN/webtorrent servers available

For standalone software like Owncast where independence and privacy is important, not requiring the dependency of 3rd party services is required. Using a public STUN server would not be appropriate.

**Comment by tarumes** [comment]
then you have to drop p2p completly because all ips of all peer are known to all peers and its extremly easy to track everyone
and it hides a serious legal issue as well
as soon as you share a single bit of a copyrighted video (as a peer) and some legal team is in that swarm you will get a realy bad letter
and that as a user who just opened the stream in his browser not knowing its p2p

**Comment by ghost** [comment]
i also wanted to ask for p2p but he is right for all of europe p2p is an extremely dangerous area
and you should not even think about using it

**Comment by Ruxton** [comment]
> Just a reminder that we'd have to build a torrent tracker into Owncast as well, so it's not just a client-side thing.

no you don't, leave that SOLVED solution up to the user IF they enable p2p.  There are plenty of lightweight trackers out there, if people want to keep the privacy on lock (you can even suggest some). Otherwise they can easily spin up on a free/open tracker.

**Comment by ForestJohnson** [comment]
> extremely dangerous

```
     ___/‾⁀|__,
      xx . .|
       [   >)    
       ‶` ‾
               
    (X)  DOUBT
```

**Comment by ghost** [comment]
not just a torrent tracker also a TURN server and also a STUN server too

**Comment by ghost** [comment]
> > extremely dangerous
> 
> ```
>      ___/‾⁀|__,
>       xx . .|
>        [   >)    
>        ‶` ‾
>                
>     (X)  DOUBT
> ```

if one of the "abmahnanwälte" from germany catch you `sharing just a single bit or byte of copyrighted material`
and yes they are observing torrent swarms from time to time they sue you to death
as they already did with other live streaming services with p2p streaming

and yes they are sue every single peer in that p2p swarm

**Comment by ForestJohnson** [comment]
First of all, owncast is a self-publishing tool,  telling people that they cannot self-publish because the content they are publishing is owned by someone  else,  it's ridiculous, what, we aren't allowed to stream ourselves any more? We are all the recording industry's property now?  

Second of all, I would not recommend negotiating with terrorists. That's all I'm going to say about that.

**Comment by ghost** [comment]
> First of all, owncast is a self-publishing tool, telling people that they cannot self-publish because the content they are publishing is owned by someone else, it's ridiculous, what, we aren't allowed to stream ourselves any more? We are all the recording industry's property now?

then have fun streaming a movie, tv-shows or **music** in europa on your owncast instance they will shut you down by force and law

**Comment by ghost** [comment]
but still you have to implement 3 services to have 1 feature ....

**Comment by ForestJohnson** [comment]
Point of information:  

TURN is a relay protocol which is used to enable WebRTC to work even in network conditions where P2P connections are impossible.   TURN is used to ensure that WebRTC-based applications such as audio and video chat always work no matter what the network conditions are.  

For P2P HLS streaming,  TURN is not only not required, it is a waste of bandwidth. No point in relaying when serving direct would work just as well.

Another point of information, in reply to @Ruxton 

If WebTorrent and/or its protocols  are used, owncast will almost certainly have to provide its own tracker. It's not about privacy, its about functionality.  Per my research into WebTorrent which you can read above,  WebTorrent is not cut out for live-streaming and it would have to be modified in order to work.  Public trackers are not going to cut it for live streaming because the live streamer would be seen as a bad actor (spammer)  by the tracker.  

I was only able to achieve 250ms latency in my testing because  I  was running my own tracker and I had hot-rodded WebTorrent in a way that puts tons of extra strain on the tracker.  With the public tracker, it had over 5 seconds latency.  Trying to use a public tracker with that hot-rodded version of WebTorrent, especially for live-streaming a new file every 2 seconds,  I don't think it's a good idea.  

BitTorrent and public trackers in general are a "solved problem", yes, but they are also designed around static content and relatively few, infrequent downloads.  Live streaming is a whole different ball game because of the way that the data is dynamic and real-time. Like I said before, IMO a whole new protocol that's not BitTorrent would be appropriate here. 

EDIT: And its worth pointing out that this is a large un-solved problem outside the scope of Owncast, it's not really Owncast's job to figure this out. If you want efficient, scalable P2P live video streaming to 100s  or even 1000s of viewers,  I think its gonna take not just implementation but also lots of R&D first.  Who knows, maybe someone in academia has a paper on this? Or maybe it's our job to go out there and do the research, write the paper.

**Comment by ghost** [comment]
wow a productive answer
unfortunately it is already too late i have already recommended another project to my company that is now financially supported due to the somewhat unprofessional nature of the previous messages

but still it is possible to put your own torrent tracker server up with like no efford i did it already and noone care about 1-2 seconds more delay if the stream runs fluid vs choppy stream

**Comment by johnsmithodom** [comment]
Does someone have any update on the p2p feature?  tried out owncast, on the viewer side, it always has the circle running, seem vary annoying; hopes p2p enabled will help the performance. Thank you for making this tool available.

**Comment by gabek** [comment]
Currently not planned. See above for the discussion. Closing.

**Comment by snowinszu** [comment]
Hi,
   I think you can try this solution: https://www.cdnbye.com/web-hls

**Comment by gabek** [comment]
Literally the first line of that web page is

> [Register](https://www.cdnbye.com/guides/getting-started#for-web-app-integration) your domain to activate P2P service.

Can you see why, even if I wanted to look into a corporate solution, how could this never work? But mostly, Owncast will never have sketchy corporate dependencies in it.

**Comment by snowinszu** [comment]
Hi @gabek 
   Thanks for your good question. As [here](https://www.cdnbye.com/pricing) said: SwarmCloud is completely free of charge for open-source projects and non-profit organizations. Register domain is only for data statistics. Even for commercial project, the price is much lower than CDN.

**Comment by pierreozoux** [comment]
@snowinszu you don't get it, it is not about the price, it is about the license of the code. And dependance to an online API that is run by a corporation. If it was a dependance to wikipedia's API, this would be something else.

**Comment by snowinszu** [comment]
Hey! I just add p2p sdk into owncast: https://github.com/cdnbye/owncast-p2p
Feel free to give me feedback :)

<blockquote><img src="https://opengraph.githubassets.com/6e5452cb57e7f086b84c56b8a7fb2f730c475285337cd0acec9b0eeb32cd2016/cdnbye/owncast-p2p" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/cdnbye/owncast-p2p">GitHub - cdnbye/owncast-p2p: Take control over your live stream video by running it yourself.  Streaming + chat out of the box. With P2P Streaming!</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. With P2P Streaming! - cdnbye/owncast-p2p</div></blockquote>
