### ISSUE TITLE
FTP support for storage

### ISSUE THREAD

**Issue by exaskye** [owncast/owncast#1123]
I've been experimenting with integrating Owncast with [bunny.net](https://bunny.net), and have had issues doing so with a "pull zone" (caching reverse proxy, more or less), and Edge Storage with curlftpfs, s3proxy, and Minio gateway. They all don't work for varying degrees of "don't work".

bunny.net Edge Storage is the ideal solution here, but they only support FTP and a custom API. It would be nice if Owncast supported FTP as a storage backend.

**Comment by gabek** [comment]
Seems like a valid use case, but I'm afraid FTP for real-time content delivery is going to be awfully niche. I'll keep this open to see if anybody else chimes in over time with use cases outside of bunny.net.

**Comment by exaskye** [comment]
FTP isn't really much more of a stretch than S3.

If you absolutely must use an HTTP API, Edge Storage has [its own custom API](https://docs.bunny.net/reference/manage-files), but that's a lot less generic, obviously.

**Comment by Vegas10128** [comment]
I just seen this post but wasn't really much help due to no answers. However i think there needs to be a solution for remote ftp storage and allowing the hls stream to send chunks through ftp, then the webserver be the response of the files needed to download. 

this would be perfect because it takes the offload completely away from your upload bandwidth on server and all users grab the chunks from that webserver. I wish Owncast had something like this.

**Comment by gabek** [comment]
> this would be perfect because it takes the offload completely away from your upload bandwidth on server and all users grab the chunks from that webserver. I wish Owncast had something like this.

That's exactly what object storage support is for. I understand you'd prefer to use FTP, but bulk file object storage providers have settled on using the S3 API and it wouldn't make sense to add an entire additional 3rd party integration that needs to be managed and tested indefinitely for just a person or two.
