### ISSUE TITLE
Make the emoji directory configurable 

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1174]
The [custom emoji directory](https://github.com/owncast/owncast/blob/7fe67cb853654ec6eeba9abeaf70502ed398c0b8/controllers/emoji.go#L18) needs to be read from the configurations. This will need some code refactoring to avoid cyclic dependencies.

**Comment by MFTabriz** [comment]
This will help the implementation of #480

**Comment by gabek** [comment]
I'd rather not have a new setting in the admin just for location of emoji.  Nobody has asked for that to be configurable, and the admin is getting pretty full of stuff. I want to be pretty sensitive about what gets added and what doesn't otherwise it can become intimidating.  What's wrong with the emoji living under the webroot?  It shouldn't impact client-side input of emoji.

**Comment by MFTabriz** [comment]
@gabek Sorry for not being clear on this. I didn't mean it to be configurable in the admin's panel. My request was to define the path to the emoji directory in the config package (maybe in config/constants.go) which then can be easily tweaked (if necessary), instead of locally defining it wherever it's needed. What do you think about this?

**Comment by gabek** [comment]
Oh, got it!  Yeah, I'm all for centralizing that value.
