### ISSUE TITLE
[bug] fix space letters

### ISSUE THREAD

**Issue by TOWUK** [owncast/owncast#1247]
![image](https://user-images.githubusercontent.com/28830162/126815802-97bd5684-9f68-4298-856a-b0bad4af09a7.png)

**Comment by TOWUK** [comment]
dont send DOT on finish change name pls or dont send bolder dot

**Comment by gabek** [comment]
This missing space was resolved in the `develop` branch a couple days ago.  The period is there because it's a sentence.  The period is not bolded.  https://github.com/owncast/owncast/blob/develop/webroot/js/components/chat/message.js#L30-L31

If it's still not formatted properly after you update feel free to re-open.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/message.js at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/message.js at develop · owncast/owncast</div></blockquote>
