### ISSUE TITLE
feature request | Re-streaming 

### ISSUE THREAD

**Issue by Waffleuncle** [owncast/owncast#1285]
Hi , i would like to know if is possible to add Re-streaming.

**Comment by gabek** [comment]
Owncast is a RTMP destination like Twitch, YouTube or any other live streaming services.  It's not a middle man between you and these services.  Take a look at [Prism](https://github.com/muesli/prism) or a service like [Restream.io](http://restream.io/) for this kind of functionality.

**Comment by p10tyr** [comment]
But you don't understand.. restreaming is very valuable because we can control the ingest pipeline better with own cast. Especially in my case my internet is quite bad and using the highest latency actually solves me a lot of headache that YouTube just starts freezing like mad.

I wish all my viewers came to my site but the honest truth is that 99% of my viewers are on YT at the moment and getting them over is PITA

Even if I had to run OBS locally next to this as an input stream so I could rebroadcast it on a server with decent internet that would be awesome... but you don't offer anything like this? 

If we are in control please give us the RTMP link so we can use in VLC or OBS Inputs. Makes sense?!

💖💖Love the software any way 👍🏼👍🏼

**Comment by gabek** [comment]
I totally understand that restreaming solves a problem you have, but Owncast isn't restreaming software. It's a video streaming server, something completely different. 

Maybe if we had more people working on the project we could expand functionality to grow to solve more problems, but the project has to focus on the [core functionality](https://github.com/owncast/owncast/blob/develop/docs/product-definition.md). Making it easier to stream to YouTube isn't something we've ever set out to do, I'm sorry.

However if you'd like to watch an Owncast-powered stream in VLC [you can do that](https://owncast.online/docs/video/#your-stream-can-be-played-outside-of-your-web-site).

**Comment by p10tyr** [comment]
@gabek Thank you for replying so quick. Yes I completely understand and that is fair. This project focus is about making your own platform which is really epic! We will defiantly be using and I hope we will be able to make enough money to donate back to awesome open source projects like this.

I'll be honest.. it was late and I read that section of the document maybe 4 times and it just didn't click in my brain what was written there. This is perfect because I can just add `https://owncast.mydomain.com/hls/stream.m3u8` to a stream input in OBS.

Thank you again 💯💯💯💯
