### ISSUE TITLE
Offline state doesn't revert player to offline appearance

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#130]
1. Start streaming video
1. See thumbnails start updating
1. Stop streaming video
1. Once the UI goes into offline you can still press play.

**Comment by gingervitis** [comment]
The logic behind this case is that the video (not stream status) would switch to "offline" when the element has `ended`. So if you're paused, and the stream ends, you'll still see the play button because you'll still have a few segments left available to play.  Once you've played to the end of the remaining video content, it should switch back to just the background image. 

(Though I've been getting buffering before it reaches the end)

**Comment by gingervitis** [comment]
UX notes:
1) stream status goes offline, but user is paused or has not started playing.
2) user clicks play, they could be playing old content thinking it's live. could be a confusing experience.

When stream status becomes offline, 
- if user hasn't started playing or is paused, just go offline, hide play button. Turn everything to offline mode.
- else keep playing to playerEnded.
