### ISSUE TITLE
Directory hero player does not move to the next instance on error

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1325]
In this example, the player is throwing an error because it refuses to load non-SSL'ed content, a perfectly acceptable error.  However, the player doesn't immediately move to the next instance, and instead just shows a spinner until the buffering timer times out.

![image](https://user-images.githubusercontent.com/414923/129497108-ab9c0f8f-9447-4823-aea2-d7b1384129e5.png)

**Comment by gingervitis** [comment]
> In this example, the player is throwing an error because it refuses to load non-SSL'ed content, a perfectly acceptable error. However, the player doesn't immediately move to the next instance, and instead just shows a spinner until the buffering timer times out.
> 
> ![image](https://user-images.githubusercontent.com/414923/129497108-ab9c0f8f-9447-4823-aea2-d7b1384129e5.png)

Hm I wonder did the `onError` event even fire? Or does this type of CORS error not fall under VideoJS's error handling?  (Tho the error message says "VIDEOJS: ERROR".  I thought I had handled this 🤔

**Comment by gingervitis** [comment]
This issue seems inconsistent across various browsers.

- Moving to next _does_ happen on Firefox.
- Moving to next _does_ happen on Safari.
- Moving to next _does_ happen on Chrome/Brave, but seems to do so at much later time.


Here this shows that it has moved on to Item #2 after dtvperth did not work.
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/9563255/129506547-7ffd5933-3377-49ba-b619-805df3e3190c.png">

**Comment by gabek** [comment]
I think what I'm seeing on Brave is it moving on after the buffering timer fires instead of when the error was fired.

**Comment by gabek** [comment]
As an aside, we should probably filter out any non-`https` streams from the hero as well, since they'll all be unplayable.
