### ISSUE TITLE
Transcoding errors when using nvenc above 60fps

### ISSUE THREAD

**Issue by Kashiroo** [owncast/owncast#1345]
I'm using the following docker image which has ffmpeg compiled with nvenc support:
https://github.com/ich777/docker-owncast

When streaming from OBS to Owncast at 1080p90fps for example, the transcoder is throwing decoding errors:

`error	8:17:30 PM 08/23/2021	[h264 @ 0x559ee50cea00] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
error	8:17:30 PM 08/23/2021	[h264 @ 0x559ee50cea00] Using more than 32 (40) decode surfaces might cause nvdec to fail.
error	8:17:30 PM 08/23/2021	[h264 @ 0x559ee50cea00] Try lowering the amount of threads. Using 16 right now.
error	8:17:30 PM 08/23/2021	[h264 @ 0x559ee50cea00] Failed setup for format cuda: hwaccel initialisation returned error.`

Shouldn't the decoding be done using nvdec, instead of cuvid?

To clarify, the stream is working fine despite the errors. Streaming at 60fps or below results in no errors.

**Comment by gabek** [comment]
We don't specify a specific decoder, allowing the the appropriate codec for the format to be selected based on what is supported.  The message "might cause nvdec to fail" implies it is using nvdec.  I read somewhere that "cuvid" is an older name for nvdec?  But I'm not sure.

I know different nvidia cards have different limits (I've run into encoding limits when testing), but I've not seen decoding limits.  And it seems like in your case you haven't hit a hard limit, since it still seems to be working.

I'm not sure there's anything that can be done if the hardware is warning you about too much being thrown at it.  It seems to be a valid warning.

If there's anything specific that needs to be changed in Owncast please let me know.
