### ISSUE TITLE
Implement /spoiler Tag for Chat messages

### ISSUE THREAD

**Issue by unclearParadigm** [owncast/owncast#1358]
Hey team!

I was watching a Coding-Stream where the streamer was solving coding-challenges. The audience was coding along and sharing their solutions in the chat. In some cases, those solutions were spoilers for the streamer, and influenced the solution. Various other messengers (e.g.: discord) have a `/spoiler`-tag, which causes the chat-message to be blacked out. The only way to make the text visible would be to click on the text. This allows people interested in the solution to click it, and others trying to figure out their own way, to continue reading the chat without getting spoilers/hints.

### Idea

* Consider `/spoiler` as a keyword that blacks out the message.
* It could be treated as simple text message as is, and it'll have no impact on the backend ChatAPI and Webhooks.
* If frontend receives a chat message, it checks whether the message-body starts with the `/spoiler` tag. 
* If the message starts with the tag, it adds a CSS-class to the message-text-container
* default behavior for that class is: "blacked out", so the text is not visible / not readable
* On-Click (or maybe even on hover): is visible as any other message

I think, this might be a cool enhancement to the Chat.

BR,
Ruffy

**Comment by gabek** [comment]
It seems like a pretty niche use case, but if it's something we can see having wide appeal I'm not opposed.

However if we were to do it I'd prefer to add metadata around the message instead of stringly matching on the rendering side. We can add a "spoiler" boolean or something along with a message so `/spoiler` doesn't have to be a part of the message text itself, and the receiver doesn't have to know about rendering spoilers if it doesn't want to (webhooks, 3rd parties).

**Comment by unclearParadigm** [comment]
Aggree, it's a nieche use-case.
I'll keep the issue open for now. If others show interest in this featured, I'd be happy to implement it, if not, I'll just close it again.

**Comment by sethschn** [comment]
I would love /spoiler tag
