### ISSUE TITLE
If server goes offline (restarted) and UI goes offline it never comes back online

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#136]
I restarted the owncast instance to get a config change update, the UI went offline as it should, but even when everything was back and video was back playing the chat UI was still locked out.

![image](https://user-images.githubusercontent.com/414923/91673975-923e6c00-eaeb-11ea-99a5-5244d9562f5b.png)

**Comment by gingervitis** [comment]
I saw this happen once, but I haven't been able to repro since.

I've tried-

1) start stream
✅ stream is "online"
✅ chat gets enabled

2) stop stream
✅ stream is "offline"
✅ chat gets disabled / grayed out

3) start stream again
✅ stream is "online"
✅ chat gets enabled, as it should.


If you see this again, can you document some steps

**Comment by gabek** [comment]
When testing I realized it's probably due to the websocket client not re-connecting.  I can fix.

1. Run server
1. Start video
1. Kill server
1. Restart server
1. Start video
1. Chat should re-enable but it doesn't

**Comment by gabek** [comment]
Fixed the client websocket not trying to reconnect, but even when it reconnects the chat input doesn't re-enable.
