### ISSUE TITLE
Set username via request headers

### ISSUE THREAD

**Issue by psych0d0g** [owncast/owncast#1365]
I have a apache proxy infront of owncast to make it private and ssl enabled and would love to set the chat username of authenticated users (via the apache) to a defined name using http headers that are set by the authenticating apache infront of owncast. With this i would also like to disable the possibility to change ones own username.

**Comment by gabek** [comment]
If anybody is interested in looking at this, it should be trivial to do since the chat server registration accepts an optional name already in https://github.com/owncast/owncast/blob/develop/controllers/chat.go#L63.  So an additional case that looks at the headers as well as the request payload could be added.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/chat.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/chat.go at develop · owncast/owncast</div></blockquote>
