### ISSUE TITLE
h264_v4l2m2m as a hardware encoder for streaming

### ISSUE THREAD

**Issue by vikanezrimaya** [owncast/owncast#1379]
https://www.willusher.io/general/2020/11/15/hw-accel-encoding-rpi4 - this is a reasonably fast method of using hardware acceleration on ARM boards such as the Pi 4 without using OMX which is not available when running a 64-bit kernel and userland and apparently deprecated (no source on that for now, lost it).

Sadly I can't choose it in the Owncast settings on the latest release. Please add it as an option :pleading_face:

**Comment by gabek** [comment]
I had issues getting it working previously.  Maybe at some point down the road I can find some time to look at it again.  If others want to use it I can make it a priority, but it's likely this will sit around for a while since it seems like not many people are interested in taking advantage of hardware acceleration. 

https://github.com/owncast/owncast/blob/develop/core/transcoder/codecs.go#L286-L330

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/codecs.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/codecs.go at develop · owncast/owncast</div></blockquote>

**Comment by gabek** [comment]
Seems like OMX is no longer supported in Raspberry Pi OS as of the most recent release, so v4l is probably the solution going forward. However, I'm not convinced people are using Owncast with this hardware, so it'll continue getting pushed back until major features get finished.

**Comment by FilipStadler** [comment]
I use RaspberryPI4 32bit with OMX - I would upgrade to 64 bit OS if the hardware encoder was working on 64bit.
I avoid making multiply version of the stream because of problems - I tried with two variants.
 one Video Passthrough  and the a smaller 1280x720p but the it looks like it also changes the video passed to 720 p also thats a bit strange to me - if I trie to have two encoded streams it did nok work for me - but one stream with 3300kbps full-hd 1080p 25 frams and OMX works OK.  I find it not so easy to stresstest my setup - I made 24 connections to this setup and it looked fine so maybe the current limit is my internet connect is limited - this setup says the output is around 4500kbps sometimes I see this using vlc connecion - but I dont understand why the passtru changed resolution.

**Comment by tsvetkovv** [comment]
Upvote for raspberry pi hardware acceleration support. 
p.s. Thanks for an amazing soft!

**Comment by gabek** [comment]
OMX is supported on Raspberry Pi, but I don't currently know the state of support of it within Raspberry Pi OS. https://owncast.online/docs/codecs/#raspberry-pi

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/codecs/">Codecs & Hardware Acceleration</a></strong></div><div>If you have direct access to specific hardware you may be able to increase the performance of your server by using a compatible codec.</div></blockquote>

**Comment by mattdsteele** [comment]
I tried getting this to work on my Pi 4 today, unsuccessfully. But I encountered some novel errors, here's what I learned in case others want to pick it up (or if I want to try in another few months).

Support for OMX on newer Raspberry Pi OS versions has gotten worse. Previously it wasn't supported on 64-bit Pi OS, but now it's gone from bullseye distros even on 32bit: https://github.com/raspberrypi/firmware/issues/1366#issuecomment-1034726587

So I took a look at enabling V4L, which is where we'd want to go long-term anyhow. Some of the code is already setup in `core/transcoder/codecs.go`, and I can make it available by adding it to the `supportedCodecs` map:

```diff
 var supportedCodecs = map[string]string{
        (&Libx264Codec{}).Name():      "libx264",
+       (&Video4Linux{}).Name():       "video4linux",
        (&OmxCodec{}).Name():          "omx",
        (&VaapiCodec{}).Name():        "vaapi",
        (&NvencCodec{}).Name():        "NVIDIA nvenc",
```

Which then let me switch to it in the UI:

![image](https://user-images.githubusercontent.com/389077/221443465-bc47ee71-8ad2-49ac-8fe2-a00bae58a195.png)

But trying to run it was causing errors around pixel formats, so I had to change to:

```diff
 // PixelFormat is the pixel format required for this codec.
 func (c *Video4Linux) PixelFormat() string {
-       return "nv21"
+       return "yuv420p"
 }
```

After these changes I could select V4L in the UI and begin encoding in a stream, but would see these errors in the logs, and Owncast was showing errors while streaming:

```
ERRO[2023-02-26T16:20:18-06:00] [h264_v4l2m2m @ 0x5599feb2d0] Failed to set number of B-frames: Invalid argument 
ERRO[2023-02-26T16:20:18-06:00] [h264_v4l2m2m @ 0x5599feb2d0] Failed to set gop size: Invalid argument 
```

![image](https://user-images.githubusercontent.com/389077/221444714-3b7e564f-dd21-4246-8982-faebe56de481.png)

Researching this led me to a few posts that indicate the ffmpeg provided by the Raspbian repo doesn't properly set keyframes when using `h264_v4l2m2m`, leading to corrupted files: https://raspberrypi.stackexchange.com/questions/139510/video-encoding-on-raspberry-pi-4-via-ffmpeg-and-h264-v4l2m2m-produces-corrupted/139512#139512

A few other things I've tried out:

Use [this fork of ffmpeg](https://johnvansickle.com/ffmpeg/) instead of one installed via apt:

* The binary was only supported on arm64, so I switched to the 64-bit Raspbian OS
* Using the 64-bit binary, it successfully generated a stream, but the `Failed to set gop size` warning still showed
* In Owncast, thumbnails and gifs failed to generate. This appears to be a bug that affects GPU decoding, but not encoding: https://github.com/jc-kynesim/rpi-ffmpeg/issues/53#issuecomment-1298570481

Using [this other fork of ffmpeg](https://github.com/jc-kynesim/rpi-ffmpeg):

* Is advertised as the issue having been fixed: https://github.com/raspberrypi/linux/issues/5150#issuecomment-1247922065
* But it doesn't appear to have been ported upstream: https://github.com/BtbN/FFmpeg-Builds/issues/217
* Issue in the forked repo: https://github.com/jc-kynesim/rpi-ffmpeg/issues/53
* I also tried compiling from source using the instructions in https://github.com/jc-kynesim/rpi-ffmpeg/blob/dev/5.1.2/rpi_import_1/pi-util/BUILD.txt
 * To get these to compile a static binary, I had to `--enable-libx264`, and remove `--enable-vout-egl`, [as per this post](https://github.com/jc-kynesim/rpi-ffmpeg/issues/52)
 * But neither the 5.1.2 nor the 4.3.5 branches were successful; they both showed the same two errors, and wouldn't encode video in Owncast

I added links to other useful pages here: https://gist.github.com/mattdsteele/9b6cd9ec389b476fa64818eb58cdf6cb

I think if we could find an ffmpeg release/fork that supported V4L, we'd be pretty close to supporting it in Owncast, but at least as of now, it doesn't seem like it's ready for prime-time.

<blockquote><img src="https://cdn.sstatic.net/Sites/raspberrypi/Img/apple-touch-icon@2.png?v=38b7cb40765d" width="48" align="right"><div>Raspberry Pi Stack Exchange</div><div><strong><a href="https://raspberrypi.stackexchange.com/questions/139510/video-encoding-on-raspberry-pi-4-via-ffmpeg-and-h264-v4l2m2m-produces-corrupted">Video encoding on Raspberry Pi 4 via ffmpeg and h264_v4l2m2m produces corrupted video</a></strong></div><div>Raspberry Pi 4, 4 GB
Rapsberry Pi OS Lite, 64 bit (2022-09-22)
Kernel 5.15.61-v8+
ffmpeg 4.3.4-0+deb11u1+rpt3

config.txt has the following relevant entry:
# Enable DRM VC4 V3D driver
dtoverlay=vc4...</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/f84237e9b1f5434e6189912385185002275e1ce3f204048ca1558e7859fab50d/jc-kynesim/rpi-ffmpeg" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jc-kynesim/rpi-ffmpeg">rpi-ffmpeg/BUILD.txt at dev/5.1.2/rpi_import_1 · jc-kynesim/rpi-ffmpeg</a></strong></div><div>FFmpeg work for RPI. Contribute to jc-kynesim/rpi-ffmpeg development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/mattdsteele/9b6cd9ec389b476fa64818eb58cdf6cb">Rpi</a></strong></div><div>Rpi. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by sandboxgangster** [comment]
Hello,

By me works ffmpeg(Mainline  4.4.3 on Gentoo) whit v4l2m2m on PI4 

My USEFLAGS are: media-video/ffmpeg network x264 libv4l v4l libx264 libx264rgb h264_v4l2m2m 

You must add more RAM to the GPU over the config.txt and than works for me without Errors

RPI4:
dtoverlay=vc4-kms-v3d-pi4,cma-256  (The PI4 Driver is not stable, is better use the PI3 driver for the RP4 this works fine)
RPI3:
dtoverlay=vc4-kms-v3d,cma-256

**Comment by mattdsteele** [comment]
@sandboxgangster Did you make the changes I mentioned above to enable `video4linux` in `codecs.go`, so it appears in the dropdown? And were you able to see video in the stream, as well as thumbnails/animated gifs for social media shares? The latter is where my experiments failed with all the approaches I had tried.

I'm not familiar with Gentoo's approach to package compilation and setup, but it's exciting you were able to get a compile working!

**Comment by sandboxgangster** [comment]
Yes, I made the changes, I checked the gop problem can be solved.

e.g. https://lists.ffmpeg.org/pipermail/ffmpeg-user/2020-December/051067.html

At the moment I'm having problems with ffmpeg not accepting the set codec, I'm in the process of building my own version of ffmpeg.

Currently working on:

```
ffmpeg started on 2023-03-30 at 21:46:47
Report written to "data/logs/transcoder.log"
Log level: 32
Command line:
/owncast/ffmpeg/ffmpeg -hide_banner -loglevel warning -fflags +genpts -i ./data/tmp/offline.ts3953729968 -map v:0 -c:v:0 h264_v4l2m2m -b:v:0 2808k -maxrate:v:0 3032k -g:v:0 150 -keyint_min:v:0 150 -r:v:0 30 -map "a:0?" -c:a:0 copy -preset veryfast -var_stream_map "v:0,a:0 " -f hls -hls_time 5 -hls_list_size 5 -hls_flags program_date_time+independent_segments -hls_playlist_type event -segment_format_options "mpegts_flags=mpegts_copyts=1" -pix_fmt yuv420p -sc_threshold 0 -master_pl_name stream.m3u8 -hls_segment_filename "http://127.0.0.1:40421/%v/stream-offline-%d.ts" -max_muxing_queue_size 400 -method PUT "http://127.0.0.1:40421/%v/stream.m3u8"
Unrecognized option 'preset'.
Error splitting the argument list: Option not found
```

**Comment by sandboxgangster** [comment]
I've adapted and adjusted the code as written above.

ffmpeg with v4l2m2m encoder ran at home without patches, I've been using it for other projects for a long time, unfortunately only streaming the thumbnails doesn't work in Owncast.

Stream Works fine:

> ffmpeg started on 2023-03-31 at 01:25:54
> Report written to "data/logs/transcoder.log"
> Log level: 32
> Command line:
> /root/owncast/ffmpeg -hide_banner -loglevel warning -fflags +genpts -i ./data/tmp/offline.ts1447846778 -map v:0 -c:v:0 h264_v4l2m2m -b:v:0 2808k -maxrate:v:0 3032k -g:v:0 150 -keyint_min:v:0 150 -r:v:0 30 -map "a:0?" -c:a:0 copy -preset superfast -var_stream_map "v:0,a:0 " -f hls -hls_time 5 -hls_list_size 5 -hls_flags program_date_time+independent_segments -hls_playlist_type event -segment_format_options "mpegts_flags=mpegts_copyts=1" -pix_fmt yuv420p -sc_threshold 0 -master_pl_name stream.m3u8 -hls_segment_filename "http://127.0.0.1:45197/%v/stream-offline-%d.ts" -max_muxing_queue_size 400 -method PUT "http://127.0.0.1:45197/%v/stream.m3u8"
> Input #0, mpegts, from './data/tmp/offline.ts1447846778':
>   Duration: 00:00:08.09, start: 1.439333, bitrate: 1135 kb/s
>   Program 1 
>     Metadata:
>       service_name    : Owncast Offline
>       service_provider: FFmpeg
>   Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], 24 fps, 24 tbr, 90k tbn
>   Stream #0:1[0x101](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 113 kb/s
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_v4l2m2m))
>   Stream #0:1 -> #0:1 (copy)
> Press [q] to stop, [?] for help
> [h264_v4l2m2m @ 0x25726a10] Using device /dev/video11
> [h264_v4l2m2m @ 0x25726a10] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
> [h264_v4l2m2m @ 0x25726a10] requesting formats: output=YU12/yuv420p capture=H264/none
> [h264_v4l2m2m @ 0x25726a10] Failed to set gop size: Invalid argument
> Output #0, hls, to 'http://127.0.0.1:45197/%v/stream.m3u8':
>   Metadata:
>     encoder         : Lavf60.3.100
>   Stream #0:0: Video: h264, yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], q=2-31, 2808 kb/s, 30 fps, 90k tbn
>     Metadata:
>       encoder         : Lavc60.3.100 h264_v4l2m2m
>   Stream #0:1(eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 113 kb/s
> [hls @ 0x256f28d0] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
> [hls @ 0x256f28d0] Opening 'http://127.0.0.1:45197/0/stream-offline-0.ts' for writing7.49x    
> [hls @ 0x256f28d0] Opening 'http://127.0.0.1:45197/0/stream.m3u8' for writing
> [hls @ 0x256f28d0] Opening 'http://127.0.0.1:45197/stream.m3u8' for writing
> [hls @ 0x256f28d0] Opening 'http://127.0.0.1:45197/0/stream-offline-1.ts' for writing
> [hls @ 0x256f28d0] Opening 'http://127.0.0.1:45197/0/stream.m3u8' for writing
> ...

**Comment by gabek** [comment]
Looks like Raspberry Pi resolved this particular problem in the worst possible way.

They removed all video encoding hardware from the Raspberry Pi 5. So that's unfortunate. Going forward, it's going to be CPU encoding only, and you get what you get.

https://raspberrypi.stackexchange.com/questions/144475/did-the-raspberry-pi-5-drop-hardware-encoding-support

<blockquote><img src="https://cdn.sstatic.net/Sites/raspberrypi/Img/apple-touch-icon@2.png?v=38b7cb40765d" width="48" align="right"><div>Raspberry Pi Stack Exchange</div><div><strong><a href="https://raspberrypi.stackexchange.com/questions/144475/did-the-raspberry-pi-5-drop-hardware-encoding-support">Did the Raspberry Pi 5 drop hardware encoding support?</a></strong></div><div>Does the upcoming Raspberry Pi 5 have any hardware acceleration for video encoding? The technical specifications only list HEVC decoding, but there's no mention of hardware encoders. The reviews I've </div></blockquote>

**Comment by mattdsteele** [comment]
Ah bummer, I just bought a Pi 5 over the holidays and was going to experiment migrating my Owncast instance over.

For folks who do want to run Owncast on a Pi 4 with hardware encoding, I wrote up a guide at https://steele.blue/owncast-raspberry-pi-4/

<blockquote><img src="https://v1.screenshot.11ty.dev/http%3A%2F%2Fsteele.blue%2Fowncast-raspberry-pi-4%2Fsocial-card%2F/opengraph/_1705195045602" width="48" align="right"><div><strong><a href="http://steele.blue/owncast-raspberry-pi-4">Running Owncast with Hardware Acceleration on a Raspberry Pi 4</a></strong></div><div>Owncast is a self-hosted platform for streaming video, which I've been using for sharing all kinds of events, from Zwift racing to my wedding.
It's been really…</div></blockquote>

**Comment by gabek** [comment]
Curious how well the CPU is going to do at the job!

**Comment by gabek** [comment]
I'm going to close this, since the goal was hardware accelerated encoding on the Raspberry Pi, and they've removed support for that.

**Comment by mattdsteele** [comment]
I spent some time trying to migrate https://stream.steele.blue from a Pi 4 with OMX enabled, to a Pi 5, which requires software encoding.

My hope was the extra CPU on the 5 would be a sufficient replacement for the loss of a dedicated encoder. With some tradeoffs I think it's possible to configure, but we're not currently at parity.

My server is setup with two video streams:

* 1200kbps bitrate, Medium CPU, 30fps
* 4100kbps bitrate, High CPU, 60fps

This runs fine on the Pi 4 with hardware encoding. With the same settings on the 5, I was seeing a large number of dropped frames (30 to 50% according to OBS), and it was definitely noticeable watching the stream. CPU was generally around 70% utilization according to htop.

I was able to tweak these values to get a more reliable stream. Moving my HD stream to Medium CPU@30fps, and my SD stream to Low CPU@30fps allowed me to have two stream qualities without dropping frames.

Unfortunately, I'll probably end up sticking with the Pi 4 + OMX encoding for as long as it continues to function, and save the Pi 5 for another project, as the performance just isn't quite there. But thought I'd share my experience since the Raspberry Pi continues to be a popular platform.

If this would be better written up somewhere else, let me know!

<blockquote><img src="https://stream.steele.blue/logo/external" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Zwift Racing with Matt</div><div><strong><a href="https://stream.steele.blue/">Zwift Racing with Matt</a></strong></div><div>Physical esports done badly by a MAMIL</div></blockquote>
