### ISSUE TITLE
Initial load of page hangs on the skypack cdn

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#141]
There seems to be a blocking request pulling from the skypack cdn that stops the initial paint of the screen.  At this point in the game I wouldn't normally care about micromanaging performance, but it's pretty egregious.

**Comment by graywolf336** [comment]
I noticed this yesterday while testing it out locally, hung for about a second or two.

**Comment by gabek** [comment]
It's especially weird because it's supposed to be cached.

I thought about filing something with them, but I don't really know what to say about it.  I looked through their issues and nobody else is reporting anything.  It's more likely we're doing something weird with it, but I don't know how we could possibly be doing anything different.  It's pretty straightforward use: https://github.com/owncast/owncast/blob/aaeea2bb1d357d41427933b1d20644d42bbd75bc/webroot/js/components/chat/chat-input.js#L5

I guess we could just point to our own version of it and see if that makes any difference.

@mattdsteele Out of curiosity, have you ever seen anything like this before using modules with skypack's cdn?

**Comment by mattdsteele** [comment]
The main thing I see when using unpkg/skypack is relying on non-pinned versions of dependencies, which results in unnecessary redirects. But it looks like you're doing that properly.

It might be worth adding a preconnect tag to `skypack.dev` and `unpkg.com` , to warm up the DNS requests. https://web.dev/uses-rel-preconnect/

All the requests appear appropriately cached; I'm seeing the second request being pulled from disk cache.

I definitely see what you're referring to; the FCP (First Contentful Paint) is longer than you'd want.

A run on mobile with 3G using WebPageTest: https://webpagetest.org/result/200918_D9_1a2762744e4bdc45d0e07e27cd887253/

FCP is around 14s on first run, 3s with a cache.

That said, looking at devtools on your Owncast instance I'm not sure the issue is specifically with this specific request or Skypack specifically. My guess as to what's happening is that none of the Preact-driven components are rendering while the component tree is getting loaded and out; and the leaf components have dependencies on remote resources `emoji-button`, etc. which gives you an n+1 problem the more lazily you load your components.

To be honest, I'm not sure how to best resolve this! Preact has a [Suspense](https://preactjs.com/guide/v10/switching-to-preact/#suspense-experimental) feature which lets you render placeholder content while the real content is being fetched. Maybe we could load some of the non-critical components like Chat outside the main render, so the FCP happens earlier?

I think there are other ways to lazy-load components so it's not one giant render, but I'm not familiar with the libraries beyond route-based splitting, which isn't especially helpful here.

**Comment by mattdsteele** [comment]
I looked into this a little more, and think it might be more Skypack-related than I originally thought. For context:

The Skypack CDN is fronted by CloudFlare; when the files are cached, it's nice and speedy. On cache misses, Skypack generates the relevant file by transpiling the NPM module on the fly (I think with CF Workers); for whatever reason, it takes a very long time to do this with the `@joeattardi/emoji-button` module.

I've opened a discussion on the Skypack repo with more details: https://github.com/pikapkg/skypack-cdn/issues/54

I'm not sure why this module in particular is slow; other uncached Skypack files tend to transpile nice and speedy. I did see one potential perf optimization, which I submitted and got merged. When they publish a new version it's probably worth upgrading to see if it behaves better. https://github.com/joeattardi/emoji-button/pull/108

I'm going to hold off on doing anything here until we hear back from folks. And the perf approaches I described above (like lazy-loading Chat and others outside the critical render path) might still be worth doing too!

But if we do decide Skypack isn't worth the performance hit, there's a few approaches we could go with:

* Switch CDNs - In particular there's an NPM bundler+optimizer, which lets you do a single request and it'll return multiple modules: https://twitter.com/_developit/status/1261389109286719489
* Host files locally - I'd want to do this in a way that doesn't require a giant NPM toolchain. I think https://www.snowpack.dev/ is a useful tool here; we could generate a folder full of .js files and commit them locally, so folks would only need Node installed if they wanted to add a new dependency.

**Comment by gabek** [comment]
I guess I didn't think of it before, but Ironically this particular library is built as a ES Module, and I don't even think we need to be using Skypack?  :). Maybe we can just use any CDN, or pull it down locally without any other changes.

https://github.com/joeattardi/emoji-button/issues/77

**Comment by gabek** [comment]
Just tried with

```
import { EmojiButton } from 'https://cdn.skypack.dev/pin/@joeattardi/emoji-button@v4.1.0-v8psdkkxts3LNdpA0m5Q/min/@joeattardi/emoji-button.js';
```
And it seems to be function fine.  I'm not sure about performance.

**Comment by mattdsteele** [comment]
Good point; for this particular component we could just go back to loading it via unpkg; no muss no fuss.

At some point it would be nice to unify how Owncast loads vendor dependencies; but that doesn't have to be done as part of this work; and might not even be feasible with either unpkg or skypack as it stands right now.

**Comment by gabek** [comment]
Cool, pushed!  Thanks for thinking about, and looking into this.  I completely agree that it would be nice to unify dependencies.  I've even thought about maybe having a weird hybrid solution where in development we're pulling ad-hoc, but for actual releases we create a vendor bundle that ships with it.  That's probably overly complex to pull off.

I'll keep an eye out for cache misses, but I'm guessing it can't possibly be any worse :)
