### ISSUE TITLE
Allow stream output variants to be disabled

### ISSUE THREAD

**Issue by notnownikki** [owncast/owncast#1410]
We have 3 video variants set up, 720@60, 720@30, and 480@30. It's working nicely for folk, they get the variant suitable for their connection, all is good 😄 

Sometimes we like to stream fast paced video games at 60fps, sometimes we're just chatting and doing a bit of art, so we only need 30fps. It would be great if we could disable the 60fps variant so we could stream in 30fp, and re-enable it when we want to do a video game stream again. It's a bit of a pain having to input all the details again, and the new variant always appears at the bottom so it's no longer a nice High Quality to Low Quality list.

**Comment by gabek** [comment]
I have a suggestion!

Since the admin uses APIs that you're free to use yourself, you could write a little script that fires a `curl` command with whatever specific configurations you'd like for that point in time. And when you want to change it back, you run another little script.

For example, I just went into Chrome and saved an update to my video settings, and then _Copy as curl_ and it looks something like this: (take note the example username, password here is admin:abc123 so you'd need to copy your own hashed password).

```
curl 'http://localhost:8080/api/admin/config/video/streamoutputvariants' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Authorization: Basic YWRtaW46YWJjMTIz' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H 'Accept: */*' \
  -H 'Sec-GPC: 1' \
  -H 'Origin: http://localhost:8080' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:8080/admin/config-video/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cookie: _ga=GA1.1.632902543.1630304651' \
  --data-raw '{"value":[{"framerate":24,"name":"1.2Mbps@24fp","videoPassthrough":false,"audioPassthrough":true,"videoBitrate":1200,"audioBitrate":0,"cpuUsageLevel":2}]}' \
  --compressed
```

If you run it you'll get:
```
{"success":true,"message":"stream output variants updated"}
```
Obviously there's more junk in that request than required, but it's everything that copied from the browser and I didn't go through to prune it.

But in theory this is actually faster, since you can run it from wherever you like and not have to use the UI.

**Comment by notnownikki** [comment]
That would work! 👍 

Is this a feature you'd accept if someone (for example: me) was to implement it for you? If not, the script will work nicely :)

**Comment by gabek** [comment]
I think it's a perfectly sensible addition if you're interested in looking at it!

Could probably create a new `data.GetEnabledStreamOutputVariants()` to have everything (except the admin) use instead of `data.GetStreamOutputVariants()` and add an `Enabled` bool to `models.StreamOutputVariant` for filtering purposes.

**Comment by notnownikki** [comment]
Great! I'll see what I can do. Thank you!

**Comment by Semisol** [comment]
I think this would be useful. Some streams require lower quality than others for me, so I would be interested in using this.
