### ISSUE TITLE
Selecting an emoji immediately when visiting page without focusing text input ignores selection

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1419]
If the chat input isn't focused, selecting an emoji will do nothing.

Maybe we should forcefully give focus to the input field when selecting an emoji.

**Comment by MFTabriz** [comment]
This issue does not occur in Firefox 92:
![ff92](https://user-images.githubusercontent.com/39205857/135072615-f3ec89f0-40b1-4b71-8205-1e3e3aa11904.gif)
in Brave 1.26 (Chromium 91) it only happens when you first load the page:
![brave1 26](https://user-images.githubusercontent.com/39205857/135072769-2d6f9cb8-2913-4a08-8c5a-35c1e545388f.gif)
