### ISSUE TITLE
One-click deploy with service providers

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#143]
I've never used one of these one-click deploy systems/app marketplaces before, but it might be nice to support some of them.  Probably wait for a couple more releases in order to get further down the road, but I wanted to file this now to think about it.

I noticed [Rocket Chat supports a bunch](https://github.com/RocketChat/Rocket.Chat#deployment),  @graywolf336, has that been helpful in getting people up and running?  

Heroku may be a worthwhile place to start but I'll ask around and see if anybody has used any of these and what might be popular.
https://devcenter.heroku.com/articles/heroku-button

**Comment by graywolf336** [comment]
Without a doubt it has. In fact, our biggest deployment base is actually Snaps (https://snapcraft.io/). Then underneath that is Docker and then it is split out amongst several others. Digital Ocean is another big one of the smaller numbers. We don't see many Heroku due to their small machines and expensive pricing compared to what you get at DO and others.

**Comment by gabek** [comment]
Closing this in favor for #776 and #777.
