### ISSUE TITLE
Stream key configuration freeze install script

### ISSUE THREAD

**Issue by ericgaspar** [owncast/owncast#1435]
hi there, I maintain the Owncast YunoHost package: https://github.com/YunoHost-Apps/owncast_ynh.
As of version 0.0.9, the installation process seems to hang forever at this point: [stream key configuration](https://github.com/YunoHost-Apps/owncast_ynh/blob/c23b26cbb6db3a85c37eeee77494a756cff5304c/scripts/install#L123)
The script was functional with version 0.0.8. 
Any idea what is done wrong?
I have some install log output: https://paste.yunohost.org/raw/yibufohohu

**Comment by gabek** [comment]
I'm guessing it has to do with this change: https://github.com/owncast/owncast/pull/1355

We used to exit after changing the key, but now, like all the other cli options, we run Owncast with the new setting when specifying it instead of exiting.

**Comment by ericgaspar** [comment]
Thanks for the reply. What will be the best way to define a custom key in a script install context?

**Comment by gabek** [comment]
You can still specify the key, but you would specify it when running Owncast.  You could also use the API to set the key with the admin API, but that's also probably not very helpful to you.

There's currently no way to change settings outside of actually running the service.

**Comment by ericgaspar** [comment]
In fact there is a easy way. Adding `-streamkey` option to owncast.service works.
Thanks for your help!

**Comment by gabek** [comment]
Keep in mind that will actually run the service while saving that hard coded key.  So if the admin changes their stream key in the admin then it will get overwritten the next time it starts by what you put in the `streamkey` argument.

**Comment by ericgaspar** [comment]
yes good point... This new behavior introduced with 0.0.9 seems like a regression to me (for a script install point of view at least)...

**Comment by gabek** [comment]
I could see how it impacts you in that way.  But from the project standpoint `streamkey` was the only CLI option that didn't run the service with the supplied value, so that inconsistency was confusing.  Just like `rtmpport` or `webserverip` doesn't change and exit, `streamkey` shouldn't either, and this change fixes that.

I guess if I had to work around this I'd only set the key on first run, or as a part of an install script run the service once with the values to override the defaults.
