### ISSUE TITLE
Improve navigation in the documentation

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#1449]
Some pages e.g. [Viewer details](https://owncast.online/docs/viewers/) are not listed in the menu and they're not easy to reach.

The left-side menu, and the destination of next/prev buttons at the end of each page need to be updated.

**Comment by gabek** [comment]
I don't feel like there's room for _everything_ in the documentation menu, it already scrolls off the screen on my display.  I think we have to rely on linking to things from other places, for example that document you mentioned is specifically for this link in the admin, and less useful in other contexts:

![image](https://user-images.githubusercontent.com/414923/135768466-5608cfef-fced-45fe-85a3-ce1f518d0c6d.png)

In general I think linking to specific documents in places where they're most useful is a better solution than having every document in a list anyway, since nobody is going to look through that list. Search is also a good solution for people to find what they're looking for instead of a list.

However, if there's a way to offer up more documents in a way that is readable and organized, I'm all for it. But I don't think we can just keep adding more things in a bucket called "documentation".

**Comment by MFTabriz** [comment]
If I start from [https://owncast.online/docs/](https://owncast.online/docs/) the only way that I know for reaching that page is to type "viewer" [only works with the full word] to get suggested "viewers details" page. Searching for "geolocation" or a similar word returns nothing.
![image](https://user-images.githubusercontent.com/39205857/135768925-d873dd3c-c85a-4e44-8404-eed048205445.png)
I'm not suggesting to have everything at the left-hand menu, but there must be a better way for navigating the documents. We can also have a similar categorization as for the admin panel in our documentation and explain the relevant information to each admin page accordingly.

This is what we see at the bottom of that page which suggests there must be an order to the pages:
![image](https://user-images.githubusercontent.com/39205857/135769011-c7c79481-18c8-4f4b-9d6a-a642136c05de.png)

There are many options to improve the current situation. For example:
* adding full text search to documentations
* adding better description/key-words to help with the current search suggestions
* adding a site-map [just an organized list of the page titles and their descriptions]
* offering users a pdf download of the whole documentation if we can't provide any good solution for searching
