### ISSUE TITLE
Use a different term for "storage" 

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#1459]
"Storage" is a bit misleading of a term to use for temporarily storing the HLS fragments during a livestream. I would expect "storage" to refer to permanent storage of recorded videos.

Prior to the addition of the actual recording feature, I think it would be a good idea to rename this setting to something else so that the term "storage" can be used for the actual recordings once that feature is added.

See #1458 for an example of this confusion

**Comment by gabek** [comment]
While Owncast isn't using these services for long term storage, they are, as advertised, storage providers. If we called them "streaming providers" or something it would be misleading and incorrect.  As it stands we can say that most (if not all) S3 compatible storage providers can be used with Owncast and be accurate. If we called them something else then I'm not sure how to point people to the correct type of service.

I completely understand the confusion, but unfortunately that comes from people making assumptions instead of reading. If there was a way to reduce the amount of incorrect assumptions we should totally do that, but I'm not sure renaming 3rd party services is the answer.  The best I can come up with is saying "S3" instead of "Storage". While it doesn't explain what it does, it might reduce confusion.

**Comment by litori** [comment]
I think renaming it to CDN could be more suitable as it is what they are.  It clears up the misunderstanding of video storage.

**Comment by aaronpk** [comment]
I agree "streaming provider" is not a good name. I like "CDN" though! Especially because if you don't configure one of these providers you are serving the files from the instance itself, which sounds very much like not using a CDN.

**Comment by gabek** [comment]
CDNs work differently.  You put CDNs in front of your origin server, where with object storage we push content to an external server.  You could use a CDN but no storage provider, or a storage provider with a CDN, or a storage provider with no CDN.

**Comment by aaronpk** [comment]
The source of the confusion is that the current setting looks like this:

![image](https://user-images.githubusercontent.com/113001/139560969-d5405688-2312-4dc0-9442-11dfc0b062bb.png)

The "Storage Enabled" with the default "off" suggests that by turning it on, you will now be storing the livestreams whereas before it would not have stored them. This is misleading, since what's really going on is that with this setting off, it uses local storage for the HLS files.

If you want to keep the term "storage" for this, then a better name for this setting would be "External Storage: on/off"

**Comment by gabek** [comment]
I think changing to "External Storage" makes a lot of sense. Maybe to be even more descriptive, "External Object Storage" so people don't infer that it means "External Recording Storage" or something and is very specific about what it is.  The menu sidebar can be changed then, too.

**Comment by litori** [comment]
I would refrain from using the word "storage" in any iterations for this as it will be confusing when you add actual video storage later on.  Better to fix it now then having it come up again later.  Maybe "External Stream Relay" or "External Broadcast Relay"?

**Comment by gabek** [comment]
It's not a relay, these companies are storage providers :). Calling them something they're not is far more confusing for somebody trying to pay for that service. 

What Owncast doesn't do are recordings, replays, or archival. What it does have support for are third party external object storage providers.

**Comment by aaronpk** [comment]
I think that depends on how the recordings are implemented later. 

If the recording feature is more like keeping the video fragments around but making a nice index on top of them with thumbnails and titles and such, then really the final recordings would actually be the same as where the files are stored during the live show.

But if the recording feature was more like combining the video fragments into a single mp4 file that is exported somewhere, that's what I would think of as "storage" and where this might be a confusing overlap of terms.

I'm not sure what the plan is for the recording feature, but I was under the impression it was more like the former, where the same storage configuration would be used for both the live stream as well as playing back recordings.

**Comment by litori** [comment]
So what is the reason why we can't call it a CDN, "Content Delivery Network"?  We are basically offloading the HLS files to the "storage" providers so that the users retrieve the stream from the "storage" providers instead of the server.  This is exactly what a CDN does, it offloads traffic from the mains server.  An S3 server is basically distributed also in different regional locations.  Why are we stuck on the term "storage" when it simply causes confusion and does not offer what the word implies.

**Comment by gabek** [comment]
A CDN is a very different thing.  If I was using some software that said "Setup your CDN" and then I went and signed up for Fastly or BunnyCDN, and then the software asked me what my bucket name was I'd be pretty upset that I wasted time and money signing up for a CDN when they really meant object storage.

**Comment by gabek** [comment]
If the toggle is the single point of confusion, what about changing the toggle from the single word "Storage" to "Use object storage" or "Scale video with S3 storage" or something longer and more descriptive?

**Comment by litori** [comment]
Maybe look up the word "storage" and see why it can be confusing.  The implied definition of the word does not match the use case.

**Comment by gabek** [comment]
I know what "Storage" means.  These are storage providers.  It's what they do, they store.  Changing and closing as this discussion is no longer productive.

![image](https://user-images.githubusercontent.com/414923/141848325-031e8522-d6af-4ef4-9202-c983257dc71d.png)
