### ISSUE TITLE
[Feature Request] Ability to export chatlogs

### ISSUE THREAD

**Issue by 4censord** [owncast/owncast#1470]
I would like the ability to export the chat-log.

I would personally use csv, and something along the lines of
```csv
timestamp,username,message
2021-10-12T21:40:55+02:00,4censord,[Feature Request] Ability to export chatlogs
2021-10-12T21:40:56+02:00,4censord,"With escaped commas, see"
```

**Comment by gabek** [comment]
We currently do just the opposite, we actively delete chat messages completely from the database to keep the data storage low, mostly for privacy reasons since there's no reason to warehouse old chat.

I suggest if you have your own requirement to store chat indefinitely that you take advantage of the chat webhooks, allowing you to take any kind of custom action needed.
