### ISSUE TITLE
Obtain geolocation data from video viewers

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#1477]
At the moment, the functionality to obtain 'viewer details', which give you geolocation data of your viewers, is tied to those in the chat and not those that are watching the video. For a project such as mine, which uses the embedded video and not the chat (yet), I'm not able to obtain this information from the Owncast admin interface, and so use analytics on our website instead to serve this purpose. If I were able to see the geolocation data of those that are watching the video, I would no longer need a separate tool for this.

**Comment by gabek** [comment]
I think that makes sense.  The viewers table was removed since it was kind of a mix between viewers and chat. When chat and viewers were split up for user management purposes that information was made specific to chat connections.

I see no reason why we can't bring back a new viewers table that just doesn't have any chat information in it.
