### ISSUE TITLE
Support path-based S3 storage

### ISSUE THREAD

**Issue by aangiel** [owncast/owncast#1495]
Hi!

According to second paragraph of https://owncast.online/docs/storage/, I would to ask for integration with Oracle Cloud Object Storage.

It is compatibile with AWS S3 API, but unfortunatelly except one point:

https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#usingAPI ->
-> "Modifying your application" ->
-> point 4:

> Use path-based access in your application. Virtual host-style access (accessing a bucket as `bucketname.namespace.compat.objectstorage.region.oraclecloud.com`) **is not supported.**

Thanks!
Artur Angiel

**Comment by gabek** [comment]
Currently Owncast expects S3 providers to use host-style since AWS was deprecating path-based support (https://github.com/owncast/owncast/commit/b2953028cf6d9040dba2c41268fb3db62260b65a#diff-8d797b99f87223de9df31a2fd08d1d32aa3087c951a87a9e478b53f0e5e51a22).  There's nothing stopping us from adding a way to switch between the two, however.

If somebody would like to do that it's just an additional attribute passed to the s3 config: https://github.com/owncast/owncast/blob/develop/core/storageproviders/s3Storage.go#L186

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/s3Storage.go at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/s3Storage.go at develop · owncast/owncast</div></blockquote>

**Comment by aangiel** [comment]
Tomorrow I'm gonna update docs
