### ISSUE TITLE
Slow webhooks servers might cause delays

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#1504]
The webhooks are run sequentially for one event, meaning that a chat message was first send to the first applicable webhook, and only to the next when it has closed the call.

This might create significant delay if one webhook recipient is slow in its response (e.g. if they're doing expensive operations on their end).

**Comment by gabek** [comment]
I do think the webhooks should be tweaked, but for a bit of a different reason.

In your example a slow server delays the other webhooks.  I think that's ok because it limits the number of inflight webhook connections per chat message sent.  But the real downside is if a bunch of chat messages get sent at once.  Then there _are_ a bunch of inflight webhook events, and to make it worse, each chat message would be hitting the slow server that you mentioned, possibly making the slow server even slower because additional load.

So while it sounds like you'd like to see all outbound webhooks to be fired concurrently, I think they should be queued up to both keep the number of concurrent outbound connections to a reasonable level, and to not hammer webhook endpoints.

Reworking webhooks as a queue is something I've planned on doing eventually, but it's pretty low on the list since I don't think many people use them, and even if they did they don't have enough chat load to create a real problem with hammering endpoints.

**Comment by jeyemwey** [comment]
> and to make it worse, each chat message would be hitting the slow server that you mentioned, possibly making the slow server even slower because additional load.

I see where you're going here, but this would happen regardless if many chat events happen at the same time since the firing is not queued at all. My proposed changes would only remove the delay for the other webhook urls.

> I think they should be queued up to both keep the number of concurrent outbound connections to a reasonable level, and to not hammer webhook endpoints.

This would require some proper queue management since every event immediately fires the list of webhooks right now. To protect the webhook endpoints, we'd need to keep track of the number of active connections to each of them. A worker pool might clog up with slow requests which would mean more even delays for the events.

**Comment by gabek** [comment]
Yeah, that's what I'm saying, have an actual managed queue so the rate of requests can be controlled.  In general I'd rather have delays due to rate limiting than send hundreds of concurrent web requests to some endpoint because somebody's chat was popular.

I'm not saying we need to build that now, but it's something to keep in mind if we're going to add more concurrency to the outbound requests.
