### ISSUE TITLE
Random stream playback problems due to thumbnails?

### ISSUE THREAD

**Issue by TicTac9k1** [owncast/owncast#1524]
So far I've been using OwnCast with success for some time now, but recently an issue popped up where people told me they can't watch certain instances because the stream never loads. The only thing I can find in the log files is a big list of the message;

Unable to generate thumbnail: exit status 1.
https://i.imgur.com/tJYXrLx.png

The deployment seemed fine. The problem occurs for random people at random times which makes troubleshooting annoying but the logs are consistently reporting the error every thumbnail update. For me this has only occurred once in months of use. When this happened the Play button is overlapping the thumbnail, and also indicates its loading, but it never plays the stream.

**Comment by gabek** [comment]
I'm guessing the issues you are experiencing aren't because of thumbnails not being able to generate, but instead thumbnails are unable to be generated because of whatever problems you're experiencing.  Thumbnails are generated from your stream, so if your stream is unavailable or invalid in some way the thumbnail generator will likely throw errors.  So I wouldn't look too much down the thumbnail route for the source of the problem.

What has changed since you started seeing the issues?  Is your stream source different in any way, or your server configuration been changed?  Are you using passthrough mode in your video settings?

**Comment by TicTac9k1** [comment]
I'm using video passthrough. It's been some time but I've also upgraded from I think v0.0.7 to v0.0.10 though people never reported any issues until now, which I hoped they'd report sooner. I'm running Owncast dockerized on one VPS, while another webserver is serving a website with Owncast's embed. In between that there is a reverse proxy on yet another VPS because we require https. Which wasn't ideal but it seemed to work, at least from the small scale testing I did.

I've changed the latency buffer to medium and we've been experimenting different keyframes (2/3)
So, yeah there's been quite some changes that weren't tracked that didn't look like it could cause problems, but it's kind of hard trying to track this problem down at the moment due to the complexity of the setup. 

If anything the reverse proxy might have something to do with it. But the DNS is set directly to the VPS Owncast is hosted at.
Another thing I can try is reverting to 0.0.7 since the issue isn't as clear cut and work my way back.

**Comment by gabek** [comment]
The first thing I'd always suggest if there are video issues that are unclear is to turn off video pass through.  Please turn that off and retest.

**Comment by TicTac9k1** [comment]
Well, I turned it off, but the VPS wasn't able to handle it. A 720p60 stream would chug the server 100% with 7 viewers. Where as hardware accelerated it sits comfortably at 20%. So i've enabled it again, but the weird thing is just how selective the problem occurs. When no one with problems is watching, the stream throws no errors about the thumbnails. As soon someone who has consistently had the problem starts watching, it throws the error.

**Comment by gabek** [comment]
Oh I guess I'm confused.  You said you're using passthrough, but you also say you're using hardware acceleration.  Passthrough bypasses the entire video encoding pipeline, meaning you can't use a hardware accelerated codec if it's enabled, it also means anything "bad" or unplayable about the inbound video gets passed along directly to the viewers.  A VPS also generally won't have access to a GPU meaning you can't take advantage of hardware accelerated encoding.

I'm not sure if you've read through it, but here's what passthrough is doing: https://owncast.online/docs/video/#video-passthrough

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/video/">Video</a></strong></div><div>Configure your video to manage the quality and hardware performance.</div></blockquote>

**Comment by TicTac9k1** [comment]
My bad, got the terminology mixed up. When I said hardware acceleration I did mean video passthrough. I'll read the doc, but from what I understood about video passthrough is, it just functions as a simple passthrough of a stream. No transcoding of any kind. Which is what I want because the VPS runs it on only needs to be transferring the data since processing capacity is limited. 

The problem is that some users have no problems at all, while others can't even load the stream. Which I'm not fully understanding because to my knowledge it should be either a) everyone has the problem or b) no one has the problem.

**Comment by gabek** [comment]
That would be the case if you were using Owncast to properly encode the video, either it would work for everyone or it wouldn't. But because you're not allowing Owncast to encode the video then you're handing off in whatever state the video isdirectly to the viewers, so it's very possible that some viewers may be able to view it while others can't.

Since Owncast isn't doing the encoding here I'm unfortunately kind of at a loss on how to help.  I strongly suggest you don't use passthrough because of issues exactly like what you're experiencing, and instead work on reducing CPU usage https://owncast.online/docs/troubleshooting/#cpu-and-ram-usage-alerts.

But if you're going to try to use passthrough you might be able to tweak settings in your broadcasting software to make it work.

1. Make sure your broadcasting software's key frame is not "auto" since that might break things and set it to 2 seconds.
2. Experiment with different codecs and encoding settings in your broadcasting software.

Sorry the answer of "don't use passthrough" isn't great, but it's the answer.


<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/troubleshooting/">Troubleshooting</a></strong></div><div>Some categories of issues you might run into and some next steps to help troubleshoot.</div></blockquote>

**Comment by TicTac9k1** [comment]
Thanks for your help. I didn't realize this could potentially be a problem by using pass through. At least it gave me insights where to look next. I really want to keep overhead down by having pass through enabled, so I'm gonna keep looking for the cause and look for a possible solution for now.

One error I noticed was this. So I guess in this specific case it could be related to the color format used.
[swscaler @ 0x558372943a00] deprecated pixel format used, make sure you did set range correctly

I'm gonna go and fiddle around some more in the hopes I'll find the root cause, otherwise I'm just gonna have to accept spending some more money on better hardware. 

Edit:
It's related to the color format, in OBS instead of using the full color range setting it to partial the people who've had issues can watch the stream.

**Comment by gabek** [comment]
That's great you were able to track down what specifically on the broadcasting side would fix it!

I'll use this opportunity to mention that some viewers still might have issues because you're only offering a single quality, at the source bitrate and resolution. Those with slower networks or on mobile networks might require a lower quality version from you, so keep an eye out for people complaining of buffering.  I know you don't want to do encoding on your server, but offering a lower quality version will enable a better viewing experience for a wider audience.

**Comment by gabek** [comment]
I'm going to go ahead and close this since it sounds like you're in good shape, but feel free to re-open or create another issue if something else comes up!
