### ISSUE TITLE
Offline State in stream.m3u8

### ISSUE THREAD

**Issue by graywolf336** [owncast/owncast#153]
We are embedding the `stream.m3u8` into our mobile app, however, when there is no livestream there is nothing that displays. It would be nice if when the stream is offline, the offline state is displayed like the website does.

**Comment by gabek** [comment]
That's the downside to `resetDirectories` being fired, it's literally being deleted.  All of this should be addressed in #9, however.

The web site is just showing a static placeholder image, and the player is hidden when the stream is offline.  That's probably the best approach for a mobile app, too.  If it's not live, but a player is available, I could see people being confused and thinking something is broken.  So that's why we don't make it available on the web.

**Comment by gabek** [comment]
I just pushed a commit to re-create the offline state after we added the firing of `resetDirectories()`.  Should take care of that empty stream issue.

**Comment by graywolf336** [comment]
Yeah, I was going to comment and say that having the offline state generated after cleaning up is probably a good idea and works perfect for my use case. Sadly, I don't have very much control over how the app is handled and what is shown, so going this route helps. 👏 

I'll close this as it was solved by 6903db8. Thank you!
