### ISSUE TITLE
IP banning of users

### ISSUE THREAD

**Issue by Semisol** [owncast/owncast#1534]
As it stands, users may clear their storage to bypass bans.  
This feature will make bans also apply to IP addresses. When a ban is made, the username and IP will be banned.

### Small note

About the development moderation GUI, it seems like you can ban people which disconnected. Due to this, a list may need to be maintained in memory to also ban the IP.

**Comment by gabek** [comment]
I'd love to hear if others would want this as well.

**Comment by closewall** [comment]
> I'd love to hear if others would want this as well.

Last time I ran a stream, I had a big problem with this mentally unstable person who kept spamming rapidly and coming back 30 seconds after being banned.
I'm all for making it more difficult to evade bans, so I'd definitely want this.

**Comment by Semisol** [comment]
I haven't encountered anyone to ban yet, but I'm worried I might sometime later.

**Comment by gabek** [comment]
My thought is, there's always a way. If we add IP banning then they just use a VPN and they evade the ban that way.  And then we have to add browser fingerprinting?  And then they use a new browser or block browser attributes from being read, etc etc.  I just fear that this might never end if the expectation is that Owncast as a piece of software can stop people from being horrible, because that's unfortunately impossible. They will find a way, and each way gets more invasive about how much information we have to store about people so we can block them later.

**Comment by Semisol** [comment]
I'd say leave VPN blocking and similar to the site owner. The basic suite of protection could be a few things:
- Disable anonymous chat (in real time, so a reload isn't required)
- IP banning
- User identity/domain banning with future IndieAuth support.

**Comment by gabek** [comment]
> Disable anonymous chat (in real time, so a reload isn't required)

Agreed. That's filed in #1239.

> IP banning

Just for sake of argument, if VPN blocking should be the responsibility of a site owner, why shouldn't IP blocking? What's the difference?  It's all just IPs.

> User identity/domain banning with future IndieAuth support.

This will never be a way to block people. Almost nobody will use IndieAuth, and even if they did, why would somebody who's purposefully a jerk login via a method that personally identifies themselves?

I'm not saying we _shouldn't_ have IP blocking, but I am saying that this is only one small step to blocking people, and there's 1000 more ways for jerks to get through.  So drawing a line in the sand is required where Owncast can't say "we have ways to stop anybody", because that's impossible.  It's impossible for Twitter and Twitch and Facebook, too.  So knowing where to draw that line is important because every feature that's added is a feature that needs to be not just built, but tested, and maintained and is a responsibility.  And when it comes to features that are built to stop people, there's no end in sight to the ways people can gain access. So in general I'd rather err on the side of fewer features and more transparency instead of more features, complexity and false confidence.

**Comment by Semisol** [comment]
> Just for sake of argument, if VPN blocking should be the responsibility of a site owner, why shouldn't IP blocking? What's the difference? It's all just IPs.

We can't currently see IPs and it would be different from VPN blocking in my opinion.  
I would do a VPN block as a firewall denial (most of the time), while user blocks are manual.

> This will never be a way to block people. Almost nobody will use IndieAuth, and even if they did, why would somebody who's purposefully a jerk login via a method that personally identifies themselves?

Hmm, you are right.

I would just end it at IP banning, to be honest.

**Comment by gabek** [comment]
I like the idea of storing hashes of IPs, but that would eliminate being able to do networks or IP ranges. What granularity would you expect to be able to block?

**Comment by Semisol** [comment]
Hmm, interesting question... There's still another workaround of hashing `1.2.3.4/32`, ... in between ..., `1.2.3.0/24` but that would also result in the problem of losing track of ranges. So I'd say actually hashes for individual IPs but CIDRs should be stored as plaintext.

**Comment by Semisol** [comment]
And about unbanning, if someone is banned, how do we know which ban was it? Do we include a reference number somewhere in the page with the ban notice?

**Comment by closewall** [comment]
> My thought is, there's always a way. If we add IP banning then they just use a VPN and they evade the ban that way. And then we have to add browser fingerprinting? And then they use a new browser or block browser attributes from being read, etc etc. I just fear that this might never end if the expectation is that Owncast as a piece of software can stop people from being horrible, because that's unfortunately impossible. They will find a way, and each way gets more invasive about how much information we have to store about people so we can block them later.

I get that it's impossible to completely stop someone from evading, but I still think it should be harder than it is right now. At the very least, having IP bans would disincentivize banned users from coming back because it becomes just that little bit more time-consuming, especially for people who aren't tech-literate.

**Comment by hollunder** [comment]
To start with a little taste of what we are dealing with pretty much every night on Hatnix' stream.
![modern_art_1](https://user-images.githubusercontent.com/8207622/145676137-233556f2-988e-47c2-9e19-4a8960afa7b6.png)
![modern_art_2](https://user-images.githubusercontent.com/8207622/145676142-2b1c1f94-26ff-419f-a934-8fc9ab98ecc8.png)
It's almost modern art, isn't it?

Clearly the current moderation is meaningless, as it apparently can be evaded simply by changing the name.

Possibly related: the second picture is from last night, you can see on the overlay that the chat got stuck, so for almost two hours Hatnix thought that no one was writing anything anymore. Whether that was triggered by the spam or due some unrelated bug I can not say.

As much as Hatnix dislikes it, I think we need to do something.
One possible solution I think we should try is a IP-based timeout. This is how I imagine that to work.

1. The streamer or a moderator, once that exists, could timeout a user and that would work based on the IP rather than the name.
2. This would last either for the duration of the stream (or some predefined value, no need to get fancy here). This way there is no need to permanently store data, no need to maintain an ever-growing list of banned users, which is probably also better in terms of GDPR and such.
3. Caveats: The offender needs to be either:
a) Unaware that he is banned via IP or
b) Unable to easily change his IP

There is no perfect solution to this, not even with accounts. Just look at Twitch, they have accounts and yet they recently introduced some AI-based ban evasion detection. https://safety.twitch.tv/s/safety-news/detail?language=en_US&post=Using-Machine-Learning-to-Curb-Ban-Evasion

What I propose is by no means a perfect solution, but my hope is that it is sufficient to discourage spammers and the likes. It is intended to make it more annoying for the spammer to avoid the timeout than it is for the streamer to time out the spammer.

**Comment by gabek** [comment]
> Clearly the current moderation is meaningless, as it apparently can be evaded simply by changing the name.

Just for clarification, the current banning method isn't by display name. It's by chat account. To evade a ban you must use a private browser/incognito tab, or go into your browser's local storage and clear the reference to your account so Owncast will create you a new one.  I only clarify this because it shows that these people are going through some effort, and actually looking into, how to get around this ban. So it's likely these same people are the same kind that would be willing to restart their TOR service or VPN each time they get banned in order to get a new IP.

I'm not saying it shouldn't be done, but I am saying these people will evade those bans as well, and like you said, there's no perfect solution and I want to set expectations.

I'm wondering if there are other options. Owncast currently has some rate limiting to stop people from using a bot or a script to automate the flooding of the chat with messages. Maybe it should be significantly lowered to stop people from _manually_ flooding the chat with messages. That might impact real people as well who want to type a quick "lol" after hitting enter from a previous message, but maybe it's worth it.

**Comment by nebunez** [comment]
Just my .2: I don't think there is any good solution for moderation without requiring authenticated user accounts. I know that there are reasons for not wanting this (including scope of the core project), but if there were an option for authenticated accounts for chat moderation, I would use it. It's important to note, that people could still watch the stream without needing authentication in this scenario.

**Comment by gabek** [comment]
Just so this discussion about IP banning doesn't go too far into registered/non-anonymous user accounts, please see https://github.com/owncast/owncast/issues/464 if people want to see the history behind that discussion or add to it.

**Comment by gabek** [comment]
And not to dilute the IP banning conversation, but one thing I think that's worth adding is given there's no perfect technical solution, better manual solutions should be made available and that's already being worked on.  [Moderators, and inline moderation](https://github.com/owncast/owncast/pull/1331#issuecomment-948235352) will be available in the next release allowing for faster moderation, and by more people. If you can't stop everyone at least be able to shut them down faster.

**Comment by hollunder** [comment]
> Just for clarification, the current banning method isn't by display name. It's by chat account. To evade a ban you must use a private browser/incognito tab, or go into your browser's local storage and clear the reference to your account so Owncast will create you a new one. I only clarify this because it shows that these people are going through some effort, and actually looking into, how to get around this ban. So it's likely these same people are the same kind that would be willing to restart their TOR service or VPN each time they get banned in order to get a new IP.
> 
> I'm not saying it shouldn't be done, but I am saying these people will evade those bans as well, and like you said, there's no perfect solution and I want to set expectations.

Thanks for the clarification.
What we have been seeing is that the spammer is back very quickly after a ban, I think below five seconds. That's why I'm saying that the current method is meaningless, it is simply too easily circumvented. Inline moderation is not going to change anything in that regard.

I do not know whether this particular spammer will be able to circumvent an IP ban just as easily. I hope not and I sure would like Hatnix to try.
I do not think rate limiting is going to help much, for example one such message per second is plenty enough to be totally disruptive.

The question is, what other options do we have?

**Comment by Semisol** [comment]
IP bans are the only reasonable way.	 For Tor, you could block tor users but there are reasons to use Tor too.

**Comment by gabek** [comment]
> The question is, what other options do we have?

When IP banning goes in and people start using VPNs and Tor to evade the bans you'll still be asking that same question.  So start thinking about that now. Because I'll probably have to say "we've run out of technical solutions, so moderation is probably the answer".

**Comment by gabek** [comment]
Side moderation discussion idea: https://github.com/owncast/owncast/issues/1587. Separate from IP banning, but another idea on top of it.

**Comment by Semisol** [comment]
> Side moderation discussion idea: #1587. Separate from IP banning, but another idea on top of it.

Looks good! IP banning + that will probably be fit for most cases.
