### ISSUE TITLE
Only one user should be able to hold a nickname

### ISSUE THREAD

**Issue by Semisol** [owncast/owncast#1542]
Currently, multiple users can hold one nickname. This can create problems such as impersonation. Due to this, I think only one user should have a nickname at a time.

**Comment by gabek** [comment]
The approach with names is they are display names, nothing more. And the real attributes behind a user are what count. If somebody joined only 5 minutes ago and are going by "Gabe", where I first joined 2 months ago and I'm also "Gabe", then I'm the real "Gabe". That's why we surface that information when you hover over a user's display name in a chat bubble. User colors also matter. If I've been blue Gabe for months, and now there's a green Gabe, then blue Gabe is the real Gabe. For admins you also get the username history of a user so you can see if they purposefully changed their name to be a jerk and you can get rid of them if that's the case.

Limiting duplicates would add more confusion than could exist now because it would stop somebody who rightfully wants a name to not be able to have it if some jerk previously took it.  Then do we need an interface for admin to change people's names if there's a discrepancy? 

I know adding more software to solve people problems is inciting, but they're just patches.  People being horrible will continue to be horrible.

That being said, as always, if this is a specific problem that adding more features will solve, then it can be discussed and worked on.

**Comment by Semisol** [comment]
Makes sense. Is there any checks for color & name pair duplicates, though?

**Comment by gabek** [comment]
Nope, the color is randomly generated when a user is created.  To be honest I never remember anybody's color, so I'd be lying if I said that's a good way to determine who is who anyway, but it's something. The user created date I rely on all the time as a guest to people's streams to know if this is somebody who just dropped by or it's somebody who's been around, though.  If two people had the same name it'd be easy to tell them apart by that alone.  But I know it's not perfect.

**Comment by gabek** [comment]
I guess my concern here is anybody can drop by and change their name, and that simple, quick, action doesn't feel like it should lock that name out for all time.  If somebody two years ago stopped by for 10 seconds and called themselves Gabe, I'd be annoyed if I couldn't be "Gabe" years later.  The reason this is different than other services is because Owncast doesn't require you to create an account to chat. If accounts were required then having a unique name makes sense because you have to go through the effort of creating a unique account anyway.

So then maybe we can say "ok, you can't call yourself X if X is already connected", like IRC.  And maybe that's an ok way of doing it, but all that means is two people with the same name can't both occur _right now_, but all you have to do is wait for the person to leave and then you change your name, and then two people could both be online with the same name going forward and you don't know if you should trust name exclusivity or not.

So maybe you say you can only take a name if the person with that name hasn't visited in the past X amount of time.  And maybe that's better, but it still means you can't trust name exclusivity because that person might come back and you'd have two of the same names.

So that's why I'm kind of treating names as a label, and not an identity, if that makes sense.

**Comment by Semisol** [comment]
Thank you for the explanation of your view. I guess I'll close it now.

**Comment by gabek** [comment]
That being said, I'm totally up for making things better.  I know this isn't optimal, but I just haven't come up with something that seems clear and fair.  So let me know if you think of something! It's possible the drawbacks listed above are better than the drawbacks of not having some restriction at all, and if so, then I'm totally up for discussing that.
