### ISSUE TITLE
Insta360 One X2 RTMP stream

### ISSUE THREAD

**Issue by wasp604** [owncast/owncast#1555]
I'm trying to get my 360 camera to stream to owncast. Is there any way to get it to show up as a movable 360 perspective, like 360 youtube live videos do? It currently shows the raw, full 360 scene all at once.

**Comment by aaronpk** [comment]
Cool idea! Looks like there is a videojs plugin for 360 video so that could certainly be a possibility: https://github.com/videojs/videojs-vr


<blockquote><img src="https://opengraph.githubassets.com/6a9ecceb7a5081f793b898501568e5759e2dcbdc25c1a5eeac30cdb5214c8056/videojs/videojs-vr" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/videojs/videojs-vr">GitHub - videojs/videojs-vr: A plugin to add 360 and VR video support to video.js.</a></strong></div><div>A plugin to add 360 and VR video support to video.js. - GitHub - videojs/videojs-vr: A plugin to add 360 and VR video support to video.js.</div></blockquote>

**Comment by gabek** [comment]
That looks like a cool solution, and should hopefully be not terribly difficult to add to the player configuration.  If you open up webroot/js/components/player.js you can see how the player is configured there, and if you follow that videojs plugin's instructions you should be able to add it.

If you want to walk through it together feel free to drop by our chat as if you want to play with it in real time with somebody.  Otherwise I can add some specifics later when my internet comes back online (stupid Comcast).

**Comment by wasp604** [comment]
> That looks like a cool solution, and should hopefully be not terribly difficult to add to the player configuration. If you open up webroot/js/components/player.js you can see how the player is configured there, and if you follow that videojs plugin's instructions you should be able to add it.
> 
> If you want to walk through it together feel free to drop by our chat as if you want to play with it in real time with somebody. Otherwise I can add some specifics later when my internet comes back online (stupid Comcast).

The instructions say to add some script tags:

```
<script src="//path/to/video.min.js"></script>
<script src="//path/to/videojs-vr.min.js"></script>
<script>
  var player = videojs('my-video');

  player.vr();
</script>
```
...which I've filled in with the relevant information:
```
<script src="//home/d/node_modules/video.js/dist"></script>
<script src="//home/d/node_modules/videojs-vr/dist"></script>
<script>
  var player = videojs('my-video');

  player.vr();
</script>
```

Where would I add this? In webroot/js/components/player.js ? I've been messing with it for at least an hour now and can't figure it out.

**Comment by gabek** [comment]
I suggest using a copy of that plugin on a CDN somewhere instead of you having to learn how NPM works.  "path" in this case means the path within NPM, not the path on your hard drive. If you want to learn how NPM works you should read through that, but it's probably easier just to use a remote copy.

Video.js should already be loaded.

```
<script src="https://cdn.jsdelivr.net/npm/videojs-vr@1.8.0/dist/videojs-vr.min.js"></script>
```

**Comment by wasp604** [comment]
Ok, you've lost me there.

The instructions offer only three ways to use it:
- <script> Tag
- Browserify/CommonJS
- RequireJS/AMD

None of these mention a CDN.

Where would I find said CDN? All that sounds extra-complicated.

> `<script src="https://cdn.jsdelivr.net/npm/videojs-vr@1.8.0/dist/videojs-vr.min.js"></script>`

and I can't find this anywhere in the player.js . Am I supposed to look elsewhere?


I'm used to plugins meaning I download a file into a plugins folder of some sort.

P.S: If you haven't noticed, I'm quite the novice regarding streaming, Linux servers, etc. There's a lot of expected knowledge that I don't have here.

**Comment by gabek** [comment]
I looked it up for you. The following script tag loads the script from a CDN so you don't have to use NPM (node_modules).

```
<script src="https://cdn.jsdelivr.net/npm/videojs-vr@1.8.0/dist/videojs-vr.min.js"></script>

```

**Comment by aaronpk** [comment]
I tried hacking this up on a test instance but wasn't able to get it to work. The content security policy blocks loading that script from the CDN. I tried downloading it to the webroot folder, but it looks like the main videojs library is being loaded in such a way that bringing in the vr plugin this way doesn't work. When I try to run the initialization line right after the main videojs object is created it throws an error like the library doesn't exist:

```
this.vjsPlayer = videojs(VIDEO_ID, VIDEO_OPTIONS);
this.vjsPlayer.vr({projection: '360'});

...
Uncaught TypeError: this.vjsPlayer.vr is not a function
```

I think it would need to be bundled in the same way as the other videojs plugins.

**Comment by aaronpk** [comment]
I bundled videojs-vr with the npm install method and that seems to have gotten farther, but I'm still getting that same error. Here's what I've done so far:

https://github.com/aaronpk/owncast/commit/093bbea7c5f4c3d5cf33d2773bfc933959576ee3

**Comment by s00500** [comment]
this would be so cool to have working, any tips on the status where this was left ? maybe I find some time to continue a bit..

**Comment by gabek** [comment]
Unfortunately, I don't know anything about this plugin, but hopefully it's in a further place than it was three years ago that you can use it now.

**Comment by s00500** [comment]
Hm... so I played with this a bit and made a very simple working player by copypasting the readmes (did this on my server on nano, so sorry for the mess)

```
<html>
<body>
<h1>Test VR</h1>
<link href="//vjs.zencdn.net/8.21.1/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/8.21.1/video.min.js"></script>
<script src="/public/videojs-vr.min.js"></script>
<video
    id="my-player"
    class="video-js"
    controls
    preload="auto"
    poster="//vjs.zencdn.net/v/oceans.png">
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a
    web browser that
    <a href="https://videojs.com/html5-video-support/" target="_blank">
      supports HTML5 video
    </a>
  </p>
</video>
<script>

// Video setup
const VIDEO_SRC = {
  src: '/hls/stream.m3u8',
  type: 'application/x-mpegURL',
};
const VIDEO_OPTIONS = {
  autoplay: false,
  liveui: true,
  preload: 'auto',
  controlBar: {
    progressControl: {
      seekBar: false,
    },
  },
  html5: {
    vhs: {
      // used to select the lowest bitrate playlist initially. This helps to decrease playback start time. This setting is false by default.
      enableLowInitialPlaylist: true,
      experimentalBufferBasedABR: true,
    },
  },
  liveTracker: {
    trackingThreshold: 0,
  },
  sources: [VIDEO_SRC],
};

  var player = videojs('my-player', VIDEO_OPTIONS);

if (!player.mediainfo) {
  player.mediainfo = {};
}


if (!player.mediainfo.projection) {
  player.mediainfo.projection = '360';
}


  player.vr({projection: '360'});
</script>
</body>
</html>
```

**Comment by s00500** [comment]
Now a few things to note, this does work quite well....
(tested on my Insta360 X4)
But if you want to consume content on lets say an occulus quest you are still better off using the normal player view and then switching to VR mode (in eg Firefox Reality)

So far to my quick tests, maybe it helps anyone out there :-)
