### ISSUE TITLE
Add "restreaming" documentation

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1638]
Owncast will never have "restreaming" functionality, it's a streaming server, not a streaming client. But enough people ask about it and consider it a barrier of entry that it's worth adding some documentation around suggestions to answer their question.  While we'd obviously love to have people using Owncast exclusively, using it along side YouTube or Twitch is better than them not using it at all.

https://github.com/muesli/prism is the obvious suggestion because it's free, open source, and made by @muesli.  But we can also point to Restreamer.

**Comment by deepto98** [comment]
@gabek Can I work on this?

**Comment by gabek** [comment]
Sure, thanks!  Our documentation repo is at https://github.com/owncast/owncast.github.io

I said "Restreamer" above but I meant Restream.io: https://restream.io/

<blockquote><img src="https://opengraph.githubassets.com/bdc4bbd210b2007fad329b86615c535161807f61e6475b5b14463178853b2ab2/owncast/owncast.github.io" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast.github.io">GitHub - owncast/owncast.github.io: Owncast's public facing web site.  Documentation and info.</a></strong></div><div>Owncast's public facing web site.  Documentation and info. - GitHub - owncast/owncast.github.io: Owncast's public facing web site.  Documentation and info.</div></blockquote>
<blockquote><img src="https://restream.io/landings-assets/img/og-image-home-9533bef037b40a397f1f5e508a1fe060.png" width="48" align="right"><div>Restream</div><div><strong><a href="https://restream.io/">Reach a Wider Audience with Multistreaming | Restream</a></strong></div><div>Restream is the #1 multistreaming solution. Stream live to YouTube, Twitch, Facebook, and 30+ platforms at once. Get started today.</div></blockquote>

**Comment by muesli** [comment]
Happy to help out here as well, but let me point out that `prism` isn't quite as universally working as I'd like it to be. I'll probably have to change out the underlying RTMP lib.

**Comment by geekgonecrazy** [comment]
This is super duper alpha quality but based on @muesli work on prism. Adds a UI and an api to allow dynamic adding / removing of destinations: 

https://github.com/geekgonecrazy/prismplus

I'd like to figure out how to make a few changes up stream to prism so we can consume it as a library instead of duplicating the code.  Or if prism wants some of this extra bit would happily contribute it back as well.

<blockquote><img src="https://opengraph.githubassets.com/641352399a46fa46b74d60bb99cf83ae62300f5922948e0731073b4a4ac3f111/geekgonecrazy/prismplus" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/geekgonecrazy/prismplus">GitHub - geekgonecrazy/prismplus</a></strong></div><div>Contribute to geekgonecrazy/prismplus development by creating an account on GitHub.</div></blockquote>

**Comment by gabek** [comment]
Sounds like for now we're limited to recommending only Restream.io.

**Comment by hex-m** [comment]
For users which prefer a self-hosted FOSS solution, OvenMediaEngine supports [RTMP push publishing](https://airensoft.gitbook.io/ovenmediaengine/push-publishing).
