### ISSUE TITLE
Feature: Invitation links for "guests" to a wedding being streamed

### ISSUE THREAD

**Issue by djpbessems** [owncast/owncast#166]
I wonder if it would be a possibility to create a feature where you can create unique invitation links to allow access to the stream (and send them through email/facebook/etc).

When people use these links, they'll obviously be logged in automatically with whichever username the administrator has given them (imagine for instance "uncle Bob and auntie Mary"), and they won't be able to use features like change their username or set a password.

An extra possibility for this feature: each such invitation would then allow for a limited amount of concurrent logins (so in the cause of "uncle Bob and auntie Mary", two simultaneous sessions).

Usecase for this feature would be to make it as easy as possible for the older generation to use the stream to participate remotely in a weddingparty.

**Comment by gabek** [comment]
Hey there, thanks for the thoughts and specifics around the use cases!

While building specific features to cater to people who have very unique requirements probably isn't in our long term plans, we can break some of these ideas into more generalized features that might be useful to everyone.

I could see having a feature where a link already has the person's username pre-filled in.  But if one person has a "personalized" link, and then they share it with their friends, they'd all have the same username.  So it would have a built-in flaw, unless, like you said, you were limited by the number of people who have that username, and that just feels like a workaround to the flaw and creates error states for users and flows they'd have to go through.  It would rely on the client to make these decisions because we don't have auth or user registration of any kind, and client security is no security at all.

Something instead that's been brought up, is when visiting the site for the first time you get prompted for your username upfront, and only once.  We'd then make the change username feature less obvious, as they already set their preferred name.  This personalized link could pre-fill in that initial username, but allow them to change it immediately so not everyone is "Uncle Bob and Auntie Mary".

I think this is something we will probably continue to think about as we find the sweet spot between full user auth and no identification at all, and personalized links might be a reasonable thing to support.
