### ISSUE TITLE
Chat character count ending in a space results in unexpected value

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#169]
I think because we're calling `trim()` on the string when counting its characters we get this kind of confusing result where you can jump between between non-ordinal values when a space is involved.  We should decide if this is what we want.

![Untitled](https://user-images.githubusercontent.com/414923/93738348-6bc79a00-fb9a-11ea-9f71-7779bdef4114.gif)

**Comment by gingervitis** [comment]
eww. 
I guess the easy route would be to not trim() before counting.

or we could remove all the white space before counting, but you'd still end up with the awkward delete char behavior.

or we could trim, then move the cursor. but I feel like that might also result in some awkward feeling behavior.

**Comment by gingervitis** [comment]
on a related note, should white spaces count as individual `&nbsp;`s? 

one could type something like
<img width="330" alt="image" src="https://user-images.githubusercontent.com/9563255/93803433-b4fb0680-fbf9-11ea-9dd5-2c45a110ce7c.png">

but end up with
<img width="303" alt="image" src="https://user-images.githubusercontent.com/9563255/93803472-c2b08c00-fbf9-11ea-93fe-44c344507251.png">

**Comment by gingervitis** [comment]
^ if yes, then that would support the easy case of not needing to do  a `trim()` before counting :)

**Comment by gabek** [comment]
I don't see any reason we need to support elaborate custom whitespace.  No need to be drawing ASCII art!

**Comment by Pranav2612000** [comment]
I'll like to work on this. Setting up the project now. The main aim is to display accurate counts, even if the chat ends in a space, right? Anything else I should know?

**Comment by Pranav2612000** [comment]
I was able to start the client side at port 8080 using go run main.go(after installing dependencies). But the chat is disabled(Is that because the stream is offline). How do I enable chat? Also, to test the website, will I need to download and use a broadcasting software, or are there some other testing mechanisms?
Sorry for a lot of questions! I am sorry if they have been answered somewhere else. I couldn't find answers to these in the docs.

**Comment by graywolf336** [comment]
> The main aim is to display accurate counts, even if the chat ends in a space, right?
You have that correct, we need to display the accurate character count.

> Also, to test the website, will I need to download and use a broadcasting software, or are there some other testing mechanisms?

Yes you will. A software like OBS, free and open source, will be required to get started. :)

**Comment by gingervitis** [comment]
@Pranav2612000 to enable chat, you can do a quick local hack by setting the enableChat prop=true to the chat component from app.js.

Just make sure you set it back later 😉.

Also I believe @gabek has included a script in the latest codebase to allow you to actually run a stream locally so you won't have to do that temp hack.

**Comment by gabek** [comment]
Yeah!  If you have a video file around try starting the owncast server and then from the command line:

```
./test/ocTestStream.sh ~/Downloads/big_buck_bunny_720p_surround.mp4
```

Or whatever video file you happen to have around.  If you want to point it at a specific instance & stream key

```
./test/ocTestStream.sh ~/Downloads/big_buck_bunny_720p_surround.mp4 rtmp://localhost/live/mystreamkey
```

**Comment by Pranav2612000** [comment]
@gingervitis @graywolf336 Thanks a lot. @gabek Thanks a lot for pointing to the script. Although I couldn't use the script directly - Because I think it expects the video names without spaces, I used the ffmpeg command in the script. Another issue I faced was an error `x264 [error]: main profile doesn't support 4:4:4`. I solved that using the modification suggested here - https://stackoverflow.com/questions/37967120/ffmpeg-convert-from-h-264-high-444-profile-to-h-264-main-profile/37969294

After this, the chat is enabled, and I can see the timer, with the text "Stream is online". But I cannot see the video that I streamed. Did any of my modifications to the previous ffmpeg script cause this?

Also, regarding this issue, the problem is if a user types a 500 character message with the second last character(s) as space(s), 
those spaces arent considered in the count(as they are trimmed) until a last non-space character is added at the end. So, when the last character is typed, the count suddently changes to a non-negative value. So, if we have a way to count the spaces at the end, it should solve the problem. Right?
Thanks again.

**Comment by gabek** [comment]
Mind posting your video somewhere?  I'd like to see what's happening with it.  It doesn't really impact the chat, but if there's some type of inbound video we're not accepting I'd like to track that down.  Thanks!

**Comment by gingervitis** [comment]
@Pranav2612000 I think the most straightforward solution to this is just to count whatever spaces there are, even the ones at the end. So basically not calling `trim()` when counting, though I'm not sure if this will affect calculations in other areas?

**Comment by Pranav2612000** [comment]
Removing trim() causes the backspace to function weirdly. For e.g - typing a space, and then backspacing it results in inputCharLeft to change to 499. This is because the formfield.innertext doesn't change to an empty string.
Looking for an alternative fix, keeping the trim().
