### ISSUE TITLE
Move away from xgo in building releases

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1756]
It's been a nice solution for cross-compiling, but it's extra moving parts and the original project has been archived, requiring a fork.

Finding a new cross-compiling solution that supports cgo is needed.

**Comment by gabek** [comment]
https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/

https://docs.earthly.dev/docs/guides/multi-platform

**Comment by lfuelling** [comment]
<details>
<summary>In case you're interested in my edge case opinion...</summary>

I've had to patch out `xgo` to get the buildscript to work in my fork (on arm64 macOS) because the docker images it uses are not available for my architecture.

I also tried adding cross compilation using the `GOOS` and `GOARCH` env vars which seems to work for projects not requiring `CGO` but unfortunately sqlite seems to need it and I was unable to get cross compilation to work without major bloat in the build script and without requiring developers to install a lot of different additional packages. I'm currently building linux binaries in a VM 🙃 

From this experience I'd suggest using multiple GitHub (sub) Actions to build the release archives on the intended platforms and limiting local builds to not be cross platform. 
</details>

**Comment by gabek** [comment]
I'm curious why you've had to use xgo to build Owncast. Local builds never have to be cross platform, since you're building with your native toolchain and architecture. The only person who's had to deal with those is me when I do a release of Owncast, and it's been working ok with xgo, but I'd prefer not to have the dependency. But like you said, as long as there's cgo, there's going to more bloat to get cross compiled builds working, and there's no getting away from that.

My current plan is to use `Earthly` with images that support the toolchains required. But I'm not trying to target everyone on every OS and every architecture being able to run it. Mostly I'm just targeting cleaning things up for myself since I've been the only one who uses it.

**Comment by lfuelling** [comment]
I tried building a linux binary on arm64 macOS because I didn't had go on the linux machine.
