### ISSUE TITLE
Chat auth using the Fediverse

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1774]
I've never seen a way for people to use their Fediverse identity to create a new account somewhere.  It's just not what it's built for. But I think I came up with an idea.  I'm not sure if it's a good one. I'm usually a proponent of using the right tool for the job, and this isn't really that. But it might be something.

By abusing the remote follow flow, we can have a user verify their identity on a remote Fediverse server.

1. User says they want to authenticate with Owncast chat and types in their remote Fediverse account.
2. Owncast creates a temporary virtual ActivityPub entity with inbox attached to this chat user.
3. Owncast starts the remote follow flow, redirecting them to their Fediverse server.
4. Remote follow flow is successful and the remote Fediverse server sends a "Follow" event to Owncast, for this virtual inbox.
5. Owncast accepts this follow request and makes the connection between the remote Fediverse identity and the local chat identity.

If the user wants to login again, a new virtual inbox would get created and the user would "follow" this completely new virtual entity, and create another connection.

The downside is this Fediverse user would then have fake entities listed as things they follow and that's pretty annoying.  But maybe Owncast can send a "Delete" event to the remote Fediverse server after this flow is complete so this fake entity can be removed.

**Comment by gabek** [comment]
As the resident auth'ist, do you have any thoughts on this @aaronpk?

**Comment by aaronpk** [comment]
This does sound like it would technically work, but I'm not sure it's a good long-term strategy. 

One problem that stands out off the bat is the user experience of this. The user would end up on their instance's remote follow page, which would have no idea what's actually happening, and would have text around following this account. The account would probably have to be some sort of funny looking username, and they would have to click the "Follow" button, when really they aren't intending to follow the account at all. And since this page is not hosted by Owncast, you don't have any control over what it says, so you'd have to explain that to the user ahead of time.

I do think it would be a better plan to do a proper OAuth flow, which is where I was going with the IndieAuth discussions. I was hoping Owncast could demonstrate how IndieAuth can work on the Fediverse, and encourage more Fediverse software to add IndieAuth to their OAuth implementations.

**Comment by gabek** [comment]
I'm totally with you that the user experience would be a mess, with no real way around it.

I'm still totally on board with IndieAuth, in fact, I have a version of it working. I just need to come up with some UI for it. But unfortunately what people want is to use their Fedvierse identity, even though there isn't a supported way to make that happen.

I've had multiple people ask me "you let me follow using my Mastodon account, why can't I login to chat?" and the answer is "because you just can't".  I understand why that doesn't make sense for people, so I wondered if I could find _some_ solution to allow people to do what they think should logically be possible.  And until Fediverse software supports OAuth I fear we might have to be creative.

**Comment by aaronpk** [comment]
Tangentially related: I've actually been thinking about doing something similar to this for my YouTube livestreams, to connect YouTube viewers with a user account on my own website. Since I can't really use the Google OAuth API for it (too many hoops to jump through regarding approvals and rate limit increases and such), my thought was to do a verification dance via the YouTube live chat.

You could do something similar here that might be a bit less obtrusive than abusing the follow feature. What about:

* The user clicks a "connect" button in the Owncast chat UI
* Owncast displays a unique code to them, and instructs them to @ mention the Owncast main account and that unique code in a post
* They'd go to their Fediverse account and write a normal post mentioning the Owncast main account and copy the code, and could even make that post unlisted so it doesn't broadcast it to all their followers
* Owncast would receive a mention from this previously-unknown Fediverse account, and would match up the unique code with the chat user

Plus: Easier to explain "mention this account and XYZ1234 in a post" than to explain away why they have to follow some weird account
Minus: Requires manually copypaste of this string instead of leveraging the "remote follow" feature to bring it over

**Comment by gabek** [comment]
haha I was just thinking of something very similar, but backwards, as a OTP flow.

1. Owncast asks you what your Fediverse account is.
2. Owncast sends you a private/direct message with a code.
3. You input that code into the Owncast UI.

While a OTP approach would be streamlined, it could be used for abuse, putting other people's accounts in there. But I'm guessing that could be rate limited or resolved in some way. 

The approach you mentioned above would totally work as well. OTP would require the user to accept private messages from possibly not previously known accounts, where verifying an account via a message wouldn't have that restriction.
