### ISSUE TITLE
Implement WCAG 2.1 compliance

### ISSUE THREAD

**Issue by Jookia** [owncast/owncast#1826]
OwnCast is fairly inaccessible at the moment. The most obvious are:

- Bad use of contrast
- Small text
- No skip links
- Poor keyboard support
- Poor screen reader support

It would be nice if OwnCast took a serious stance on accessibility.

**Comment by gabek** [comment]
Thanks for the comment!

There's plans in the works to redesign and rebuild the Owncast frontend. This time around it'll be built with a UI framework that should hopefully give a head start with making sure individual components are accessible.

On top of that hopefully you might be able to give some insight when the new design is getting built on what needs to be improved on.

**Comment by gabek** [comment]
I ping'ed the Ant thread about in progress accessibility issues. https://github.com/ant-design/ant-design/issues/22343

And for clarification, since I didn't mention it, the reason the plan is to use Ant Design is because it's already been used to build the Owncast Admin UI.

**Comment by Jookia** [comment]
The Owncast Admin UI is actually the less accessible part of the UI from what I've played with. It looks like Ant doesn't really have a plan or priority for accessibility, meaning you'd likely have to fork Ant to fix it.

**Comment by gabek** [comment]
I'll make another plea here that since the project is currently only me, I could desperately use some web frontend help.

**Comment by Jookia** [comment]
Rebuilding both the admin and frontend with some more accessible framework is probably the better idea

**Comment by Jookia** [comment]
I've decided I'm going to sit down sometime next week or this week and dig apart the OwnCast admin code and see what needs to be done for screen reader accessibility.

**Comment by Jookia** [comment]
Alrighty, my spam continues in this thread. Sorry, but also not that sorry.
I took some notes regarding keyboard and screen reader support. A lot of WCAG compliance can be done with visual changes, such as text size, fonts, etc- but these are things I assume you already know how to do as it's part of doing web development usually.

So I sat down and opened Orca (installable in Linux easily) and started to use the arrows and tab/space/enter to navigate the admin panel. That's the basic workflow for testing screen reader and keyboard accessibility: Actually trying to see if it reads properly and can be navigable using the keyboard. It's important to note that screen readers have a special 'browse mode' that grabs the arrows keys and other keys by default so you can easily read text line by line. Javascript components have to make sure that the screen reader will switch to 'focus mode' in some cases to grab inputs like arrows.

Anyway, here are my notes:

The general UI:
- There's no skip link to skip the menu
- The menu's focus indicator doesn't work well
- The menu doesn't work in browse mode, I think it should be grabbing focus
- Accordion elements grab focus instead of acting like push buttons
- Table headers aren't interactable easily with keyboard
- You can't skip tables easily
- Horizontal sliders don't speak the current value

Home page:
- Streaming URL/Key copy buttons should be labeled better
- Browse mode doesn't focus a button

Chat page:
- Checkboxes aren't labeled

Configuration page:
- Switches aren't labeled
- Tags can't be removed using keyboard
- Markdown editor doesn't seem to have focusable elements but still lets you enter markdown

Video page:
- Close button for message about only having one variant isn't focusable
- Browse mode gets stuck at the video passthrough toggle
- Setting video codec brings up an unfocusable/unreadable dialog

Help menu:
- Full of 'learn more' links, they should be 'Learn about ...' so you can tab through them easily without getting confused

A lot of these are easy HTML fixes, a few might require a lot more time getting Ant to be ARIA compliant. It does look like the project takes pull requests and is a little bit active about ARIA stuff.

**Comment by Flameborn** [comment]
Tested the frontend here with VoiceOver under MacOS. Most of what @Jookia mentioned is also an issue here, although VoiceOver can get to more things at times, which makes the browsing experience much better. Here are my findings in addition to what was mentioned:

When using the admin UI, the navigation menu definitely needs some work when it comes to the keyboard. Navigating with the up and down arrows work, but keyboard focus is not set.

At the moment, the menu is always expanded, so it's difficult to determine when the user would want to focus it. I suggest collapsing it initially, and binding it to a link or button to expand and set focus to the first item. This would also allow skipping the menu easily, if one can collapse it with the escape key. If this is visually not feasible, ARIA could be used to collapse it just for screen readers only, though this would be more work.

Switches are exposed as a standard switch control, which VoiceOver has no issues reading or interacting with.

When removing tags, the remove button is exposed as an image labelled *Close*, which can be only clicked on to remove the appropriate tag. I suggest adding a *button* role, making it focusable and also binding the click event to the space bar, so that it can be used via the keyboard as well.

The client is usable, e.g. I was able to start playback in Safari, as it is exposed through a standard video player control.

It would be very useful to mark the chat history as a live ARIA region, so new messages read automagically.

My final thoughts: right now, Owncast is more accessible than commercial alternatives, but some minor tweaks could really make it shine.

Later on, some sound effects could be added for various events, e.g. when users join or leave or send a new message, but this is beyond the scope of this issue of course.

**Comment by Jookia** [comment]
I did a bit of work today on getting some of the major issues with the front-end fixed. I've published it in my fork, version v20220417: https://github.com/Jookia/owncast/releases/tag/v20220417 If you think anything looks interesting I'll do a PR.

I think most the headache is going to be on implementing the chat region as a widget of some sort. I'd like to see users be able to tab in to it and scroll with arrow keys to read and moderate chat.

**Comment by Jookia** [comment]
Alright, I did a little bit more work on my fork today and released a new version. Main changes are removing emojis from window titles (the colored circles are confusing) and adding an alt tag to the moderator icon in chat.

This is where I'm going to stop for now at this point. Chat is still fairly broken:
- Emotes don't read alt text in Firefox due to a 3 year old bug
- Navigating through chat is a headache using the keyboard and there's plenty of opportunities to trick screen readers

Fixing this will likely require rewriting chat to provide text alternatives for screen readers. As the chat is arbitrary HTML this would require stepping through the HTML and serializing it to text.

Most likely in my fork I'll just disable Markdown and emotes and have things be plain text.

**Comment by gabek** [comment]
Could you please be a little nicer? You filed something a couple days ago and you're really upset that I don't know what you know about the subject. I'm not an accessibility, or even web frontend expert. I'll have to learn about this stuff. I appreciate your insight, and I'd really like to make some progress on this. I look forward to being able to do that but it's not something that can magically occur overnight. 

You might be fine with removing complete features, but I'm not. It'll take time to go through these issues and make changes that work without doing things like wholesale ripping out markdown or title notifications, for example. Not to mention, like I've told you, how major changes to the UI are planned in the future, so doing a deep dive into our existing frontend is not the best use of time.

I 100% suggest you use Twitch if it fits your needs better. Owncast isn't for everyone and it never will be, nor is Owncast trying to convince people to leave Twitch if you prefer it there. I'm sorry Owncast is not what you'd like it to be.

I appreciate the updates, but I'd really ask for you to be a bit more understanding.

**Comment by Jookia** [comment]
How would you like me to be nicer?

**Comment by jprjr** [comment]
> A lot of WCAG compliance can be done with visual changes, such as text size, fonts, etc- but these are things I assume you already know how to do as it's part of doing web development usually.

This comes off as somewhat condescending, because it implies the project author knows about WCAG guidelines and is choosing to not implement them / being lazy, or alternatively: they're not a great web developer if they're not familiar with making accessible websites.

I don't know the author, don't know their background - this could be their first project to gain traction and accessibility hasn't come up before. Maybe they've done web dev professionally or maybe they haven't, and even if they have done professional web dev - still not a guarantee that it's come up. 

From looking at the committers list, this is mostly a one-person effort. I've worked at places where somebody's *entire job* was ensuring all our products were accessible. Nobody can be an expert in everything.

> I might just jump back to Twitch given issues like this.

Stuff like this is not at all necessary when reporting a bug. If the issue remains unfixed, don't announce you're leaving for the alternative - just go.

***

Now as mentioned, there are a lot of issues with the web front-end and accessibility. The author has stated they intend to rewrite the front-ends. In the meantime, I'm sure they would appreciate fixes to the current front-end, if you make it easy for them to integrate. Make it so they can just merge a pull request while they focus on the rewrite.

With that in mind, making a fork and just saying "go look at my fork" comes off as kind of rude - why not open a pull request or a series of pull requests? The changes in the fork are mostly sensible, straightforward changes. I'd recommend taking related changes and making a series of small, easily digestible pull requests that the project owner can evaluate individually.

Like a pull request that fixes the placeholder texts, a pull request that corrects some of the semantic elements, a pull request for removing the emoji from the document title. This way the author can review and the "no-brainer" stuff like updating placeholder texts - just merge it. That's a *very* easy small change. But for things like the green/red icon in the document title - maybe there's another solution using aria live regions? But that fork, in it's current state - has unrelated changes like changing the version number scheme, meaning the project owner has to go through, cherry-pick what they'd like, etc. The onus is on them to take time, parse through it, etc, as opposed to getting a packaged, ready-to-be-integrated pull request.

This isn't the kind of thing that a single person can fix overnight. In my opinion, the chat needs an overhaul to not send HTML on the wire. I have an issue open on that (#1803), and another issue (#1828) kind of requires sending plain-text to be implemented. This alone winds up requiring changes like:

* either move markdown rendering to client-side, or ensure the server sends both plain-text and html versions
* changing how JSON is encoded server-side (right now it's using `json.Marshal` which escapes HTML, odds are that needs to be changed to send both plain-text and escaped HTML or just send plaintext and render client-side).

And probably more that I haven't thought of yet, and this is a relatively small piece. But once a plain-text version is available, it opens up a lot of options - like instead of disabling emotes entirely, that could be presented as an option to the user, or do whatever is needed (I'm not sure) to ensure emotes are presented well to screen-reader users.

There's only so many hours in a day. It will require time. If you need a solution *right now* and there's an alternative, that's probably the way to go, otherwise try to work *with* the person instead to implement these fixes.

**Comment by Jookia** [comment]
I don't have the energy to deal with this. Sorry for any offense/etc, I've deleted my posts and fork and unsubscribing from this issue.

**Comment by gabek** [comment]
With the frontend rewrite slowly starting, accessibility best practices are built right into the component development process. This should be a good start in doing the right thing for each component.

![image](https://user-images.githubusercontent.com/414923/168194861-2b8e75d5-b290-4628-8d4d-de062058c543.png)

**Comment by rkingett** [comment]
I've tested the front end on Windows with the free screen reader, NVDA, and this is what I found. The biggest barrier is controls and menu items not getting keyboard focus.

I'd consider making the chat a live aria region to make it output to screen readers automatically.

When using the admin pages, the main navigation  menu, the keyboard focus isn't set, which makes it very dificult to navigate and interact with items.

It appears as if the menu is always expanded? I honestly couldn't tell, but this is also causing focus issues and it makes navigating quickly a slight hassle, because I can't collapse menus.

Skip navigation, adding more skip links at the beginning of the DOM will help many users, including keyboard only sighted users. I'd recommend, skip navigation, skip to player, and skip to footer.
when a user is trying to filter, the remove filter buttons appear as an image labeled close for some reason. I'd make these standard HTML buttons so they can be bound to the space bar, the click event. Basically, with HTML, you get more keyboard functions for free!

The player uses standard controls, which is fabulous! I couldn't immediately find any issues there.

Overall, while some work needs to be done, this is, honestly? Not a bad start. Could someone point me to the new design or a discussion about the new design? I'd like to play with it.

**Comment by gabek** [comment]
Hi, @rkingett, thanks for the feedback!

Unfortunately the redesign is in _very_ early days, and there's nothing to show, and likely won't have anything for some time. All the new components are being worked on at https://owncast.online/components, but that's not likely a terribly useful source of anything unless you're actively working on the project.

That's correct that the admin sidebar menu is always there.  The admin is currently composed of Ant Design components, and I'm aiming to use more of those components for the new UI of Owncast as well. When you say you're filtering, what do you mean by that?  Is this the admin tables?  That's the only place I can think of that you can filter different data.

As far as I've seen the accessibility of these ant components we're using in the admin aren't perfect, but I believe they're better than the zero accessibility that we currently have in the 100% home built UI, so hopefully it creates a starting point.

Admittedly I'm not familiar with what skip links or a live region is (I don't personally come from a background of frontend web development, but trying my best!) but the more notes we can compile here the more research I can do to learn about it. I've also been trying to find some frontend help from those who have a background in it. Hopefully with the complete UI rewrite using better components along with some knowledge of what can be improved thanks to feedback from people like you, all of this can be improved.

Thanks again!

<blockquote><div><strong><a href="https://owncast.online/components">Webpack App</a></strong></div></blockquote>

**Comment by gabek** [comment]
Colors, fonts, contrast, and readability for the redesigned web UI is being worked out currently.

**Comment by gabek** [comment]
It was [recommended](https://linuxrocks.online/@bgtlover/108919572391476288) we use https://github.com/AlmeroSteyn/react-aria-live. It's old, so I'm not sure if it works at all, but there might be something newer, too.

<blockquote><img src="https://opengraph.githubassets.com/37d9c80d4dc03cc377beda5a46ec10c385d804f97fe7c67873ded5bc3c605d80/AlmeroSteyn/react-aria-live" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmeroSteyn/react-aria-live">GitHub - AlmeroSteyn/react-aria-live: ARIA live message announcer for React apps</a></strong></div><div>ARIA live message announcer for React apps. Contribute to AlmeroSteyn/react-aria-live development by creating an account on GitHub.</div></blockquote>

**Comment by Flameborn** [comment]
> Skip navigation, adding more skip links at the beginning of the DOM will help many users, including keyboard only sighted users. I'd recommend, skip navigation, skip to player, and skip to footer.
I think this is a bit too verbose. While skipping to the footer area is a logically sensible idea, one rarely needs to interact with items in the footer to warrant an extra skip link.

One *Skip to Content* link should be enough, while adding regions for the important areas, such as the chat history and the player would make screen reader navigation a lot easier.

> It was [recommended](https://linuxrocks.online/@bgtlover/108919572391476288) we use https://github.com/AlmeroSteyn/react-aria-live. It's old, so I'm not sure if it works at all, but there might be something newer, too.
This is mainly for sending speech events only to a screen reader. For items that are visually displayed in a logically structured container, marking up the container via the [log](https://www.w3.org/TR/wai-aria/#log) role for example makes a lot more sense. I believe this container in our case would be the *div* with the *messages-only* id.

The downside to this, as well as to the recommended component, is that embedded items, e.g. emoji as images will likely not read properly in a live region. They will need a text-based representation, possibly  sent from the server.

<blockquote><img src="https://opengraph.githubassets.com/37d9c80d4dc03cc377beda5a46ec10c385d804f97fe7c67873ded5bc3c605d80/AlmeroSteyn/react-aria-live" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmeroSteyn/react-aria-live">GitHub - AlmeroSteyn/react-aria-live: ARIA live message announcer for React apps</a></strong></div><div>ARIA live message announcer for React apps. Contribute to AlmeroSteyn/react-aria-live development by creating an account on GitHub.</div></blockquote>

**Comment by synergic777** [comment]
With my mockup redesign I am trying to make contrasts matching WCAG requirements. Would you adjust something?
https://design.penpot.app/#/view/bc0c6ce0-3683-11ed-a5c2-cf2300df1f4f?page-id=bc0c6ce1-3683-11ed-a5c2-cf2300df1f4f&section=interactions&index=0&share-id=af09e910-3696-11ed-a332-c67f7655c7b3

**Comment by Flameborn** [comment]
Sounds great. Thank you for the update.

When things are ready, I’d be happy to go through via multiple screen readers and post some feedback.

**Comment by gabek** [comment]
Attached is an accessibility scan performed by the HAN University of Applied Sciences. While unfortunately it's for the original UI, as tested on `watch.owncast.online`, it does give us datapoints to compare against in the new web interface to make sure it's better than it was before and the items listed are addressed in webv2.

[HAN Report watch.owncast.online.pdf](https://github.com/owncast/owncast/files/10190230/HAN.Report.watch.owncast.online.pdf)

**Comment by azyklus** [comment]
I would like to be assigned to this issue.

**Comment by gabek** [comment]
Awesome, thank you! :D

**Comment by gabek** [comment]
@azyklus What parts specifically are you looking at?

**Comment by gabek** [comment]
@azyklus Hi there, just checking in again to see if you're still looking at this. If not I'll go ahead and unassigned and start through through the attached PDF of issues from the web v1 UI and start cross referencing with the new v2 UI.

**Comment by gabek** [comment]
Going to make this comment a checklist of things to either add or verify.

## Add

- [x] Skip to content link
- [x] Skip to player link
- [x] Skip to footer link

## Verify these are not problems

These are copied from the above webv1 accessibility report. Webv2 should not have the same issues and if they still exist, they should be resolved.

- [x] Label in the chat is missing, placeholder is not enough.
- [x] Input field for the chatbox does not have the acurate role . 
- [x] The account dropdown button in the rightcorner does not contain a status when opened, this should be communicated by assistive technologies such as ‘open/closed’ or with aria-expanded.
- [x] When changing the username, the input field with placeholder ‘Update username’ does not have an associated label.
- [x] When changing the username, the purple check button next to the input field does not have an assessible name. The cancel button has a title attribute but this is not sufficient. We would advise to use the alt-attribute in the SVG for placing the text alternative.
- [x] When opening the modal ‘Authenticate with chat ‘ the collapsable content with tekst: ‘Learn more about using
IndieAuth to authenticate with chat.’ does not have contain a status when opened, this should be communicated by assistive technologies such as ‘open/closed’ or with aria-expanded.
- [x]  The logo image does not contain a tekst alternative in the alt attribute but contains informative content.
- [x] When toggling the chat with the button ‘Toggle chat’ does not have contain a status when opened, this should be communicated by assistive technologies such as ‘open/closed’ or with aria-expanded.
- [x] The video does not have a accessible name, a div region container contains a aria-label with tekst ‘Video Player’ but this in not on the right placement and does not contain relevant information. We advice to give the video element an accessible name such as the title of the video.
- [x] In the video player the button for Settings does not contain an accessible name.
- [x] The tekst under the videoplayer ‘Stream is online.’ is a statusmessage but not communicated as such. Make sure the status message has a role such as aria-live when important information is given. The frequency of the changing information could be disruptive for the user so the timer/clock should be left out.
- [x] When looking the website on a viewport of 320px, the inputfield with text ‘Type here to chat, no account necessary.’ is not fully readable. This is also a problem for the text ‘Owncast’ in the top navigation.
- [ ] When looking the website with the settings for text spacing, the inputfield with text ‘Type here to chat, no account necessary.’ is not fully readable.

**Comment by gabek** [comment]
I'm not sure what this means:

> When looking the website with the settings for text spacing, the inputfield with text ‘Type here to chat, no account necessary.’ is not fully readable.

"Settings for text spacing" isn't something I'm familiar with, so I'm going to leave this marked as incomplete. If anybody else knows what this might mean please do chime in.

**Comment by gabek** [comment]
Since this issue is a large, overarching issue that was more of a discussion and less of providing specific action items I'd like to close it in favor of filing specific actionable items, otherwise this issue will just stay open forever with limited detail. However, I don't want to disconnect future conversation from the people in this thread that offered to help or want to stay up to date.

So by closing this I'm not saying "accessibility is done", because that's not the case, but individual tasks should be filed for individual todos. I can say, however, that I've gone through above feedback as well as the Web v1 accessibility report and compared all the items to the Web v2 and either verified (to the best of my ability) they are no longer an issue or made a change to address it. I don't know where that puts us as far as accessibility completeness goes, but I genuinely hope it's significantly better than it was. But this is primarily limited to making sure items have labels and roles and such and I'm in no way saying from a functionality standpoint it's better, worse, or the same with Web v2.

So I'm going to ping all involved here to make sure they see this, I hope you're still all willing to provide continued feedback and will file issues as we move into a broader testing phase soon.

@azyklus @Flameborn @rkingett @jprjr

**Comment by azyklus** [comment]
That’s cool with me. I was admittedly struggling with the scope of the issue and haven’t had all that much time lately anyway. If possible, however, I would like to be assigned to the issues you just referenced this in so I have a couple of places to get started on. @gabek

**Comment by gabek** [comment]
Sounds good! Feel free to click through to any of the issues I'm linking here and comment so I can assign you.

For reference what I'm doing now is loading up the web interface with the [Wave accessibility evaluation tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) and filing issues for items that seem valid.
