### ISSUE TITLE
Idea: swappable chat backends

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#1829]
Hi there, just thought I'd toss this idea out there - what if Owncast could be configured to use different chat backends?

So the thinking goes, by default - use the current chat system with the fairly ephemeral nicknames, users in local storage, possibly support fediverse auth, and so on.

But, allow admins to specify say, an IRC room or XMPP room, and have Owncast use that.

When a client connects, the frontend would connect to Owncast via websocket, as it does now - and still send message and receive messages about the same way. Owncast would open a connection to the backend chat service and be responsible for converting the client-sent messages to the correct protocol. It could use the `PROXY` protocol to inform the backend service of the incoming IP info. It could have bot credentials for performing administrative actions, or maybe you just say if you're using a different backend, you're on your own for moderation, which I think most users would be fine with. If they're taking the time to set up and configure an IRC server, they're probably fine with performing bans and such with their own IRC client.

This would change a few things in the admin interface - like if the user configures a different chat backend, the part for listing IP bans should probably be disabled.

The main pro of this is it outsources accounts. I recall in #464 there were concerns over having an account management system, GDPR, dealing with users forgetting passwords, and so on. All that becomes a non-issue, since it would now be the IRC or XMPP server's responsibility to manage all that, and Owncast would just be a thin client. This would give a lot of flexibility to owncast users, and allow them to create and enforce policies however they see fit (maybe they require registration to chat, or have a server-side component to filter swear words before it goes to other participants, stuff like that).

**Comment by jprjr** [comment]
Should also probably mention, I'm happy to help develop this - but figured I should see if this is something the project wants before I sit down and start writing it. It would likely require a few big-ish changes, like moving the markdown rendering to client-side instead of server-side, and sending emotes as plain-text instead of HTML (see #1803) and parsing/injecting them client-side. I'm assuming if somebody is plugging into an IRC or XMPP server, you'd want to send markdown so people connected via other clients can read/participate. I'm also presuming #1828 would require having the on-the-wire data be less HTML-y and more plain-text/markdown.

**Comment by gabek** [comment]
I appreciate the thought you've put into this and your offer to help with it.

But unfortunately it looks like not only would Owncast have to maintain and build features for the internal chat server (a full time task of its own), but also keep up to date with a growing number of 3rd party services to make sure our features are working with them. And while I know you offered to work on this, unfortunately I can't rely on a single person to maintain something indefinitely. The day you decide Owncast no longer fits your needs I have a substantial set of features, protocols, and 3rd party services that I personally have to support.

I know it always seems like I'm saying no to everyone's ideas, and it's not because they're bad. I think this is cool idea. I wish Owncast was large enough of a team to support huge initiatives like this and know an investment in this kind of thing could be supported into the future. But as it stands the internal chat service has to be the focus.

If there's one thing I've learned over time is relying on 3rd party services for core functionality of your software is a never ending battle. And I don't want Owncast to take on that battle without having a substantial army to fight it.

I'd love if Owncast could support some type of [plugin](https://github.com/owncast/owncast/issues/1736) ecosystem so people could build and support their own plugins for things that they want, but that's another luxury that's currently not at the top of any todo list.

**Comment by gabek** [comment]
And also, I know I've said it 10000000 times but:

> So the thinking goes, by default - use the current chat system with the fairly ephemeral nicknames, users in local storage, possibly support fediverse auth, and so on.

Users aren't in local storage.

**Comment by shodanx2** [comment]
Hello, 
I'm curious about this, I'm already using xmpp chat and will be using converse.js as web chat.

Does owncast have a way to make its chat interoperate with xmpp ? 

I've seen in the settings it has some fediverse connection, and there seems to be a activitypub to xmpp bridge. 
Has anyone tried this before ?

**Comment by gabek** [comment]
If you'd like to read more about how the Fediverse can interact with Owncast please take a look at the documentation. In short, it's not a chat replacement. https://owncast.online/docs/social/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/docs/social/">Social features</a></strong></div><div>Allow people to follow your server, know when you go live, share and interact with your stream.</div></blockquote>

**Comment by sjehuda** [comment]
I would want to interject and mention, that XMPP has all the features (and even more) that ActivityPub has to offer.

Essentially, and without disrespect, ActivityPub is a spin-off of XEP-0060 and XEP-0277 of XMPP.

It is important to mention that the publishing system of XMPP is offered in the form of Atom Syndication Format (RFC 4287), which means that it is possible to use rich text, title, summary, content, and even attachments (i.e. enclosures).

So, for Owncast, it might be of at most benefit to priorities or entirely shift to XMPP.

See projects Blasta, Libervia, Movim, and Rivista for realizations of publishing content over XMPP.

**Comment by shodanx2** [comment]
Thanks @sjehuda  
I did not know that about ActivityPub's history, that was most interesting !

**Comment by sjehuda** [comment]
On Wed, 20 Aug 2025 11:08:38 -0700
shodanx2 ***@***.***> wrote:

> shodanx2 left a comment (owncast/owncast#1829)
> 
> Thanks @sjehuda  
> I did not know that about ActivityPub's history, that was most
> interesting !
> 

@shodanx2 I guess you meant to XMPP, not ActivityPub.

This article has more information on this subject.

https://journal.woodpeckersnest.eu/posts/2024-11-05-xmpp-as-the-internet
