### ISSUE TITLE
Create automated upgrade test

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1876]
- Start at an older version
- Make some API calls to configure it
- Check out each release tag and build + run
- Once getting to the destination version make sure it builds + runs and the configuration that is expected to be there still is.

**Comment by 4censord** [comment]
I might take a shot at this.
Few questions:
* At what version to start?
  Or when has the config been stabilized?
* Should it test every single version since the start?
* Is just fetching the release artifact from back then okay?
  That would prevent build issues that might arise by building older versions with newer Go versions

**Comment by gabek** [comment]
Hey there! These are good questions! In theory we should be able to start from the very earliest release, but the downside is up to v0.0.6 a config file was used to configure an instance instead of an API. So I think it could be fair to say 0.0.6 could be the starting point.

That's a good idea to just use the binaries. And since this is the type of test that is important before a release, the most recent version wouldn't yet have a release available  Another option might be to use Docker images.
