### ISSUE TITLE
Improve chat history query performance

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1890]
An issue that has lingered, improved slightly, but still occurs as our queries have become more complex.

When the tables have many rows, the chat history query can get very slow at scale. It doesn't impact most streamers, but one person reported a problem with it.

Query: https://github.com/owncast/owncast/blob/develop/core/chat/persistence.go#L292

I'd love the help of anybody who can shed some light on optimizing SQL queries.

**Comment by gabek** [comment]
One major bottleneck seems to be the `scan` of history rows. I have no idea why it's so slow.

**Comment by jprjr** [comment]
I might be able to help - is the user able to share their sqlite file? Alternatively I could write a script to synthesize it - how many messages do they have (roughly)?

**Comment by jprjr** [comment]
Started taking a look at the schema - loaded it into a sqlite database, and tried various queries with `explain query plan`.

First thing I noticed is a syntax error when creating the messages db https://github.com/owncast/owncast/blob/2c47ddeef0ab1b21ef610d4de25787875e6dbeb5/core/data/messages.go#L26 - sqlite doesn't allow naming an index `index`. This doesn't affect this particular issue as far as I can tell, just wanted to point it out.

Question: is there a case where a user could be disabled, but the message non-hidden? You may be able to just remove that `disabled_at is not null` clause if any disabled user's messages will be hidden anyway.

It also looks like the messages table lists user_id as an integer, but the user's id is a text column, so there's a join occurring on mis-matched data types.

Using the current schema this is the results of explain:

```
QUERY PLAN
|--SEARCH users USING INDEX user_disabled_at_index (disabled_at=?)
|--SEARCH messages USING INDEX user_id (user_id=?)
`--USE TEMP B-TREE FOR ORDER BY
```

If I change message's user_id to a `TEXT` type the plan changes - it scans messages first and uses a compound index when joining with the user:

```
QUERY PLAN
|--SEARCH messages USING INDEX hidden_at (hidden_at=?)
|--SEARCH users USING INDEX user_id_disabled_index (id=? AND disabled_at=?)
`--USE TEMP B-TREE FOR ORDER BY
```

Finally, to get rid of the temp b-tree, you could create an index on `hidden_at` and `timestamp`:

```
create index idx_messages_hidden_at_timestamp on messages(hidden_at, timestamp);
```

This gives a much better-looking query plan (so for reference - I changed `user_id` to a `TEXT` type and created that hidden_at + timestamp index):

```
QUERY PLAN
|--SEARCH messages USING INDEX idx_messages_hidden_at_timestamp (hidden_at=?)
`--SEARCH users USING INDEX user_id_disabled_index (id=? AND disabled_at=?)
```
If I leave the user_id field as an `INTEGER` type, but add that new index, I get this query plan, which also looks pretty good:

```
QUERY PLAN
|--SEARCH messages USING INDEX hidden_at_timestamp (hidden_at=?)
`--SEARCH users USING INDEX user_disabled_at_index (disabled_at=?)
```

I still need to generate a test database and perform real-world timing. But I suspect creating the hidden_at + timestamp index will help dramatically since SQLite no longer needs to construct that temporary table to sort by timestamp.

Changing the message schema to have `user_id` be a `TEXT` type will help if the users table is large, I'm unsure how big of an impact that will be.

**Comment by gabek** [comment]
These are good finds.

For me, I used a WIP test to generate load against a local instance.  You can find that here: https://github.com/owncast/owncast/tree/gek/load-tests/test/load/new. Don't run the tests against the `gek/load-tests` branch, though, as there's a bunch of other experimental changes that aren't finished or are broken or not intended to actually be used.

Running the test a handful of times builds up a backlog of messages and users. Originally the query could take multiple seconds to complete, but with the small change above it now takes about half a second, but that still backs things up.

The test isn't complete but it's enough to build up some data.

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/test/load/new at gek/load-tests · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/test/load/new at gek/load-tests · owncast/owncast</div></blockquote>

**Comment by jprjr** [comment]
Another idea that may be worth trying, since the message timestamp is indexed:

If you added a clause like `messages.timestamp > datetime('now','localtime','-(x) hours')`, that *may* cut down processing time if you have a lot of messages that haven't been pruned yet? I'm unsure how often the pruner runs. But that would also be indexed.

For particularly busy instances, it may make since for the pruner, max backlog count, and max backlog timestamp to all be configurable (apologies if they are already, haven't checked). For busier servers, an admin could set all of those to more aggressive values to prune more messages more often.

**Comment by gabek** [comment]
Certainly not stale. Will get some of these improvements in after the 0.0.12 release.

**Comment by gabek** [comment]
@jprjr I just put together a PR with your fixes and suggestions above. While I wasn't able to see a significant performance improvement, it's at least way more _correct_.  And in poking around I've seen indexes that I thought were being created weren't, so I'll be able to go through and fix those, not because of specific performance issues, but they should exist.

> I'm unsure how often the pruner runs. But that would also be indexed.
Since then it was reduced to every 2hrs, and that feels like it's pretty aggressive. I'd hate to add more knobs and switches for configuring that, but if people run into a use case where a sane default can't be determined for all instances we can re-evaluate. Right now only the most recent 50 messages are returned anyway, and the rest of that 2hrs is just to allow the admin to have access to a larger backlog in the admin (for moderation mostly).

Who knows, maybe with the other index fixes there will be some other performance improvements that squeak in!  But it's probably starting to reach premature optimization territory since chat is rarely _that_ busy. But it could be.

If you get a chance to take a glance at the PR and see if anything else comes to mind, feel free!

PR: #2026
