### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by choupaland** [owncast/owncast#1903]
Hello there,

I would like to use owncast on windows.
have you plan to create a windows release ?

I search on issue and found that you do test on github actions.
But no windows release found.

Best regards.

**Comment by gabek** [comment]
It's very low on the list of priorities, just because most people don't use it. And those who do use Windows happily use the Linux subsystem.

I don't have a Windows test environment, but if somebody wanted to take the lead on a Windows release I'd happily let them test and make the changes required for it to happen.

**Comment by jamestockwell** [comment]
Hey, I ended up running it in docker on windows as a workaround and have had no issue running 4 docker images all pointed at different ports.

**Comment by choupaland** [comment]
on this repository, i don't find the way for create/push a new release.
where is the releaser "script" ?

**Comment by gabek** [comment]
Don't worry about the actual process of creating releases. The primary concern would be to make sure Owncast can natively run on Windows.
