### ISSUE TITLE
Feature request: "Hosting" another streamer

### ISSUE THREAD

**Issue by ChillyCider** [owncast/owncast#1917]
Kudos on the Owncast project. It is great! I was able to get a container up and running, and used it to stream some gameplay to my friends. Worked like a charm!

Ok, so I had an idea, not sure if this has been discussed already. I looked through the Issues page, and didn't see anything similar.

I was thinking about how to save on outgoing traffic. I saw the S3 integration, and I think that's great. But, I have hopes that eventually, we'll be able to lean on more community-run/federated solutions.

Twitch has a feature called "*hosting*." This is where you maintain a list of streamers you'd like to *host*, and then your stream **becomes a relay for a one of them** whenever you aren't streaming.

Maybe this could be a model for Owncast, to save on in-the-moment bandwidth? So like, maybe i can configure my stream to play a low-res version of somebody else's? And then, maybe, viewers get divided to each instance?

Idk how that would happen on the technical side. But if this worked, then a small circle of streamers could work together (i.e. cooperate) to maximize the benefit from this.

Anyway, just dropping this idea here to see if it's already been discussed. Like I said, I didn't see any existing discussion about it.

**Comment by gabek** [comment]
I'm glad you were able to get up and running and things are working for you!

We've discussed ["raids"](https://github.com/owncast/owncast/discussions/717), but it sounds like what you're talking about is pretty different than that.

I'm not sure what you're talking about could ever really help people in saving their local bandwidth. In fact it sounds like it would be the same, or even using additional bandwidth all around because a copy of the stream is being ingested elsewhere.

We can't really use Twitch as a comparison because in that use case all the bandwidth is the same, it's all Twitch. So in your example one streamer isn't becoming a relay for another, it's simply Twitch streaming Twitch. It's all the same from the broadcasting side because they're centralized.

While I think the "Raid" approach would work much better for many reasons, if we used your use case above as example where Owncast server A (offline) wanted to have Owncast server B (online)'s video playing:

- One option is to point Server B's video player at Server A. In that case Server B would use no bandwidth and Server A would use the same amount of bandwidth as if Server B wasn't "hosting" at all and the viewers were on the server directly.
- Or like you said, Server B could ingest a copy of server A's video and stream it on behalf of Server B. Now this means Server B **and** server A is streaming and using bandwidth.  So it's certainly a net negative in my opinion. 

But ultimately I think this is an academic exercise because I would never want the scenario where an Owncast server gets fewer eyeballs for chat and page content because the video is being copied to another server. I think if people are watching the video of a server they should be chatting on that server, and reading the content of that server's page, and clicking on the donate buttons of that server, and doing all of the things that come with engaging with that stream.

Sure, if people choose to watch with vlc, mpv, quicktime, TVs, etc they don't get all those things, but that's an end-user choice. I wouldn't want to make a built-in platform choice that enables a server to get less engagement.

**Comment by ChillyCider** [comment]
Thanks for the response1

> [...] I would never want the scenario where an Owncast server gets fewer eyeballs for chat and page content because the video is being copied to another server. I think if people are watching the video of a server they should be chatting on that server, and reading the content of that server's page, and clicking on the donate buttons of that server, and doing all of the things that come with engaging with that stream.

That's a great point! Something i had never considered.

To address that, maybe this idea makes more sense as e.g. a "Select a Mirror/Relay" dropdown on the video player. Where your selection just changes which server the video player connects to. The options would be curated by the Owncast instance owner and also authorized by the relays themselves.

If the <s>mirror</s> relay you're watching dies, then you'd be switched to different relay in the background.

> Or like you said, Server B could ingest a copy of server A's video and stream it on behalf of Server B. Now this means Server B **and** server A is streaming and using bandwidth.  So it's certainly a net negative in my opinion.

That's correct - as a group, the servers would experience a heavier load. But, assuming the audience is evenly split among the relays, each server would experience lesser load. This would be mainly for streamers with low Internet speed to help each other out 😋
