### ISSUE TITLE
Web UI v2: Chat message username highlighting

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1921]
This is existing Owncast functionality in UI v1:

If a person says your name in chat it should be highlighted in the message to catch your attention.

**Comment by t1enne** [comment]
Do we want to bring back mark.js from the old ui or should I write something?

**Comment by gabek** [comment]
Since we're using React now there might be other options out there, but mark.js worked fine and we can totally use that again, plus the code already exists to use it, so sounds good to me!

**Comment by bolshoytoster** [comment]
I know this issue has been closed for a while, but would it make sense to highlight when you say someone else's name in a message.

I suggest this because I've seen a few people (myself included) confused at how the highlighting works, and it would be nice to see when it has worked.

I'd be happy to open a PR for this if this is wanted.

**Comment by gabek** [comment]
Please open a new issue for highlighting other people's display names. We can discuss that.

**Comment by bolshoytoster** [comment]
I've opened an issue (#5137)
