### ISSUE TITLE
UI Testing

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#1926]
With Web UI v1 we used puppeteer to perform some automated testing of the web page as a whole. Since we're starting fresh we can either use puppeteer again or look at other tools that fit our needs.

Some testing options:

- Storbyook-based testing https://storybook.js.org/blog/storybook-6-5/
- Cypress

**Comment by jamescallumyoung** [comment]
Hi @gabek I'd like to take a look at this. Testing is a good way to get familiar with the FE codebase.

I'd suggest we use https://chromatic.com. It's a web-based visual diffing tool built by some of the Storybook folks. They have a generous free tier and a FOSS tier. I'll ping them about the project's elegibility under their FOSS tier.

I think web-based is the way to go since it'll require less setup and it'll run automatically with GH Actions so new contributors don't miss things accidentally.

<blockquote><img src="https://www.chromatic.com/open-graph/og-home.jpg" width="48" align="right"><div><strong><a href="https://www.chromatic.com/">Automatically review, test, and document Storybook</a></strong></div><div>We make tools for frontend developers that automate the Storybook workflow. Chromatic helps you gather UI feedback, test across browsers, and generate usage docs, all in one shared cloud workspace.</div></blockquote>

PS: Pls assign me 😉

**Comment by gabek** [comment]
Oh! I actually have the project setup on Chromatic, but it's not actively being used for anything. Admittedly I didn't really look into how testing actually worked or how you write tests for Chromatic. 

https://www.chromatic.com/library?appId=629132c6e23893003a9e89c5

I just added you as a collaborator. It says

> This project currently syncs collaborators from owncast/owncast. Collaborators must login to Chromatic to begin syncing and appear in the list.

So hopefully you can now login to Chromatic for `owncast/owncast`. Let me know if it's not working.

Thanks so much for wanting to look into this, it's really good to have somebody who's used Chromatic for this kind of thing before to get us in the right direction.

**Comment by jamescallumyoung** [comment]
I checked in with the Chromatic team and they said owncast isn't eligible for their FOSS tier as it's only open for FOSS design systems.

I'll check the existing Chromatic setup.

**Comment by jamescallumyoung** [comment]
I created a small refactor @gabek. I moved the storybook story files for each component so they're co-located with their components. I added some rationale in the PR. 

It's a draft right now since I can't test it too well. I'll take a look at starting up a backend instance to connect the frontend to, test it out, then un-draft the PR.

**Comment by gabek** [comment]
That sounds like a great change, it makes a lot of sense. Certainly simplifies things like you mentioned. Let me know if you have any issues spinning up the backend.

**Comment by gabek** [comment]
I'm going to start work on some Cypress tests.

**Comment by gabek** [comment]
I started work on this, but due to churn in design I must stop because I cannot work on UI tests if the UI is going to be changing.
