### ISSUE TITLE
Implement multiplatform Docker image

### ISSUE THREAD

**Issue by hufman** [owncast/owncast#1953]
This project is incredible, thank you so much for building it!
I'd like to add support for building an arm64 Docker image. The Go toolchain makes [cross-compilation](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/) very easy, and your Dockerfile is already set up with multi-stage builds which should keep the build fast.

I'd like your review on my approach before I start:

- I'd like to move the Tailwind CSS compilation out of [docker-nightly.sh](https://github.com/owncast/owncast/blob/34629d0f5da8fd6e82750a49cd7b608a644c320d/build/release/docker-nightly.sh#L8-L15) and [release.sh](https://github.com/owncast/owncast/blob/34629d0f5da8fd6e82750a49cd7b608a644c320d/build/release/build.sh#L43-L50) into another stage within the Dockerfile.
- I'd like to switch the [Docker Nightly Action](https://github.com/owncast/owncast/blob/develop/.github/workflows/docker-nightly.yaml) (and maybe the release action, but I was unable find it) to use the [Docker Buildx build and push actions](https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md).

Admittedly I only started using this project yesterday, so please let me know if there are any other things I should consider or any other thoughts you have!

**Comment by gabek** [comment]
Thanks for the kind words! And thanks for checking in, A multiplatform image would be great.

While the Go toolchain is good with cross-compilation, unfortunately we're using cgo, and that adds a bunch of complexity in building. That's why in `release.sh` you can see it's building with `xgo` instead of `go` so we can get multi-platform binaries.

Because our Dockerfile is assuming only 64bit Linux we don't need to use xgo. But with a multiplatform build we would.

[I've been trying to migrate away from xgo](https://github.com/owncast/owncast/issues/1756) for some time, with hopes of moving to Earthly. I _think_ I got pretty far with that, but it hasn't been a priority: https://github.com/owncast/owncast/blob/gek/earthly-builds/Earthfile

As for Tailwind, this next release (0.0.12) will be the last release that requires the Tailwind CSS compilation, so maybe it's not worth making changes to that.

Sorry for adding complexity to what would generally be a pretty straightforward thing, but I'm open to any ideas you have!

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/Earthfile at gek/earthly-builds · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/Earthfile at gek/earthly-builds · owncast/owncast</div></blockquote>

**Comment by hufman** [comment]
Oh wow, Earthfile looks nifty! It looks like it would just need some extra Docker image build targets with [SAVE IMAGE](https://docs.earthly.dev/docs/guides/multi-platform#saving-multi-platform-images) commands.
I'm glad you've already considered it, I'll leave this here as a feature request then :)

**Comment by gabek** [comment]
Yeah! There's a path forward for sure. This is probably something that will have to be worked out: https://docs.earthly.dev/docs/guides/multi-platform#emulation-and-with-docker

And while that Earthfile has stuff in it, it hasn't actually been tested on the different architectures that in theory it's building binaries for. So it's very much a work in progress.

Since you're knowledgeable about this stuff, if you're at all interested in getting multiplatform images to work with Earthly, I'd love your help! I'd love to get rid of these release shell scripts and requiring xgo.

<blockquote><img src="https://app.gitbook.com/share/space/thumbnail/-M3I14IYwbiMH3cL5KCq/page/-MR14XMPkvEuiZsznKDi.png?color=%232AAFCB&logo=https%3A%2F%2F1330441096-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-legacy-files%2Fo%2Fspaces%252F-M3I14IYwbiMH3cL5KCq%252Favatar-rectangle-1596854602616.png%3Fgeneration%3D1596854603001615%26alt%3Dmedia&theme=light" width="48" align="right"><div><strong><a href="https://docs.earthly.dev/docs/guides/multi-platform#emulation-and-with-docker">Multi-platform builds</a></strong></div></blockquote>

**Comment by hufman** [comment]
Successful nerdsnipe, good sir! 4 hours later and here's [my Earthfile](https://github.com/hufman/owncast/commits/hufman/earthly-builds) for you :) It cross-compiles all the destination binaries from an amd64 host, without needing emulation, and I verified the resulting amd64 and arm64 Linux binaries worked natively on my test machines.
I'm not quite sure on how the steps should be composed most elegantly, having only learned Earthfile tonight, so there could be improvements there.

It should be easy for me to extend it with Docker steps next!

**Comment by gabek** [comment]
No emulation, that's awesome! I bet it's a ton faster.  Thank you for checking this out, I really look forward to the end result!

**Comment by hufman** [comment]
Updated [my Earthfile](https://github.com/hufman/owncast/blob/hufman/earthly-builds/Earthfile) with a new approach (using a --platform arg instead of separate named targets), and then added Docker image support, including [successfully pushing the image](https://hub.docker.com/r/hufman/owncast/tags) with a single command: `earthly --push +docker-all --tag hufman/owncast`!
Whatcha think? Try it out, pretty much everything should work fine without emulation, and [qemu](https://docs.earthly.dev/docs/guides/multi-platform#linux) is only needed to build the Docker crossplatform images.

**Comment by gabek** [comment]
It worked fantastically! This is awesome! I'm going to do some testing on different platforms and make sure these actually run, but this is super cool. And then in theory I could set this up to run the nightly build from Earthly in the Github Actions CI job as the next step.

**Comment by gabek** [comment]
On top of the Linux 64bit build, I just tested the macOS build on my Intel Mac and the Arm7 build on a Raspberry Pi 4 running a 32bit OS and everything runs as expected.  Would you mind putting up a PR with your updates? I could just copy your file over, but it'd be good to keep your commits and make sure you get contributor credit!

**Comment by hufman** [comment]
Published a PR, as requested!

**Comment by gabek** [comment]
I made a couple tweaks so it would build from the local files, and be able to have a version that's different than the tag: https://github.com/owncast/owncast/commit/d214f2390e094e06ff70defe49fd66d0e88020f4

I setup a new parallel nightly build job that will create a separate nightly image for testing, and if that works as expected then the previous one can get removed. 

https://github.com/orgs/owncast/packages/container/package/owncast-earthly 

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 83 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Comment by gabek** [comment]
Success! It builds and pushes the Docker image: https://github.com/orgs/owncast/packages/container/owncast-earthly/versions

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 83 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div></blockquote>

**Comment by hufman** [comment]
I peeked at the nightly build job, and it looks like the start of the [Checkout and Build step](https://github.com/owncast/owncast/blob/a137d7ebb9224f5b0e5728654985b73eec0d72b5/.github/workflows/docker-nightly-earthly.yaml#L40-L46) is raising an error, because the `git checkout -b` option is meant to create a new branch with the given name. However, the GITHUB_HEAD_REF should already be pointing to an existing branch, I think.
If it is a typo that meant to check out the GITHUB_HEAD_REF as the current branch, I think the previous `actions/checkout` step should take care of that already.
There's also an [action](https://github.com/marketplace/actions/setup-earthly) available to set up Earthly instead of curling the installer, which feels a little more elegant to me.

I switched my deployment to use the Github Releases docker image and it works great!

**Comment by gabek** [comment]
Ah yeah I see that. That step is from the [documentation](https://docs.earthly.dev/ci-integration/vendor-specific-guides/gh-actions-integration). I think the use case they're trying to fix for is not having a branch when running this on a specific commit/tag/ref, instead of a specific branch. I'm just going to remove that branching since it's not applicable.

**Comment by hufman** [comment]
Oh curious, I didn't know the checkout action would omit the branch in the local clone! The builds on my project using androidgitversion have reliably picked up the branch name with that same action 🤷.

**Comment by gabek** [comment]
Oh yeah I think it's no problem if it's a branch you're checking out, but I think they are concerned about other refs such as commits, tags, etc so they create a temporary branch to work around it. I also switched to the action, and that works great!
