### ISSUE TITLE
Not listening on ipv4

### ISSUE THREAD

**Issue by timowevel1** [owncast/owncast#1987]
Hey,

my instance isnt listening on ipv4, I am using a fresh installed AWS EC2 instance. Means I cannot reach it via http or the rtmp port, as it also listens on ipv6.

tcp6       0      0 :::8080                 :::*                    LISTEN      4030/./owncast/ownc

You know how to fix it?

Thanks

**Comment by gabek** [comment]
Owncast listens on 8080 on all interfaces by default, so I can't say offhand why it's not able to bind to 8080 unless something else is using it or there's no interface with an ipv4 address for it to bind to.

**Comment by jprjr** [comment]
Owncast by default listens to "0.0.0.0" - on most runtimes, this string represents "all IPv4 addresses", but Go listens on all IPv6 addresses as well, see https://github.com/golang/go/issues/17615

By default on Linux, listening to `::` (the IPv6 equivalent of "0.0.0.0") also includes all IPv4 addresses unless you set the option `IPV6_V6ONLY` when binding the socket, or if you've set the global v6only sysctl.

So by default on most Linux distros - even though `netstat` and/or `ss` show it only listening on IPv6, you actually can connect via IPv4.

What does `curl -I http://127.0.0.1:8080` do? If that's successful (you'll see "HTTP/1.1 200 OK" and then some headers), then the issue is elsewhere, like a firewall/iptables rule.

If `curl -I http://127.0.0.1:8080` shows a connection refused type message, then you could check if dual-binding is enabled:

```
cat /proc/sys/net/ipv6/bindv6only
```

If that returns "1", then dual-binding is disabled. Assuming you're OK with having dual-binding enabled set it back to the default of 0 - edit `/etc/sysctl.conf` and add the line:

```
net.ipv6.bindv6only=0
```

Then run `sysctl -p`

**Comment by jprjr** [comment]
An alternative would be for Owncast to change up how it registers the HTTP server, by creating a TCP listener separately. and using `http.Serve()` instead of `http.ListenAndServe()`. When you create a listener, you can specify the `net` to be `tcp` (the default that `http.ListenAndServe()` is using), or `tcp4` to specify you only want to bind on IPv4-only, or `tcp6` for IPv6-only.

Going this route, Owncast would probably need a flag/option to specify whether you want to use a `tcp`, `tcp4`, or `tcp6` listener, with the default being `tcp` to maintain backwards compatibility.

**Comment by timowevel1** [comment]
> Owncast by default listens to "0.0.0.0" - on most runtimes, this string represents "all IPv4 addresses", but Go listens on all IPv6 addresses as well, see [golang/go#17615](https://github.com/golang/go/issues/17615)
> 
> By default on Linux, listening to `::` (the IPv6 equivalent of "0.0.0.0") also includes all IPv4 addresses unless you set the option `IPV6_V6ONLY` when binding the socket, or if you've set the global v6only sysctl.
> 
> So by default on most Linux distros - even though `netstat` and/or `ss` show it only listening on IPv6, you actually can connect via IPv4.
> 
> What does `curl -I http://127.0.0.1:8080` do? If that's successful (you'll see "HTTP/1.1 200 OK" and then some headers), then the issue is elsewhere, like a firewall/iptables rule.
> 
> If `curl -I http://127.0.0.1:8080` shows a connection refused type message, then you could check if dual-binding is enabled:
> 
> ```
> cat /proc/sys/net/ipv6/bindv6only
> ```
> 
> If that returns "1", then dual-binding is disabled. Assuming you're OK with having dual-binding enabled set it back to the default of 0 - edit `/etc/sysctl.conf` and add the line:
> 
> ```
> net.ipv6.bindv6only=0
> ```
> 
> Then run `sysctl -p`

Thanks for your help, that worked.
