### ISSUE TITLE
Surface what auth methods a chat user uses

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2065]
### Share your bug report, feature request, or comment.

I originally wanted to visibly display, and link to, the profile/url that a chat user authenticated themselves with. But I decided against it since it was making a choice for the user to share that profile/url with the public just because they wanted to authenticate with chat. I didn't feel like this was was a necessary tradeoff and ultimately kept that piece of data private and internal to Owncast.

I was chatting with the people on the Hejo stream today and they strongly feel that not showing this information makes auth completely useless.

For clarification I believe what they want chat authentication to be and what it is now is _slightly_ different.

### 1) Chat identity. Not personal identity.

Currently Owncast chat auth doesn't verify the legitimacy or true personal identity of a person. The current goal is to only say that they are the same person that they were before. That the "gabe" who just joined the chat is for sure the same "gabe" who was there a week ago. It does _not_ however, make a claim that the "gabe" who joined chat is the same "gabe" you know from High School, the Fediverse, or the party you were at. This in theory would be the Twitter-style "verified"-style approach. You know that Elon Musk is Elon Musk because somebody vouched for them.

### 2) Sharing a chat identity between devices.

It allows you to restore your chat identity that you created on device or browser with another. This is "account restoration", and again making no claims to who you are outside of the chat.

### 3) Name is not the identity

Owncast calls the chat name a "display name" for a reason, it is not your identity. It's just a display attribute. People can change their names, make confusing names, make names that look like or sound like other people, etc. There's an unlimited number of ways people can make names that make life difficult. Any attribute that people can easily change shouldn't be trusted as a solid way to identity a person.

## Pros to showing detailed auth information
- Be able to say "this gabe _is_ the same gabe you know from the Fediverse because he authenticated using Fediverse auth and here is his profile.
- An additional datapoint when knowing that this gabe is the same gabe you saw last week because you remember that the gabe last week also linked to a specific profile or URL.
- Enable clicking through to chat users' external web sites and profiles.

## Cons
- It still cannot verify outside if a Fediverse profile or IndieAuth-enabled web site that the person who they say they are is actually that person. That's far beyond the scope of a technical solution with Owncast.
- It will publicly show, and link to, the method the user authenticated with. This would either be a Fediverse profile or an IndieAuth-enabled web site. A chat user may not want this aspect of their identity to be shared with the public.
- Not all profiles/urls directly link with a person, so you have to remember "gabe linked to cool.biz last time and this person who says they're gabe linked to cool.net so the person is different".
- People may have multiple auth options attached to their chat account. For example a Fediverse account and an IndieAuth page, or multiple Fediverse accounts. Showing them all would become a UI mess.

## Things that are out of scope

- I'm not interested in adding a bunch of admin settings for people to understand to micromanage what gets shown where and how. This is either a thing Owncast does or it doesn't.
- I'm also not interested in each chat user micromanaging their own settings about what things they show and what they don't. Besides, if you were a bad guy trying to cause a problem you'd just hide your auth so people would not be able to verify it's not accurate anyway.
- This has nothing to do with adding username/password auth and I'm still not interested in having that.

 
## Feedback

This would require feedback from the greater Owncast community before any decisions can be made as I'm not going to be making decisions on behalf of every chat user to share their social links with strangers unless this is actually what is felt is best.

I'd also love for people's help in working on making things better. This project is often just me, and if you are passionate about Owncast and care deeply about wanting something to work a certain way I'd love you to become more involved in the project. Otherwise it's just me alone in a room coming up with ideas, and my ideas don't always align with your requirements, especially if you don't tell me.

**Comment by unclearParadigm** [comment]
may I chime in here for a second and add some mustard to the discussion.

In my humble opinion we won't be able to satisfy everyone...

Why? Because actually we have different use-cases for Authentication on Owncast:
1. use-case of anonymity/privacy for authenticated users
2. use-case of proofing the identity of an authenticated user (for others to verify the authenticity of a authenticated user)
3. use-case of reserving usernames usernicks/names (+ preventing similar looking/different char usernames)

All of these are inherently different use-cases and sometimes even conflict with each other.

## Let's have a closer look on `1` and `2`, shall we?

### Story

A user called `Alice` authenticates against Owncast using Mastodon. Then we have `Bob`, `Bob` is the best friend of `Alice` and joins the same Owncast stream. But `Bob` currently has no way of identifying whether `Alice` in the Owncast Chat is the real `Alice`. What a pity. Luckily `Bob` is following `Alice` already on Mastodon, and therefore knows, that when `Alice` authenticated herself against Mastodon, it must be the real `Alice`. Owncast would implement the feature to show the source of authentication (e.g. a Mastodon instance + profile Link) and everyone would be happy... Or not? The problem is, that `Alice` is very cautious when it comes to her privacy online. So she does NOT want to share her Mastodon-Profile with other viewers of Owncast (she'd trust `Bob`, but not the other thousand viewers in the chatroom, that now would be able to stalk her on her Fediverse profile). So `Alice` decides not to authenticate against Owncast, as she does not want her identity to be disclosed. `Bob` must find a out-of-band way to verify whether `Alice` in the chat is the `Alice` he knows.

### Lessons

When delegating Authentication to a Third-Party (e.g. FediverseAuth, IndieAuth), we don't solve the problem.
We just shift it to a third-party. What if `Bob` does not know `Alice` Fediverse account? What if `Alice` created  a second Fediverse Account so she is able to authenticate to the Owncast chat without disclosing her real Fediverse profile? The problem does not get any better from here on. We just shift the problem to another application.

## Let's tackle `3` and `2`

### Story

`gabe` is famous around Owncast. He is known to stumble to various Streams now and then. `Eve` knows this, and wants to impersonate `gabe`, to tell people to use Twitch instead of Owncast. So she writes a script, that crawls the Owncast Directory, and everytime a new Owncast-Instance becomes available, she visits the site and immediately registers the nick `gabe`. Now the displayName `gabe` actually belongs to `Eve` who is an `gabe`-imposter. 

### Lesson

Reserving nicks will always boil down to a "first-come, first-serve" situation. This problem won't be solvable, except we have another possibility to verify that `gabe` is `gabe` and not `eve` - which again brings us to the `1` vs. `2` story above. 

---

## Final Words

I think, we won't find a proper solution that makes EVERYONE happy without majorly re-thinking user-management in Owncast, or without major investement in development (e.g. to allow multiple delegated authentication sources, opt-in of visibility for authentication-source). I personally love, that Owncast is simple and it "just works(TM)". I love that I don't need to take care about User-Management, and GDPR topics, because I don't store E-Mail Addresses and other sensitive user-information in the Owncast-SqliteDb. I love that I don't have to force my visitors to make an Account (neither on Owncast, nor on the Fediverse) to participate in the chat. It's just simple! And personally, I'd be more than happy to keep it simple - even if that means, I need to do a manual "Challenge-Response" to `gabe` (e.g. on Fedierse) everytime he joins the stream, just to prove for myself its the real `gabe`.

But if we (talking about the broader Owncast-community) really want to solve the authentication problem once and for all, then I think there's no other way, than jumping onto "Registering Users" to Owncast. Be it centrally with a shared "Owcast-Id" (please don't. ...), or each Owncast-Instance taking authentication and user-management into its own hands. This of course would come with another range of problems to solve/implement (Self-Service, Password-Change, Password-Reset, "First-Come-First-Serve"-Problematic, User-Administration-UI).

If there is a concrete, shared plan and concept on what to do. I'd be happy to help out on the backend-side of things!

Cheers,
Ruffy

**Comment by H3J0** [comment]
There is no perfect solution, but that is not my problem. My problem is that the current solution leaves too much room for abuse or misunderstandings.
On (almost) all social media platforms, a check mark signals some kind of verification or authentication. If a random person visits a stream and there is a `Hejo` with a check mark, they could easily assume that it is the >real `Hejo`. This person could visit another stream and hey, there is another `Hejo` with a check mark. This could EASILY imply that this is the same dude. WE know that this must not be the case, `User N` does not, and we have - at least in my opinion - to care about this viewpoint even more than ours. 

At the moment, the only advantage of this auth-function is, that you can transfer your ID to another device (which is practically only important for moderators, if at all). What else do we authenticate otherwise? That we have a web server or a fediverse account. That is it.

At this point I'd prefer NO auth feature, over the current solution. I'd rather trust no one on this channel (Owncast chat) than give a false sense of security with this auth method. And it would be great if I could disable this feature, and not be forced to hide it with CSS.

I won't address the other points. Feels like a waste of time when potential solutions are out of the scope anyway.

**Comment by gabek** [comment]
I apologize, I was under the impression that you very much wanted to display the source of auth, but it sounds like from the feedback above nobody actually wants that. I'll be closing this discussion as I misinterpreted the request.

In the future I won't be interpreting people's requests and try to open issues on their behalf because I can get their requests wrong. I'll let people speak in their own words.
