### ISSUE TITLE
Pass playlist URL in STREAM_STARTED webhook

### ISSUE THREAD

**Issue by kontrollanten** [owncast/owncast#2075]
### Share your bug report, feature request, or comment.

To be able to import a Owncast stream into another platform (PeerTube, for instance) it would be great if the playlist URL is included in the payload of the STREAM_STARTED webhook.

**Comment by gabek** [comment]
The path will always be `/hls/stream.m3u8` of the server. Does that suffice, or do you need the full hostname?  If you need the full hostname I'll have to add validation in the webhook config section because people may not have set the hostname of their server... so it's just more stuff that would need to get added there.

**Comment by kontrollanten** [comment]
Thanks, that should be enough. I'll reopen this if I'd need the hostname in the future.
