### ISSUE TITLE
setInterval handler took too long in ClientConfigStore.tsx

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2111]
### Share your bug report, feature request, or comment.

![image](https://user-images.githubusercontent.com/414923/190074911-8e510e16-067c-460a-a235-26773e434640.png)

**Comment by heller** [comment]
What is needed to reproduce this? After setting up a clean environment on the `webv2` branch and streaming a loop of `./test/test.mp4`, this warning doesn't appear for me in the latest FireFox or Safari on macOS.

(I even tried `renice 20 <pid>` on the go server because I suspected it was the `/api/status` call being slow.)

**Comment by gabek** [comment]
Hey Matt!

You're right, it looks to have just... gone away. Thanks for looking and pointing out that it magically fixed itself(?).

Hope things are going well!
