### ISSUE TITLE
Fix Storybook deprecation warnings

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2177]
### Share your bug report, feature request, or comment.

When storybook runs `npm run storybook` it throws some deprecation warnings.

```
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: '' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
DeprecationWarning: 'createBinaryExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createExpressionStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
```

**Comment by Pranav2612000** [comment]
I found this - https://pullanswer.com/questions/deprecation-warnings-after-upgrade-to-ts-4-8 which says that the errors are due to the react-docgen-typescript-plugin. A PR has been made for this fix ( https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/70 ) 
As this is not a critical issue in my opinion, the only thing we can do is wait for storybook to update once this PR has been merged.

<blockquote><img src="https://pullanswer.com/assets/images/logo.jpeg" width="48" align="right"><div>PullAnswer</div><div><strong><a href="https://pullanswer.com/questions/deprecation-warnings-after-upgrade-to-ts-4-8">Deprecation warnings after upgrade to TS 4.8 - PullAnswer</a></strong></div><div>Deprecation warnings after upgrade to TS 4.8</div></blockquote>

**Comment by gabek** [comment]
Closing since we are not able to fix this ourselves.
