### ISSUE TITLE
Change default custom page content text

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2178]
### Share your bug report, feature request, or comment.

The current default text is
> This is your page's content that can be edited in the admin.

I've noticed a lot of instances do not change this text and it looks pretty stupid. Instead we can use this as an opportunity to have the default text explain that this is an Owncast instance, and talk a bit about what Owncast is. At least then the space will be used for something worthwhile.

And since it's all in markdown we can add links, images, etc to help tell the Owncast story.

**Comment by gabek** [comment]
I took a first pass at it but I'd love some discussion and feedback.

**Comment by SleepyLili** [comment]
I'd probably mention that this is the default description somewhere in the text. Maybe something like "The streamer has not set a description for this owncast instance", or "This is the default description that can be changed in the admin panel."? To make it clear that you're not reading something the streamer/server host wrote, but a default blurb.

"Why you might be interested in Owncast" sounds quite long to me, maybe something like "Owncast features" would work better.

I'd also add custom emotes support to the feature list, since that's a feature I really like (and it's a popular one on sites like Twitch)

**Comment by gabek** [comment]
I'm having a hard time coming up with some brief text that:

1. Tells the person what this server is.
2. Why it's different without being technical or nerdy.
3. But without trying to sell them on it.

I'm not trying to convince a viewer who drops by to install Owncast, but simply trying to spread the word that Owncast exists. If they want to go deeper on Owncast after that, that's up to them.

**Comment by gabek** [comment]
I don't think I did a very good job coming up with page content, but if I come up with something better I'll change it.
