### ISSUE TITLE
Broken images for federated actions list in admin

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2182]
### Share your bug report, feature request, or comment.

With webv2 the icons in the federated actions list in the admin `/admin/federation/actions` are broken.

![image](https://user-images.githubusercontent.com/414923/194772196-40f8a1ed-2623-4c17-a3d5-5e4bf584c42c.png)

**Comment by pippo** [comment]
I can take a look at this ✋ Please, assign.

**Comment by gabek** [comment]
Awesome, thank you!

**Comment by pippo** [comment]
Thanks. Quick question.
The issue appears to be caused by the fact that next.js is looking for static in the `web/public` folder, and there's no file called e.g. `img/like.svg`. I can see files for those 3 broken images (`like.svg`, `follow.svg`, `repost.svg`) present in the `webroot/img` folder, but not in `web/public/img`. Copying those to `web/public/img` resolves the problem, but I'm not sure if there's a deeper underlying problem, so a different solution might be required.
Is `webroot` a legacy web version thing? If so, is it fine to copy those 3 files over to `web/public/img`?

**Comment by gabek** [comment]
Yup, `webroot` is legacy.  It's the v1 of the web interface, so copying those files sound like the solution. Thank you!
