### ISSUE TITLE
Update project required Go version to 1.20

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2185]
### Share your bug report, feature request, or comment.

After Hacktoberfest is complete, and with enough warning to everyone, I'd like to update our Go version requirement to 1.19.

#2180 is a forcing function, as it uses types that were introduced in the recent version.

**Comment by jackgris** [comment]
Hi! 
When changed in `go.mod` the go version to 1.20 and running `golangci-lint` the only warning I get is with the use of rand.Seed, for fix that I use:
```go
//nolint:gosec
rand.New(rand.NewSource(time.Now().UnixMicro()))
```
But as you see, I need to use the directive `nolint:gosec` because the use of math/rand provokes a warning:
"Use of weak random number generator (math/rand instead of crypto/rand) "
That occurs in the function `ShuffleStringSlice` in utils package.
If you want I can send a pull request with that.

**Comment by gabek** [comment]
Hi there! Feel free to submit a PR, but I don't plan on making any Go 1.20 related changes until after v0.1.0 is released, so the PR will be unmerged until then.

**Comment by jackgris** [comment]
OK, nice to know, so I think is better wait to until that moment. Maybe you can think of a different version of Go to update at that moment. I will try to pay attention to that.
