### ISSUE TITLE
[feature request] Documentation missing minimum and recommended owncast server requirements

### ISSUE THREAD

**Issue by jahway603** [owncast/owncast#2233]
### Share your bug report, feature request, or comment.

Currently, the documentation is missing minimum and recommended owncast server requirements. I'm logging this issue as I will be testing owncast on a VPS with 1 CPU and 1.5 GB RAM, so I'll report back if it worked or not.

**Comment by gabek** [comment]
There's no documentation around this pretty much on purpose. Each person will have vastly different requirements depending on what their needs are.

RAM is generally not an issue. CPU is highly dependent on what your requirements are. The more "work" that is required (converting what you send it to what is being sent out) the more CPU is required to do that work. So if you have one output variant configured that is similar to the bitrate that you're already sending it, that's not a lot of work. As you add more (likely lower) bitrates so people with slower connections can view your stream, you'll need more cores available to perform additional transcoding work. Network usage is simpler to talk about. It's your bitrate x your concurrent viewers accessing that specific bitrate.

Each output variant configuration also has additional settings such as the amount of CPU you want to use (more CPU the better the output quality), so that's also a knob that's involved in the final usage.
And lower the FPS, the less work that is required as well, so that's also a part of the calculation.

Many people opt to use "passthrough mode" that literally takes what you send Owncast and makes it available as the output to your viewers. That's generally not recommended for a number of reasons, but it is an option to keep your CPU usage very low if necessary. But I find it to be trading one issue for others.

This all changes, however, if you have the ability to do hardware encoding. Then the CPU requirements will become minimal. But if you're using a hosting provider you likely won't have that option. But people who self-host from home might.

Not to mention every hosting provider is different, and the performance and amount of CPU they give you for a "vcpu" varies a lot. So all of this, and more, is why it's really hard to give a solid answer on what the requirements are.

As far your specific configuration of 1 vcpu, like with any other setup, some configurations it'll work great with, others it won't work at all depending on what you're trying to do.

**Comment by gabek** [comment]
I've had dreams of building a little wizard on the web site where you put in your specific configuration and it estimates what type hardware and bandwidth requirements you might need. Maybe some day I can get to that.

But the downside of that is streamers often don't know what configuration they plan on running with until later.

**Comment by gabek** [comment]
I'm going to go ahead and close this. If anybody has any ideas on how to better document "it depends on your requirements", I'd appreciate the help in doing better to answer this question for people.
