### ISSUE TITLE
Error: people can't follow

### ISSUE THREAD

**Issue by kaffeeringe** [owncast/owncast#2287]
### Share your bug report, feature request, or comment.

I enabled the social feature and I didn't set it private:
![Screenshot 2022-10-31 at 17-16-04 Owncast Admin](https://user-images.githubusercontent.com/367592/199062026-659b8093-7e32-4cbe-b5cd-dd97093638ed.png)

But when people try to follow, they can't - it's only a following request. When I look into the logs, there seems to be something wrong:
![Screenshot 2022-10-31 at 17-18-20 Owncast Admin](https://user-images.githubusercontent.com/367592/199062183-44ff3ff6-f3c3-43c9-8c50-a056bae350a6.png)

The error is being thrown here around line 180: https://github.com/owncast/owncast/blob/2d44f8603577bf1eb125447b3894462fa1310960/activitypub/resolvers/resolve.go

System is 20.04.5 LTS. up-to-date.

**Comment by gabek** [comment]
Ignore the "actor may not be valid" errors, those are different. That generally means a request came in to delete a reference to a remote federated user, and we looked up that user, and they weren't there (because they were deleted). It's a bad error and in the next release you won't see it.

The real error that needs to be tracked down here are the rsa/crypto errors.

![image](https://user-images.githubusercontent.com/414923/199065728-1f44cbb5-a31c-4356-b69c-33480bec8db2.png)

**Comment by gabek** [comment]
I haven't heard of any other occurrences of this by people, have you learned anything new or discovered any new specifics since you first started experiencing it?
