### ISSUE TITLE
Mobile: Send message button has disappeared

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2293]
### Share your bug report, feature request, or comment.

* Send button should show for mobile.
* Send button should hide for desktop as it's not needed, people have a keyboard.

Component: https://owncast.online/components/?path=%2Fstory%2Fowncast-chat-input-text-field--example

https://user-images.githubusercontent.com/414923/198814325-9f86a46f-7228-402c-8b82-ada5d142641b.MOV

**Comment by jprjr** [comment]
Regarding "Send button should hide for desktop as it's not needed, people have a keyboard."

If I use the emoji picker, and I'm just planning on sending emotes - after choosing my emote(s) I have to click somewhere in the chat box and hit enter.

So, assuming it may be easier to always have the send button visible (since there's no logic for hiding/showing) - I, for one, would love a send button on Desktop.

**Comment by heller** [comment]
Looks like the CSS to show it is reversed. I can just make it show everywhere, unless there are objections?

https://github.com/owncast/owncast/blob/6ce52e184c07d6ea50506db4ccc7aca82d1f5b87/web/components/chat/ChatTextField/ChatTextField.module.scss#L58-L69

**Comment by gabek** [comment]
No objections here!
