### ISSUE TITLE
Chat input field is not displayed in Chrome and Safari browser on my Phone

### ISSUE THREAD

**Issue by pscriptos** [owncast/owncast#2362]
Hello,

I would like to report a bug.
In the Chrome browser on the Android phone and also on the iPhone, the chat input field is not displayed. The Safari browser on the iPhone is also affected.

I was able to reproduce this behaviour with the latest Chrome app on the Android (v107.0.5304.105) and on the iPhone (v107.0.5304.101).
However, when I use the phone in landscape mode, I can also use the chat input field.
I use the Safari browser on the iPhone in the iOS 15.5 version.

I have no problems with Firefox on my phone. The input field is displayed here.

I use Owncast in the following version:
Owncast v0.0.12-linux-64bit (2d44f8603577bf1eb125447b3894462fa1310960)

Thank you very much.

**Comment by gabek** [comment]
Hi there, thanks for the report!

Currently the Owncast frontend web interface is getting completely rebuilt from the ground up, so I hope you don't mind if I close this issue, since future releases won't have this specific bug due to the rewrite.

If you're curious, feel free to follow along! https://github.com/orgs/owncast/projects/1


<blockquote><img src="https://github.com/opengraph.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/owncast/projects/1">Owncast Web Redesign/Rebuild • owncast</a></strong></div><div>Owncast Web Redesign/Rebuild</div></blockquote>
