### ISSUE TITLE
Option to mute embed by default

### ISSUE THREAD

**Issue by KyleMaas** [owncast/owncast#2420]
### Share your bug report, feature request, or comment.

It would be great if there was a way to feed a mute parameter to an embeded player so the player could run muted by default until the user unmutes it.

Maybe I'm missing something and this feature already exists, but I don't see anything in the documentation so I figured I'd request it.

**Comment by gabek** [comment]
We purposefully don't use autoplay because it's muted by default, so I can't imagine most people want to have to press two buttons (play, and then unmute) in order to fully watch a video. But I also don't see any harm if that's something that was really wanted by somebody, since you'd have to add the parameter.

**Comment by andrew-secret** [comment]
I could take a look at this one.

**Comment by LBBO** [comment]
Hey, this seems like a good first issue, right? If so, I'd love to work on it!

**Comment by gabek** [comment]
In theory it should be:

1. Check if muted query parameter exists 
2. Add a parameter to the player to be muted if the query parameter is there

So I think it should be as straightforward as that. Go for it!

**Comment by KyleMaas** [comment]
Awesome!  Thank you!
