### ISSUE TITLE
add fallback in case the contributors list could not be fetched for the website

### ISSUE THREAD

**Issue by MFTabriz** [owncast/owncast#2475]
The website build script randomly fails to fetch the contributors list (see [1](https://github.com/owncast/owncast.github.io/commit/7835ce6be5fc9fc61b1d8e655791a5887b3143d7)) and ends up deploying an empty list.

![image](https://user-images.githubusercontent.com/39205857/208892912-35ce059a-9e48-4a24-a2b4-7022c98a82c8.png)

**Comment by gabek** [comment]
I have a monitor on the OpenCollective API to make sure > 1 entries are being returned and the monitor has never failed. Are you sure the issue is with the API and not something on our end? I'm not saying it's not the API, because that's why I'm monitoring it, but it hasn't failed the entire time I've been monitoring it.

Previous discussion happened at: https://github.com/owncast/owncast/issues/2187

![image](https://user-images.githubusercontent.com/414923/208976043-89c89f3f-e575-4384-bd4e-ccdf02ed5e98.png)

**Comment by MFTabriz** [comment]
I will add some checks to CI to catch exactly why it is failing
