### ISSUE TITLE
Mobile layout has double scroll bars

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2499]
### Share your bug report, feature request, or comment.

Only the content inside the tabs should be scrollable in a mobile layout. The player should be static.

![image](https://user-images.githubusercontent.com/414923/209457382-8cb20029-7dd9-4e8f-b83a-3db55edf4a01.png)

**Comment by andrew-secret** [comment]
That sounds like a good first issue to me :) I'll take it

**Comment by gabek** [comment]
Sweet! Thank you!

**Comment by andrew-secret** [comment]
I think I found the issue for our double scrollbars. The reason for this behavior was that we are calculating the height of the `MobileContent` by using the `useHeight` hook without subtracting the height of the footer element.

One way to fix this is:

```tsx
const height = `calc(${useHeight(mobileContentRef)}px - var(--footer-height))`;
```

That would look like this:
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/13103896/209485044-b10893f5-847f-46b0-a6d9-25c57556c2ba.png">


## Other solutions
- don't show the footer on mobile

## Double scrollbar is also visible on Desktop


https://user-images.githubusercontent.com/13103896/209486981-3902e02a-44f9-40f7-87df-5254ce79f4f6.mov


This is happening because we apply `overflow-y: scroll;` to the `mainSection` in the `Content.tsx`. How do we want to handle this behaviour?

Wouldn't it be better to remove this at all on desktop so the browser would handle it for us? Let me know what do you think about it.

**Comment by gabek** [comment]
Thank you so much for digging into this!

Ah ha, and that footer is double the height due to it wrapping into two lines on mobile, probably making it worse. That makes a ton of sense.

I'm totally on board for not showing the footer on mobile.

Thanks for finding that it's occurring on desktop as well. I'm totally up for whatever you think would be a good solution. If simplifying the styles applied to it can fix it, that sounds like a good approach!

**Comment by andrew-secret** [comment]
Sounds good to me. You welcome. I'll remove the footer on mobile and come up with a solution/proposal in a small PR. Maybe I need some help to actually setup and test it with a livestream, because I couldn't figure it out by myself.

**Comment by gabek** [comment]
uh oh. This seems to be connected. On mobile it no longer lets you scroll vertically at all. I'm assuming this is also the cause of #1933. 

![image](https://user-images.githubusercontent.com/414923/210038158-511fee5b-1733-4624-8b90-7c5b3f430b14.png)

**Comment by andrew-secret** [comment]
Oh no 😅 I can double-check it. Seems to happen only on a real device.

**Comment by andrew-secret** [comment]
Ok, little update regarding scrolling. It works now on iOS Safari. The reason for it is the `react-use` hook.  It somehow locks the scrolling for everything, works pretty well, I guess 😆. I might take a close look at this hook. Otherwise, I'll go with the previous solution (inline style in the head).

I'm currently debugging and running through a localtunnel on my iOS device. I apologize, it must be annoying to always report the same bug over and over. But I hope this time we're going to fix it for real!

I hope I can push something tmrw or the next day depends on how much Wine I'll drink 😅🥳

Happy new year to all of you 🎉

**Comment by gabek** [comment]
Awesome, thank you for tracking this one down! And a happy new year to you as well!

**Comment by gabek** [comment]
@andrew-secret Just checking in! Are you still looking at this?

**Comment by andrew-secret** [comment]
I will take a look I to this trmw and then write my final thoughts down or raise a PR 👌.

My work stuff came into my way 😆

**Comment by andrew-secret** [comment]
FYI: Ok I found a solution. Tested it on different devices and it should work. Currently trying to clean up a bit in order to raise a PR.
