### ISSUE TITLE
Height of chat sidebar overflows

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2503]
I specifically ran into this when testing on an iPad, but it's using the standard desktop layout of the page.

![image](https://user-images.githubusercontent.com/414923/209497887-6c9e22ed-c158-4eaf-814a-a4912e87c586.png)

**Comment by Satoshi-Sh** [comment]
I'm on this issue.

**Comment by gabek** [comment]
Awesome! I want to just ping issue @andrew-secret working on #2499 as I'm not sure if it's related or not. It might be worth giving that issue a read just in case.

**Comment by Satoshi-Sh** [comment]
I was just testing it locally on the Chrome browser. It doesn't overflow even with a small window as mentioned. It might be fixed in another task. 

Just for your info, I have never contributed to open-source projects before. Please feel free to correct me, if I'm wrong. Thanks. 

 ![Screenshot from 2022-12-27 20-01-19](https://user-images.githubusercontent.com/73622805/209745787-e30a1acf-ef39-47b0-8bd4-540af3c84e78.png)

**Comment by andrew-secret** [comment]
Yeah, I'm working on this issue because it is part of the scrolling behavior I try to solve in https://github.com/owncast/owncast/issues/2499

I will write a more detailed explanation in the PR 🙂

**Comment by Satoshi-Sh** [comment]
I will unassign myself.

**Comment by andrew-secret** [comment]
I think that issue should be resolved by https://github.com/owncast/owncast/pull/2509
