### ISSUE TITLE
Add Google Cast support

### ISSUE THREAD

**Issue by FireTime** [owncast/owncast#2557]
### Share your bug report, feature request, or comment.

Would be nice to be able to view streams using chrome cast devices without the need to use the desktop tab cast feature. 

Assuming the stream is already using a [compatible codec](https://developers.google.com/cast/docs/media) (the default Owncast settings are) the HLS protocol and the mu3p playlists are already compatible with chrome cast devices. 

I've spun up a [proof of concept](https://fireti.me/cast/?s=https://live.retrostrange.com) that uses the [castjs library](https://github.com/castjs/castjs). The s post variable can be updated to public Owncast stream and the page will pass it along to a chrome cast device once the button is pressed. This should work on mobile as well as desktop devices on the same network as a Google Cast enabled device.

The POC page source is below is below
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Cast Test</title>
</head>
<body>
    <button id="cast"> Cast </button>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/castjs/5.2.0/cast.min.js"></script>
    <script>
    var url = new URL(window.location.href);
    var domain = url.searchParams.get("s");
    const cjs = new Castjs();
    document.getElementById('cast').addEventListener('click', function() {
        if (cjs.available) {
            cjs.cast(domain + '/hls/stream.m3u8', {
                poster     : domain + '/logo',
                title      : domain,
                description: 'Owncast live stream'
            })
        }
    });
    </script>
</body>
</html>
```

As of now the POC works for my use case as a link from the Custom Page Content but would be nice to have more properly integrated.

**Comment by gabek** [comment]
There was some previous discussion around this over at https://github.com/owncast/owncast/issues/410. The consensus was that we didn't feel comfortable ping'ing Google every time somebody loaded an Owncast stream. Maybe there would be an option with some other browser APIs, but there was nobody to focus on it.

The requirements would be:

1. We can bundle the script locally, and not pull it down from a CDN or remote location.
2. It doesn't require using Google APIs if Chromecast is not active or has no intention of being used.

Do you know how the above castjs could fit in with that?

**Comment by FireTime** [comment]
Sorry about missing previous request.

As for the two requirements:

1. The cast.js library is MIT licensed so I'm assuming it should have no issue with being distributed along with Owncast. However per the [google Integrate Cast SDK "Load the library"](https://developers.google.com/cast/docs/web_sender/integrate#Load%20the%20library) any at some point in the code flow once casting is requested it would be necessary for the users browser to pull down a script from a google gstatic server to connect with Google Cast devices.
2. Castjs could be loaded on user action to start the casting process. Before that no calls to external servers would be required. I've updated my [POC](https://fireti.me/cast/index3.html?s=https://live.retrostrange.com) to do just that. Before selecting the cast button no external resources are loaded.

**Comment by gabek** [comment]
> Castjs could be loaded on user action to start the casting process.

That sounds perfect, but if Castjs isn't loaded, how does it know if any Chromecast devices are available? It feels like a bit of a chicken and an egg situation, so that's why we've been stuck. I'm fine loading scripts from Google if the the user said they wanted to partake in a Chromecast session, but without loading scripts from Google (or Castjs) I'm not aware of a way to know if a Chromecast session is possible.

**Comment by gabek** [comment]
Maybe we could add a "Enable/Disable Chromecast" option in the player's menu. If it's enabled we load the script and start detecting Chromecast devices you can select, if not, it doesn't talk to Google and doesn't load. It would be a little awkward, since you'd have to know to enable it, though. And the wording might be weird because just because you "enabled" the support doesn't mean you actually have a Chromecast device, we wouldn't know that. Maybe something broader like "Enable Google casting" would be more accurate.

It would solve the "off by default" approach of contacting Google unless the user really wanted to.

**Comment by FireTime** [comment]
Can be more of a user experience question of: "Is displaying a cast icon but no valid cast targets is acceptable?" Android applications like Spotify and Youtube always have the icon visible while Twitch seems to only display the icon after its detected at least one valid casting device.
![NVIDIA_Share_pm1kl2hcwm](https://user-images.githubusercontent.com/8028436/211178198-94e47ba9-b7b9-40ed-b23d-4de78f499cde.png)

Or as you mentioned could be a togglable setting hiding under the gear to enable casting functions.

**Comment by gabek** [comment]
> "Is displaying a cast icon but no valid cast targets is acceptable?"

I would say no, mostly because in the case somebody is using Safari on MacOS or iOS it would show both the AirPlay icon *and* the Chromecast icon, and only one of them would do anything, leading to immense confusion unless the whole thing was rearchitectured to work more like Spotify where the Chromecast icon isn't really a Chromecast icon, but more of an "External devices" icon that led to more menus and both Chromecast and AirPlay would live within it. While I'm not opposed to that, it would be a lot of work.
