### ISSUE TITLE
Hide the address bar on mobile

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2586]
The address bar takes up a lot of vertical space. It auto-hides as you scroll the contents of the page, but in our case there is no full page scrolling as our content is locked to specific areas. 

It would be great to reclaim this space and find a way to hide it if at all possible.  

Mobile safari: 

![image](https://user-images.githubusercontent.com/414923/212580990-b1c0c319-c58f-4322-aa39-d5f13ce51bd6.png)

Mobile brave:

![image](https://user-images.githubusercontent.com/414923/212581415-2db5a694-e850-47c0-b84b-3010f0815b57.png)

**Comment by LBBO** [comment]
I think this might be tricky to do because there needs to be a clear way to show the bar again. Also, from some quick research and experimenting, it seems to be rather difficult to hide this bar consistently and programmatically.

One way to kind of get around this might be to add a `Hide browser bar` button that would actually just be a fullscreen button, but that seems kind of weird to me and it would need to be embedded into the design nicely. Also, users would notice what's going on since browsers show a "how to exit fullscreen" notice, which might be a bit irritating to some users.

Another idea would be to just promote the use of Owncast as a PWA since the bar is already hidden there.

**Comment by gabek** [comment]
The problem is the browser will auto-hide this once you scroll, but #2585 locks scrolling. So this isn't a problem that generally exists but exists now for us.

**Comment by LBBO** [comment]
I see, I misunderstood the issue. It isn't that you want to hide the bar immediately when users open the page but you just want to somehow enable users to hide the bar, right?

A large bit of my comment still stands, though. Hiding the bar programmatically seems hard to do consistently (if at all possible; I couldn't get anything to work in Chrome on Android). Going fullscreen is an option, but it seems kind of hacky. 

Another idea I can come up with would be to somehow make the main content's scrollbar actually be the body's scroll bar, so you aren't scrolling in some div but in the actual body. This could perhaps be achieved by making some elements' positions fixed, but it would likely be alot of hassle.

**Comment by gabek** [comment]
We've had a lot of problems trying to work on this. @andrew-secret has been working hard on it, but every change that's made in one direction throws things off in another. The original issue was multiple scrollbars, so he put in a bunch of work so things would be fixed and only the content body would be allowed to scroll. But now because the global page isn't allowed to scroll things like the keyboard doesn't show properly and the address bars won't hide themselves because they're supposed to hide on scroll, and we no longer allow scrolling.

**Comment by andrew-secret** [comment]
Another solution could be to restructure the markup and try to make everything `position: fixed`. Therefore, we would need to do more calculations in some `useEffects`. Then we would have the default behavior from the browser.

If we rebuilt this, I would recommend splitting desktop and mobile layout into separate files to get a better overview.

But my concern here is I don't know how the tabs are working exactly. If they have the [compound components pattern,](https://www.smashingmagazine.com/2021/08/compound-components-react/) then we rely on a certain structure.

Another way could be to reconsider the design because those layouts are looking more native app like to me. For instance, if you double-check YouTube or twitch, you won't find that complexity in their layouts. But maybe I'm just talking bullshit and I can't solve this properly 😅 Just wanted to think out loud a bit..

**Comment by gabek** [comment]
We landed on the current layout simply because other layouts weren't working on mobile. Showing chat as a tab simplified the UI from a user perspective compared to the other options where you had to toggle chat and on off in menus or with buttons you had to discover in order to read the "About" content.

We could certainly split up the desktop and mobile layouts if that's helpful. I'm not sure if you're thinking the entire screen, or just the content part. The content is split right now for desktop and mobile, but the rest of the page is the same.

But yeah, it does feel like there is an overarching issue that can't be solved, but it's hard to believe it's impossible or require a complete redesign.

**Comment by andrew-secret** [comment]
@gabek I hope so too that there is a good solution out there w/o going all over again. I'll keep my eyes open. If I find something I'll let you know here.

**Comment by gabek** [comment]
A side note that's tangentially related: I recently hid the scroll bars on the page, just to make it look cleaner (and the original v1 of the owncast web UI also had hidden scroll bars). So the original-original issue of double scroll bars can't technically be possible when there are no scrollbars to show, so maybe that helps a bit.

**Comment by gabek** [comment]
Investigating it seems like other sites have this same problem when they lock to a single unscrollable viewport, so I'm going to close this and no longer worry about it.

**Comment by TheTechmage** [comment]
I know this is closed, but I wanted to add my two cents from Android. Because of the inability to fullscreen or scroll, the textbox becomes inaccessible in Chrome on my Pixel 5, as can be seen in the screenshot. I am unable to scroll to the textbox and am therefore, unable to chat at all.

![image](https://user-images.githubusercontent.com/509363/230637154-f4358082-3dcf-4b2d-9efd-fd2b1ee27ed2.png)

**Comment by gabek** [comment]
Hi there @frostyfrog. This issue and discussion was for the future v0.1.0 release. From your screenshot it doesn't look like you're testing the pre-release build (nor would I recommend you do so). So whatever you're seeing in the previous version isn't overly applicable to the current work going on in this case. But thanks for checking in!
