### ISSUE TITLE
Changed Port from 8080 to 443 Cannot Access Web Panel

### ISSUE THREAD

**Issue by Vegas10128** [owncast/owncast#2665]
### Share your bug report, feature request, or comment.

I am trying to find where the directory on command line in order to change back to 8080 if someone can please help me with that.

**Comment by Vegas10128** [comment]
Sorry some information to add here. 
Currently using Ubuntu 20.04 with the bash installation, not using docker.

**Comment by gabek** [comment]
Hi there. Could you add some detail about what's going on? You mentioned the directory and ports, but I'm not exactly sure what your exact problem is from your issue, so maybe a bit of background and specifics might help.

**Comment by rmens** [comment]
Try running Owncast with `-webserverport 8080` as flag. So for example:

`./owncast -webserverport 8080`

This should override the configuration you made and put the web interface back on port 8080, so you can correct the error.

**Comment by gabek** [comment]
While it's uncommon, there's nothing technically stopping you from running standard `http` over port 443 instead of `https`. Make sure the browser has the correct protocol specified.

But what rmens said is probably the best bet, just change it back. However none of this deals with the directory like you mentioned in your initial issue, so please clarify if we're interpreting your request incorrectly.
