### ISSUE TITLE
Ability to recover or remove inaccessable fediverse account

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#2670]
### Share your bug report, feature request, or comment.

In my experience, when I've made the mistake of not backing up and restoring my 'data' directory when reinstalling an Owncast server, after having previously enabled Federation (choosing to use the API to set up an instance instead), I'm no longer able to use the same username in Social Features. The interface allows you to use the same username, but when trying to follow that user, the old instance of that user appears, and no longer accepts follow requests or updates to the status. An example is @jnktn@test.jnktn.tv. That account still exists on the Fediverse, despite not being active for several months.

If you use another username, Federation works as it should, since it creates a new account which allows follows and status updates. The documentation that appears when you enable Social Features states that if you change username, the old account will 'disappear', which doesn't look to be the case. If you search the old user, it still seems to exists, but in an unrecoverable state. Even if I change the Fediverse server I search the account on (tested on fosstodon.org, mastodon.online, veganism.social), the account still appears.

So, is there or will there ever be a way of recovering or removing an old account that was created via Owncast's Social Features, after a user reinstalls their Owncast instance without their original 'data' directory? I understand that this is most likely something Owncast can't do anything about, so it's more to detail a 'bug' that others may come across. If there is nothing that can be done, should documentation be updated to reflect that backups of the 'data' directory are mandatory for those that want to keep their current Fediverse username, and with it, their statuses and followers if they want or need to reinstall their server?

**Comment by gabek** [comment]
I think there needs to some clarification on what's going on since it's not clear.

If you change the account name the old one is no longer valid.

This is accurate, and Owncast will no longer respond when asked about the original account. However that doesn't mean that the **Fediverse** will just magically forget about that original account. Fediverse servers cache identity data and the keys associated to that user. So if you delete the `data` directory and set the username to be the same as it was before, the keys will be different and when a Fediverse server that knew about your user before tries to interact with it again. It will just error out seeing that there's an account of the same name but with different identity.

Is there a way of recovering an old account?

Absolutely, but it's the `data` directory.  There are identity keys that are associated to a Fediverse account and if you lose them then there's nothing you can do about it. If you could build an old Fediverse identity out of thin air and make the entire Fediverse trust it then people could buy up old domains and fake other people's old identities.

Is there a way to Delete an account?

Technically yes, but you'd need to do that before you deleted the `data` directory and lost the keys. Owncast does not currently send out a "Delete" but this wouldn't have solved your specific issue anyway. A valid user needs to send out a Delete request to all the servers who know about it, and you wouldn't be able to do that after deleting `data` and losing your account.

Like anything else, backups aren't mandatory. I can't tell you what to do. But also like anything else if you delete your data, it's gone. I understand that's annoying, but it's not unique to Owncast. Everything Owncast saves is in that directory. There's even a `-backupdir` flag to save backups elsewhere at the very minimum if you really refuse to do real backups, just make sure you have a copy of it somewhere.

So while the documentation could enumerate all the things that you'd lose if you deleted your `data` directory, it's really _everything_ just like if you'd delete your data from any application.

That said, if there's something that I'm doing wrong or could be doing better or there's some kind of expectations I'd be happy to improve things.

**Comment by ghost** [comment]
Thanks for the clarification @gabek. It's the fault of the user for not backing up and restoring the `data` directory, and I am aware that I should have done that when reinstalling the server. It was more just to see if there's anything that can be done in this situation. It would be great to have the ability to delete the current Fediverse account before going about reinstalling a server, so that the same username could be used again on the fresh install. Since this would technically be a new account, so followers and statuses wouldn't be kept, I guess it wouldn't be all that useful. Maybe if a user were to change the username of their Fediverse account, the old account could automatically be deleted, so that there isn't anything left lingering when the change it made.

I'm happy to close this, since the important data for an Owncast instance is in the `data` directory, and users should be making a point of backing this up between installs if they want ALL of the same data. Hoping this issue can help others realise their mistake if they've ended up in the same situation.

**Comment by gabek** [comment]
Just for to make sure, you mentioned that people should back it up "between installs", do you mean upgrades? You can upgrade Owncast in place just by dropping an updated version on top of the old one, there's no need to delete it all and start over each time. But if you are moving servers (something that probably doesn't happen that often) then you can just copy your whole Owncast install from one machine to another and start where you left off unless you really wanted to start over from scratch.

**Comment by ghost** [comment]
I don't mean upgrades, since I'm aware that that can be done in place. I'm just one of those people who likes to mess around and break things, then tear a VPS down and rebuild it to start fresh.

Will backing up and restoring the `data` directory always work? Will anything break if, for example, you backed up your `data` directory from an older version of Owncast, such as 0.0.10, and restored it to a newer one like 0.1.0?

**Comment by gabek** [comment]
As long as you're using a copy of older data with a newer version of Owncast it'll migrate the data to use in the newer version. The other direction, however, using newer data with an older version of Owncast, won't work.

**Comment by ghost** [comment]
Good to know. Thanks for the info @gabek. As I say, I'm happy to close this and treat it as a reference for those that may be in the same situation.

**Comment by gabek** [comment]
Works for me!
