### ISSUE TITLE
Followers: Avatar image should use placeholder 

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2677]
### Share your bug report, feature request, or comment.

We should use a placeholder image for the avatar (`/logo`) if an image doesn't exist or it errors out when loading.

![image](https://user-images.githubusercontent.com/414923/216791082-b1161318-deb9-474b-9af8-3480a7cc3235.png)

**Comment by JacobWrenn** [comment]
Hi, I'm new here but I'd be interested in taking this on if that's OK?

**Comment by gabek** [comment]
Absolutely, thanks for reaching out and offering! Let me know if you run into any questions.

**Comment by gabek** [comment]
Hey @JacobWrenn! Just checking in to see if you're still looking at this or if you've had any issues getting things up and running.

**Comment by JacobWrenn** [comment]
Hi @gabek I've been able to get everything setup OK. I've been able to use the storybook to view the follower list and from my first inspection it appears to be behaving properly except for the fact that /logo is not found on the storybook server. Could you point me towards where I can find the followers list when running the full server locally so that I can view how it is behaving there?

**Comment by gabek** [comment]
The list of followers only displays when you have that functionality enabled, so you'd either need to setup a fully functioning Owncast server or fake the data. The easiest way to look at it is through Storybook so you don't need to do any of that. Here's an example of the list in action via the nightly deployment: https://nightly.owncast.tv/

It does look like the placeholder is showing up, but just very oddly.

<blockquote><img src="https://nightly.owncast.tv//thumbnail" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast Nightly</div><div><strong><a href="https://nightly.owncast.tv/">Owncast Nightly</a></strong></div><div>This is a server running the nightly build of Owncast.</div></blockquote>

**Comment by JacobWrenn** [comment]
I have opened PR #2709. It should resolve the styling issues of the avatar placeholder. I did try to change the storybook config so that /logo would be accessible to the previews however it seems it wouldn't be possible to do this. However, everything should look good when being served from an Owncast server.
