### ISSUE TITLE
Stream key not passed on from command line to webinterface

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2749]
### Bug report

I'm running Owncast 0.1.0 in Docker with this command

`docker run -p 8080:8080 -p 1935:1935 ghcr.io/owncast/owncast:nightly -streamkey xyz987 -enableVerboseLogging`

And my encoder connected without a problem using this stream key. However the web interface doesn't reflect that this key is in use. It shows the default key.

<img width="732" alt="Schermafbeelding 2023-02-27 om 23 12 30" src="https://user-images.githubusercontent.com/6742496/221698219-b3742978-861c-418c-a681-596200acb0f7.png">

**Comment by gabek** [comment]
This is indeed confusing.

When using `streamkey` on the command line it sets a temporary/session-specific stream key. I believe it might even use the word temporary in the `--help` output. It doesn't add it as a new key for future use or change any previous stream keys that were saved permanently.

I don't recall offhand if setting this temporary key disables the keys that were previously saved (such as `abc123` in your example). I'll look into that.

Because there used to only be one key, setting it via the command line flag was less confusing because it would simply use the new key instead of anything that was previously saved. But with multiple keys:

1. Should setting a CLI key disable all other keys?
2. Should a CLI key show up in the admin as the key? It's not saved so you can't delete it and it would disappear if you restarted Owncast without the flag.
3. Should setting a CLI key completely disable the UI for saving keys in the admin?

I'm thinking the UI for managing stream keys should be disabled if you're setting a key via the CLI so the confusion you're seeing doesn't occur. It's not helpful for this UI to exist if you're managing keys externally.

And because the UI would no longer be supported the answer for #1 should be yes, setting a CLI key should disable all other keys, not merge them. Merging keys would cause more confusion about the what's and why's and require a more complex UI to explain it.

In the future if there's more bandwidth we could have a more comprehensive stream key management UI that shows more detail around different types of keys, where they came from, why some actions exist for some but not others, etc.

**Comment by rmens** [comment]
My $0.02:

1. Should setting a CLI key disable all other keys? > **Yes**
2. Should a CLI key show up in the admin as the key? > **No**
3. Should setting a CLI key completely disable the UI for saving keys in the admin? > **Yes**
