### ISSUE TITLE
Styling inconsistencies in video configuration screen

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#2803]
### Share your bug report, feature request, or comment.

- The word 'Lowest' breaks out of it's div
- The heading for the advanced settings collapsable element could use the same bg color as the stream output section
 
<img width="1341" alt="Schermafbeelding 2023-03-12 om 13 31 13" src="https://user-images.githubusercontent.com/6742496/224545215-e521c5ab-e1a7-47b7-b1c5-fa650e11bc8b.png">

**Comment by gabek** [comment]
Some tweaks to the above comment:

- It does look the L of "Lowest" is directly against the left column, so it's probably not overflowing out of the column, but instead maybe there just needs to be some margin between the left and right sides. Each of those admin sections have their own internal padding so I'm guessing that's why they're not directly against the other column.
- Don't change the background color of the "Advanced settings" but instead set consistent global background color for collapsible headers. If each one was set individually then the inconsistencies would grow across different admin pages. This should be handled with all the rest of the admin styling that needs to be done.

**Comment by gabek** [comment]
I had originally pushed this off until v0.1.1 but given some bigger issues for v0.1.0 are still blockers there's probably still time to get smaller things in without pushing out the milestone.
