### ISSUE TITLE
 Unsupported operating system

### ISSUE THREAD

**Issue by henish1400** [owncast/owncast#2813]
### Share your bug report, feature request, or comment.

Unsupported operating system MINGW64_NT-10.0-25314Your Owncast installation did not complete successfully.

![image](https://user-images.githubusercontent.com/102351385/224627136-cdf0247e-6fdc-4ddb-9989-0de8d60dd8c5.png)

**Comment by gabek** [comment]
Could you expand on your issue? What are you trying to do?

**Comment by henish1400** [comment]
I want to use the Owncast Quick Installer Script.

**Comment by gabek** [comment]
What operating system are you trying to install on? What is MING?

**Comment by henish1400** [comment]
windows 11

**Comment by gabek** [comment]
Owncast does not support Windows natively.

**Comment by henish1400** [comment]
so what's operating system support.

**Comment by henish1400** [comment]
which operating system support it?

**Comment by gabek** [comment]
If you go to the releases you can see the binaries that are available for download: https://github.com/owncast/owncast/releases/tag/v0.0.13

Owncast, however, is open source and you're free to work on compiling your own binaries for whatever operating system you prefer, but there's no guarantees it'll run on anything that's not directly supported by the project.

<blockquote><img src="https://opengraph.githubassets.com/932cebb3aab9a2d5cdb2ed7f0a65f7adbf4db578712748177a380312d0ae8d3a/owncast/owncast/releases/tag/v0.0.13" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/owncast/owncast/releases/tag/v0.0.13">Release Owncast v0.0.13 · owncast/owncast</a></strong></div><div>Owncast v0.0.13 is a very small release targeting mostly bug fixes.
Since v0.1.0 is taking longer than hoped, this allows some updates to get out between now and then. But all the work for the new ...</div></blockquote>
