### ISSUE TITLE
Admin Password

### ISSUE THREAD

**Issue by darkdecoy** [owncast/owncast#2904]
### Share your bug report, feature request, or comment.

So currently the stream key and admin password are one and the same.  This is a bad security practice as you could have people streaming that you don't want to have admin access.  They really should be two different things.

**Comment by rmens** [comment]
Yes. This is fixed in the next big release.

**Comment by gabek** [comment]
I wouldn't say "fixed" :). The approach is changing, but the key and password has been the same because it was that way on purpose. Beginning in v0.1.0 there will be a new (more complex) way to manage stream keys. However, Owncast is still single tenant software and is intended to be used by a single user.
