### ISSUE TITLE
[request] Social/Fediverse - compose post extend composing feature?

### ISSUE THREAD

**Issue by valvin1** [owncast/owncast#2920]
### Share your bug report, feature request, or comment.

On nightly v20230410-nightly

I'm testing new compose post feature and I like it :) It allowes to announce something on the fediverse (and maybe other social platform?) without launching a stream. First time I used it I tried to import a media file (don't remember why). I think it could be interesting to extend composing feature in this dialog.

So it is a feature request but without any criticity :)

**Comment by gabek** [comment]
It's actually been there since v0.0.11, so not that new!

I appreciate the idea of wanting to upload media, but it does add a level of complexity where Owncast would start to host resources, possibly large ones, indefinitely. And then would probably need an interface to be able to manage those or clean them up on demand to save space.

If I had all the time in the world I wouldn't be opposed to adding more microblogging-style Fediverse features to Owncast, but that's just not the focus, and it opens up more questions than answers when you go down that road.

**Comment by valvin1** [comment]
maybe it is related to ui design because i didn't see the compose feature before :)  maybe i didn't look at it well before.

i understand you won't do this request thank you for the explanation.
