### ISSUE TITLE
[Feature Request] Increase the first valid RTMP packet deadline or make it configurable

### ISSUE THREAD

**Issue by kylosus** [owncast/owncast#2952]
### Share your bug report, feature request, or comment.

Owncast terminates the connection when ffmpeg establishes a connection, but starts sending packets late. This happens rather often in my experience when burning subtitles with `-vf` and/or doing stream mapping, which delays first packet, and slows down 
the subsequent few seconds, though ffmpeg can keep up afterwards.

I believe the following line is responsible for this behavior:
https://github.com/owncast/owncast/blob/b28c2f3dd6329002acb9ead6c8d56fcbe0c77c71/core/rtmp/rtmp.go#L118

It would help a lot if the deadline is increased to +15 seconds or so, or better, made available as a configurable value in the UI. I am willing to submit a PR for the latter if acceptable.

For reference, this is roughly the script I'm using to stream (video passthrough)
```bash
ffmpeg -re -ss "$TIMESTAMP" -hwaccel auto -copyts \
        -i "$1" -input_format yuyv422 \
        -c:v h264 -maxrate 2M -bufsize 12M -x264opts opencl \
        -preset medium -tune zerolatency -movflags +faststart \
        -vf "format=yuv420p,subtitles='$1:stream_index=0'" -ss "$TIMESTAMP" \
        -g 60 -c:a aac -ac 2 -map 0:v:0 \
        -map 0:s:m:language:eng? -map 0:a:m:language:jpn? \
        -sn -f flv "rtmp://$SERVER_URL/live/$STREAM_KEY"
```

**Comment by gabek** [comment]
Something sounds wrong if it takes over 10 seconds after you connect via RTMP to send the first packet. That points to more of a bug somewhere on your broadcasting side. Increasing that value is just randomly changing that value. 

This isn't an issue I've ever run into before and I use ffmpeg for streaming every day, including burning in dynamic text. For example start your Owncast server and then run `/test/ocTestStream.sh rtmp://$SERVER_URL/live/$STREAM_KEY` and you'll see dynamic text drawn into the stream.

I don't think this should be a configurable setting, as this isn't something that anybody has ever needed to configure before, and isn't something that you should need to configure now, and changing it to 15 seconds feels like a random number that just happened to work for you.

While I want to be helpful, I don't think random magic number changes are the answer. I do think the answer is fixing the broadcasting side so it does what it should.

**Comment by kylosus** [comment]
Thanks for the quick response!

Burning text doesn't _always_ result in delays, but I do experience it with some files, particularly when the files are large and contain multiple streams. I don't know what exactly ffmpeg does internally, but I'm assuming it establishes the connection before starting the heavy work, and spends however many seconds afterwards encoding.

While I do admit that the 15 seconds I suggested is arbitrary, I don't see why owncast cuts connections after _10_ seconds specifically - it seems to me like another magic number. Why not allow it to be configurable for edge cases like mine in advanced video settings or so?

**Comment by gabek** [comment]
It is slightly arbitrary. The reason it exists is to handle when a socket has an unclean disconnection. So I figured 10 seconds is a reasonable time to wait for a connection to be dead before the server actually gives up on it. Because of this, if you did legitimately have a messy disconnection you won't be able to re-connect for 10 seconds, because Owncast doesn't see you as disconnected yet. Moving that to 15 seconds would mean you wouldn't be able to re-connect for 15 seconds. And while it's only five extra seconds, that's starting to feel like a long time.

This is an edge case, such as streaming via a cell phone and you go into a tunnel, or something. 10 seconds is probably a high value as it is, but I figured it was a number that would reasonably give a valid connection a chance to stay alive.

**Comment by kylosus** [comment]
It makes sense that owncast has protections against dead connections hogging the server indefinitely, but waiting for 10 seconds (or 15, for that matter) is not a very clean solution imo. How about giving new connections a 10 second grace period, and only dropping them _if_ a new connection is attempted after the period has passed? That way clients clients have longer than an arbitrary number of seconds to initialize their streams, and re-connects are still possible.

I can implement this behavior, but I understand if the dev team doesn't want to complicate the rtmp logic further. Worst case I'll patch a few lines in my instance to fit my needs.

**Comment by gabek** [comment]
Having multiple concurrent RTMP connections and swapping between them while waiting for a timeout would absolutely add unnecessary complexity.

This isn't anything I'm currently looking to change since it's not an issue with Owncast. Having a timeout for dead sockets is a very common way to handle this, and while I understand it's getting in your way, if I were you I'd far prefer to fix the problem instead of patching over it by increasing the number of seconds until it works. Maybe you'll need 15 seconds today, maybe you'll need 20 tomorrow, maybe you'll need a minute and a half next week.

I apologize for not being helpful, but there's something wrong if your broadcasting client isn't sending packets for over 10 seconds and I don't feel comfortable patching the server to resolve this very specific issue.
