### ISSUE TITLE
Admin modals have incorrect title color

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2964]
### Share your bug report, feature request, or comment.

It's hard to read. There must be a modal header text color override being set somewhere that should be removed.

![image](https://user-images.githubusercontent.com/414923/235057006-31cc3405-58a4-415c-94e0-9983b51541c7.png)

**Comment by LJPR** [comment]
I'm taking a peep at this if you'd like to assign it to me :)

**Comment by gabek** [comment]
Awesome, thanks so much!

**Comment by 1Shubham7** [comment]
can I solve this issue? Please assign it to me.

**Comment by VaibhavKambar7** [comment]
I searched the entire modal folder and even some files in the admin folder, but still could not find the code for this.

**Comment by LJPR** [comment]
Looks like it's because the sass file that controls the variable for text color is at ./ui/modal/Modal.module.scss, and the modals that are affected are located in ./modals.  There are no styles imported to the modals that are broken. It's the FatalErrorStateModal in particular- called Global error state in storybook- which has no scss module of its own either. I'm newish to sass & less so I'm reading docs for the proper fix; would appreciate guidance if anyone has.

**Comment by LJPR** [comment]
As always, it turned out simple. :global was declared on only the child selectors, so the ./modals components did not have access to the class "modal".
