### ISSUE TITLE
[bug] macOS 0.1.0 release doesn't run on arm macs

### ISSUE THREAD

**Issue by compufox** [owncast/owncast#3056]
### Share your bug report, feature request, or comment.

Attempting to run the 0.1.0 macOS binary does nothing. no output, attempting to load the webserver by visiting the webpage does nothing but hang the browser. Attempted to run on intel and arm macOS versions. 

Intel version errors out with "address boundary error" while the arm64 version doesn't error and terminate at all.

Operating System: macOS 12.6.5 (arm) / macOS 13.4 (Intel)
Owncast version: 0.1.0

**Comment by gabek** [comment]
Maybe it's time to stop supporting macOS binaries. I don't have modern Apple hardware to test with these days. These kind of problems will only grow.

**Comment by rmens** [comment]
Can't reproduce on macOS 12.6.5 (Intel)

<img width="1426" alt="Schermafbeelding 2023-05-30 om 21 16 28" src="https://github.com/owncast/owncast/assets/6742496/add4ab4b-b966-43df-b73c-2f76af4be460">

**Comment by rmens** [comment]
Could reproduce on macOS 13.4 (ARM)

<img width="682" alt="Scherm­afbeelding 2023-05-30 om 21 29 30" src="https://github.com/owncast/owncast/assets/6742496/9401eeab-7ba6-4e8b-8665-43493c540ad5">

**Comment by gabek** [comment]
Just tested but this is an old mac. If somebody wants to work on a macOS  arm version feel free to chime in, otherwise I think this is the end of the road for mac binaries.

<img width="770" alt="image" src="https://github.com/owncast/owncast/assets/414923/ce2d99d7-be9e-4769-a5c6-2f0cb34075fb">

**Comment by gabek** [comment]
Are people actually running production Owncast servers on Mac hardware? Also, I thought the new macs were supposed to run Intel binaries?

**Comment by compufox** [comment]
I am, lol. And they do, although it's thru a translation layer. Which I think is the issue here...

I just spun up a mac vm (ARM - 12.6) and installed npm/golang and ran owncast using `go run main.go` and it ran fine.

![image](https://github.com/owncast/owncast/assets/1060898/94e8f87d-d427-4bc0-a977-b58887785643)

(the error in the console is because i hadnt installed the translation layer)

**Comment by rmens** [comment]
Can confirm. On the ARM Mac with macOS 13.4 Owncast does run when running from source. This is the same machine that doesn't run the compiled version.

<img width="1328" alt="Scherm­afbeelding 2023-05-30 om 22 58 53" src="https://github.com/owncast/owncast/assets/6742496/366402cf-8f56-4ed6-a00f-439b7e310c25">


The problem must be something with building the binaries.

**Comment by rmens** [comment]
Built my own executable on the ARM Mac with `go build main.go` and it runs without problems.

I think there should be separate binaries for macOS x64 and macOS ARM. According [to this article](https://dev.to/thewraven/universal-macos-binaries-with-go-1-16-3mm3) it shouldn't be too hard to build a universal/fat binary for macOS too. I'm not sure how Owncast is built @gabek, but this could be an easy fix.

**Comment by gabek** [comment]
Cross compiling is more complicated because of the cgo requirements. For reference he's how the builds are made. https://github.com/owncast/owncast/blob/develop/Earthfile

<blockquote><img src="https://repository-images.githubusercontent.com/266445736/4f82fb80-a5b1-11ea-8f1c-69d316f861b5" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/owncast/owncast">owncast/Earthfile at develop · owncast/owncast</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - owncast/Earthfile at develop · owncast/owncast</div></blockquote>

**Comment by compufox** [comment]
I'm still getting the error (the "Address boundary error") I mentioned in my original post on my Intel mac running 13.4 but compiling my own version works like a charm. I'm assuming this is another build related issue.

**Comment by gabek** [comment]
I'll leave this issue open to see if others are running macOS in production, but I think the plan forward needs to be to stop shipping macOS binaries.

**Comment by gabek** [comment]
I left this open so those who use Owncast in production on Macs could chime in, so I could gauge how common it is. Nobody has added to this thread.

However, [somebody on the fediverse](https://mastodon.social/@rmasoni/110573040025827916) felt that not supporting mac binaries was unacceptable and found it odd that [I didn't just ask for help](https://github.com/owncast/owncast/issues/3056#issuecomment-1569017102). So I wanted to ask for help and see who would be interested in adding ARM binary support to Owncast and its future releases. This would require a reproducible test under CI, just like we do for Linux, especially since there's no way for me to test them locally.

**Comment by rmasoni** [comment]
Just saw this and wanted to thank you for trying. That somebody was me.

I lack the technical knowledge to help implementing this, but I'd be more than willing to help test ARM builds.

I see @compufox and @rmens were successful in running it. Are you able to help?

Edit: perhaps just adding instructions for macOS users on how to manually start it like they did would suffice?

**Comment by gabek** [comment]
Good news, I have in my possession an ARM mac. It's not mine, but I can use it. So hopefully I should be able to figure out how to create Apple Silicon binary releases for Owncast and update the installer to support them.

**Comment by gabek** [comment]
Updated installer will be deployed with v0.1.2. Earthfile has been updated.
