### ISSUE TITLE
Feature: A credits or community page inside the Admin interface

### ISSUE THREAD

**Issue by CaptainCalliope** [owncast/owncast#3092]
### Share your bug report, feature request, or comment.

I think there should be something like a credits or community page in the Admin interface, on a tab just above or below the Help tab.

A blurb about how this is an open source community project, how the sausage is made, ways to contribute/get involved, and some information and/or embeds showing major code contributors and donors. (you can be one too! click here!)

**Comment by gabek** [comment]
The new version of Owncast does, in the footer, have links to project resources. I felt like this was ok because people who visit an Owncast-powered stream might be curious how it worked and this could point them in the right direction of being involved or learning more. 

In theory I'm not opposed to adding to the admin. But I do think of Owncast as server software, pieces of infrastructure that people deploy just like Apache, Nginx, Postfix, etc and I'd be annoyed if those projects were pinging me within the software itself. Once somebody downloads Owncast I do think they should be mostly left alone. I had a hard time deciding if we should do the "News" section because that requires a remote call to pull in that data, and I felt like that was really pushing the line of what I was comfortable doing.

The biggest thing I can ask for is more contributors who want to be involved consistently, and for people to help with non-code related things like a dedicated designer, social media person, etc. As a compromise I did recently mention in the news section that we're still looking for a designer. But I don't think it's going to help. There's just no interest. I'm not sure adding an additional section to the admin will change anybody's mind on that front.

I think people know it's an open source project, and I haven't been quiet about our needs. But if people really think the admin is a place to try to pull people in, I would do it. I'm just not sure awareness is the problem. I think it's interest.

**Comment by gabek** [comment]
I may have changed my mind. As an experiment I added the "looking for designer" post to the admin news section, and it was there a while, but eventually somebody saw it and dropped by the chat yesterday to learn more.

So maybe the admin is a place to put more of these kind of things, after all. I'd love to hear what other people think. Do you often drop by the admin? Or is it something you rarely look at once Owncast is configured for the first time?
