### ISSUE TITLE
Firefox requires clearing cache often to log into the admin

### ISSUE THREAD

**Issue by anegadian** [owncast/owncast#3097]
### Share your bug report, feature request, or comment.

I have upgraded to v0.1.0. The service itself works (I can stream as before).

However, I can no longer connect to the admin interface.

Dump from curl:

```
> curl -i http://stream.bvipirate.com:8080/admin/
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Origin:
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
Www-Authenticate: Basic realm="Owncast Authenticated Request"
X-Content-Type-Options: nosniff
Date: Wed, 21 Jun 2023 19:27:25 GMT
Content-Length: 13

Unauthorized
```

**Comment by gabek** [comment]
That looks correct, the admin requires authorization. Without it you'll get the unauthorized response.

You could try doing `curl -u admin:YOURPASSWORD -i http://stream.bvipirate.com:8080/admin/`

**Comment by anegadian** [comment]
Fine for curl. How do I connect to admin with browser? Browser to http://stream.bvipirate.com:8080/admin/ returns 402 Unauthorized.

**Comment by gabek** [comment]
This sounds oddly similar to an issue somebody had with Chrome yesterday. Every browser was fine except for Chrome. https://owncast.rocket.chat/channel/general/thread/ZsQcGm8AhsRzfwaHR

<blockquote><img src="assets/favicon_512.png" width="48" align="right"><div><strong><a href="https://owncast.rocket.chat/channel/general/thread/ZsQcGm8AhsRzfwaHR">Owncast</a></strong></div></blockquote>

**Comment by anegadian** [comment]
Resolved. Cleared browser cache and data.

**Comment by TheSamsai** [comment]
I don't think clearing the cache and data is a reliable solution, more a temporary workaround. On my server I have to clear the cache basically every day in order to be able to login to my admin panel. This is also with Firefox, so not exclusively a Chrome problem.

**Comment by gabek** [comment]
I apologize, but I honestly don't know what the solution is. I don't believe it to be an Owncast problem because it works for every other browser. I'm not sure what Firefox is doing to cause this problem, so I'm not sure how to resolve it. It's clearly caching something that it shouldn't be, and that other browsers don't, and I'm not sure how to control that.

I'll reopen this in case people have ideas.

**Comment by TheSamsai** [comment]
No worries, it's not a showstopper because a temporary workaround exists. I'll see if I can get some more info on it next time it happens to see what kind of authentication challenge the server might be sending back, maybe it responds differently with existing cookies that are now invalid? It could also be that somehow Chrome and Firefox just are mishandling status code 401 in some circumstances.

**Comment by TheSamsai** [comment]
Okay, I managed to catch two instances of getting logged out, in one case the login prompt came up normally (don't really know why that time) and in the second case it didn't. The headers seemed identical in both cases but when I looked at the network traffic on the developer console there was one difference: when the login prompt didn't come up the "Transferred" column showed "service worker" rather than a transferred data figure like in the case of the successful login prompt.

![image](https://github.com/owncast/owncast/assets/4444065/5cf0fcde-0305-4f68-8e46-f98d5bcb0a2d)

So, if I had to guess, there is some kind of a scenario where the loading of the page gets kicked off to a service worker which doesn't bring up a login prompt, probably due to some kind of a difference between how a service worker reacts to a 401 as opposed to a normal page load. But why exactly the page gets loaded by a service worker in one case and normally in other cases is a mystery to me.

**Comment by gabek** [comment]
Thank you for looking into it and reporting back! I'll do some digging to see if anything can be tweaked around the service worker. Firefox might just be working with it differently.

**Comment by YellowOnion** [comment]
I get this issue on Firefox.

**Comment by gabek** [comment]
@YellowOnion Have any idea why?

**Comment by vijay-prema** [comment]
I also always had this issue in Firefox.  My workaround is to always access /admin in a new incognito window.

**Comment by gabek** [comment]
Control+shift+r fixes it when you run into it, it'll clear the cache. Incognito isn't necessary.

**Comment by mahmed2000** [comment]
It is a service worker issue.

Service workers are disabled in private browsing and over non-localhost HTTP and I've had no issues testing there. Happens on localhost and the devtool application tab shows the service worker running. Unregistering it from there will let a reload work properly. Until the sw.js starts running again and then it's back to 401s on the next reload.

These seems relevant:
https://www.github.com/nuxt-community/pwa-module/issues/94
https://stackoverflow.com/questions/37934972/serviceworker-conflict-with-http-basic-auth

Apparently its fixable, but I don't know enough about PWAs yet to do much.

<blockquote><img src="https://opengraph.githubassets.com/3f379624e91f67575c3aa368407dbc83a303e1e7167330bf6e6a1743c85be82b/nuxt-community/pwa-module/issues/94" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nuxt-community/pwa-module/issues/94">Basic Auth won't prompt for credentials due to service worker caching response · Issue #94 · nuxt-community/pwa-module</a></strong></div><div>Affects: v2.4.0 Currently with a service worker caching pages, HTTP Basic Auth is broken. Upon initial load a user will be prompted for credentials, however, due to caching, this prompt will never ...</div></blockquote>
<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/37934972/serviceworker-conflict-with-http-basic-auth">Serviceworker conflict with HTTP basic auth?</a></strong></div><div>I'm trying to protect a site during an early stage of development from casual prying eyes. Basic auth over HTTPS seemed like a reasonable solution but the presence of a serviceworker seems to preve...</div></blockquote>

**Comment by mahmed2000** [comment]
Might be less Firefox breaking, and more Chromium does weird things to support this use case as is.

Under Storage -> IndexedDB -> workbox-expiration -> cache-entries
Shows all cached urls for the service worker by the corresponding cacheNames (all use an "expiration" plugin, see Sources -> sw.js)

cacheNames include "static-js-assets", "static-style-assets", "cross-origin", etc. All of them are a part of next-pwa's default runtimeCaching: https://gitlab.com/serwist/next-pwa/-/blob/v5.6.0/src/cache.ts?ref_type=tags.

This also includes "others" and "apis", neither of which the `next.config.js` names or would override. All /api/ urls go into the "apis" strategy and all the /admin/ calls are being caught by the "others" rule. I've tried reverting the order since the docs say it matters but there might also be a regex issue.

In the default strategy, the only patterns to use the `^` at the start are for external fonts with https prepended. I'm guessing the urlPattern only matches the full url and the only fix is to use arrow functions like the last 3 of the next-pwa default.

<blockquote><img src="https://gitlab.com/uploads/-/system/project/avatar/56334129/next-pwa.png" width="48" align="right"><div><img src="/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png" height="14"> GitLab</div><div><strong><a href="https://gitlab.com/serwist/next-pwa/-/blob/v5.6.0/src/cache.ts?ref_type=tags">src/cache.ts · v5.6.0 · serwist / next-pwa · GitLab</a></strong></div><div>Zero-config PWA plugin for Next.js 🧰 https://ducanh-next-pwa.vercel.app/</div></blockquote>

**Comment by gabek** [comment]
I thought I was excluding all of the api and admin paths from the service workers pulling down assets, but now that we know it's the service worker, and my exceptions are not working, it should be fixable. Like you said, maybe it's a regex, or perhaps it's a configuration somewhere. I'd like to think it should be straightforward.

The point of this specific functionality with the service worker was to pre-load web components so when you click on a button or some piece of UI pops up, you don't see a spinner and have to wait for it. Another nice side effect is emojis are pre-loaded, so you don't see a broken emoji the first time its sent, and then you see it fill in. It all feels more snappy with this approach.
