### ISSUE TITLE
Emoji markup is cut off when hitting character limits, breaking the images

### ISSUE THREAD

**Issue by dev265545** [owncast/owncast#3120]
### Share your bug report, feature request, or comment.

https://github.com/owncast/owncast/assets/73140257/d72002f6-037b-47f5-8690-68d3c53e8fd8
Watch this video in 2x or by skipping
Added this video for context.
While adding 3-5 emojis we get the code or the url of the emoji.

**Comment by gabek** [comment]
Could you file an issue for the second item? When there's multiple issues in a single item I find things get overlooked.

**Comment by gabek** [comment]
The fix should be to not count html tags in the character count.

**Comment by gabek** [comment]
For reference the chat input was rebuilt just this past week, so that's why there's new issues. It's untested.

This issue would be resolved by waiting for #1803 since then we'd have the non-markedup contents to make character count decisions with. Otherwise I'll just strip all tags.

Secondly we have to block adding additional emoji if you're going to hit the limit. That's why you see broken image tags, they get truncated to the max character count.

**Comment by gabek** [comment]
I've done some simplifying. Now it doesn't count custom emoji as a character at all, but I feel like that's fine for the short term. We can improve this with #1803 and tokenize `:emoji:`s, counting each as a certain number of characters.
