### ISSUE TITLE
IndieAuth rejected

### ISSUE THREAD

**Issue by 121GWJolt** [owncast/owncast#3129]
### Share your bug report, feature request, or comment.

Hello! I attempted to sign in to multiple domains with IndieAuth after I configured my domain name to support it and confirmed it worked using both IndieAuth sample login pages.

![image](https://github.com/owncast/owncast/assets/12266333/ffbb4201-7c26-4b89-be97-c4f60744ff8a)

This happens across all Owncast instances that I've tried, including the official one. Both the legacy and the beta versions of the IndieAuth server say I'm all configured and my login is working, so I'm not entirely certain what's going on with that and wonder if it is indicative of a larger bug, or if there really is a bad configuration in my page that the sample login pages on indieauth.com and indielogin.com are ignoring.

Thank you, and have a great day!

**Comment by aaronpk** [comment]
Hi, so it seems there is some terminology confusion. I looked at your site and I see that you have a rel=me link from your site to GitHub so that you're able to log in at IndieLogin.com. However that is not the same as IndieAuth. To support IndieAuth, you need to have an IndieAuth provider linked from your site. That's described in the first section on https://indielogin.com/setup

IndieLogin.com supports indieauth as well as fallback to a few OAuth providers like GitHub when indieauth isn't available. OwnCast supports indieauth but not the fallback providers. Hope this helps! 

<blockquote><img src="/icons/favicon.ico" width="48" align="right"><div><strong><a href="https://indielogin.com/setup">How to Start Using IndieLogin.com</a></strong></div></blockquote>

**Comment by 121GWJolt** [comment]
Ah, I understand now!

I will potentially need to make my own provider in the future when I move to an ASP.NET Core application in the future (unless I am simply blind to the existence of one), but for now I will attempt to use selfauth for this purpose while I still have apache going.

Thank you very much!

**Comment by jedahan** [comment]
I had to follow this, adding a new link to say that indieauth.com was a valid provider, then it worked for me :)

https://indieweb.org/IndieAuth#Set_up_using_IndieAuth.com

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://indieweb.org/IndieAuth#Set_up_using_IndieAuth.com">IndieAuth - IndieWeb</a></strong></div></blockquote>
