### ISSUE TITLE
Flickering chat

### ISSUE THREAD

**Issue by 2TonWaffle** [owncast/owncast#3132]
### Share your bug report, feature request, or comment.

Experienced the flickering chat bug which kept happening for the later half of the stream, accidentally removed the YouTube video so I have the twitch clip of it happening [clip](https://clips.twitch.tv/SuaveHorriblePigBloodTrail-KkUqAfQOgNCo6lZ2)

Viewer was also experiencing the same bug as well.

**Comment by janWilejan** [comment]
I managed to reproduce this locally. It looks like it's caused by the username collapsing. If the same user types multiple messages in a row, the chat is rendered with the username hidden for some messages. This causes the chat to be re-rendered, but this time a different set of messages might have the username hidden, causing another re-render.

Gabe, assign me this issue.

![ChatFlicker1](https://github.com/owncast/owncast/assets/119548498/4b86b4a0-5e38-417b-b449-a9838f94c048)
![ChatFlicker2](https://github.com/owncast/owncast/assets/119548498/0fa304f6-7db5-4c48-b293-eaa00bd826c9)

**Comment by gabek** [comment]
Thanks so much for looking into this, jan!
