### ISSUE TITLE
Slur / Profanity Filter

### ISSUE THREAD

**Issue by janWilejan** [owncast/owncast#3139]
### Share your bug report, feature request, or comment.

To prevent users from coming into chat and writing messages that the streamer obviously doesn't want on their stream, there should be a configurable chat filter.

Filtered messages could be handled in a few ways:
- Replace the offending word with a different word [^1]: for example, osu! replaces "fuck" with "firetruck"
- Mute the user for a period of time, with a customizable message saying "that kind of language isn't allowed here you've been muted for a short while"
- Ban the user permanently, with a customizable message saying "we don't allow slurs on this platform"

Word matching could happen in multiple ways:
- A checkbox for case sensitivity (on by default)
- A checkbox for whether to match diacritics or unicode lookalikes [^1]
- A checkbox for whether to match whole words or parts of words (if you want to block "fuck", you probably want to block words like "fucking"; if you want to block "ass", you probably don't words like "classic" blocked)

The interface should let admins / moderators upload multiple word lists each having its own options for matching settings and response settings.

Should Owncast ship with a default chat filter? I think it should come with a basic filter for English words at least. What kind of words should be in it? Should it be enabled by default?

[^1]: Not necessary for a basic profanity filter, but it could be nice to have

**Comment by gabek** [comment]
I think it's a reasonable feature to have. I'd vote to start simple, however, and simply don't allow messages that match the list to get sent. Then we wouldn't have to have an entire interface for replacing words and such. It also allows somebody who got hit with a false positive to simply retype their message without the offending word.

I don't think we'd ever want to auto-ban somebody based on automated actions, too much room for false positives and it kicking out innocent people. Similarly I don't think we'd want it on by default. We do have a couple default banned chat display names that are built in, but they are names that would never make sense. It's harder to make claims on behalf of others what the filtered words should be. But if it's off by default then it would be fine to ship a few example words that could be easily changed.

I'm thinking a lot about false positives because as far as I've seen, just viewing people's streams over time, there hasn't been a heavy need for filtering chat messages. People say "naughty" words with their friends all the time, and it's fine. If we shipped a filter and turned it on then it would just annoy these people more than help them.

**Comment by janWilejan** [comment]
I agree with you about starting simple. I'm aware that false positives could be a potential issue we need to tackle. 

There was a recent stream where a user was "slinging a few slurs around" in chat and the streamer did not notice. I don't think it's likely that a filter matching the N-Slur or the F-Slur would have many false positives.

I don't think most streamers will care if users say naughty words like "fuck", but some might.

Also, I don't think that any default chat filter that gets shipped should auto-ban. I assume moderators will have the ability to un-ban people if they turn it on. If an Owncast instance ever gets big enough to get "hate raids" the way Twich (used to?) have, I think giving admins an auto-ban option could be a helpful tool.

**Comment by gabek** [comment]
Those are all great points, thanks for sharing your point of view, I wasn't thinking about a lot of that. There are absolutely words that aren't likely to be accidentally filtered and are words that have no place being said.

One feature I'm not sure if anybody uses, but would be helpful in some of these scenarios is the "established chat user" mode that only allows people who have previously been around for some amount of time (I forget how long) to be able to chat. That would stop any hateful raids as well.

**Comment by jprjr** [comment]
Just a cursory search found this library that may be helpful: https://github.com/TwiN/go-away

<blockquote><img src="https://opengraph.githubassets.com/4fab4659acc40c3cefad335036af3df5ac5a434892cbcec39ba2954bb77def0d/TwiN/go-away" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/TwiN/go-away">GitHub - TwiN/go-away: Library for detecting profanities in Go</a></strong></div><div>Library for detecting profanities in Go. Contribute to TwiN/go-away development by creating an account on GitHub.</div></blockquote>

**Comment by jprjr** [comment]
As far as iterating goes, assuming you go with this library -

Iteration 1, use the default settings and have it as an on/off setting.

Next iteration, allow admins to specify profanities, false positives, and false negatives.

Then look into Unicode normalization - the NFKD normalizing mode should convert look-alike characters into their ascii equivalents, and being decomposed makes it easy to filter out combining characters.

Not sure if it makes more sense to go basic -> custom lists -> Unicode normalization or basic -> Unicode normalization -> custom lists.

**Comment by misnina** [comment]
Has there been any update to this that I haven't seen? The lack of slur filtering and free anon chat means Owncast is not a viable solution to pretty much anyone of a marginalized group. The choice of if someone wants to roll with a heavy false positive moderation style should be up to them, but some type of word filter is essential to a chat platform.

**Comment by gabek** [comment]
> Has there been any update to this that I haven't seen?

All work takes place on GitHub, so this is where you'll find updates.
