### ISSUE TITLE
Custom Framerate

### ISSUE THREAD

**Issue by LesTrucsMuches** [owncast/owncast#3178]
### Share your bug report, feature request, or comment.

Is there a way to add a custom framerate other than the ones offered? I would like to add 48fps. but I can't find the option anywhere.

**Comment by gabek** [comment]
You could use the API, as that's a way people have set their own custom values in the past. If 48fps is a common thing, we could add that to the admin, but if it's something that isn't used by anybody else I prefer not to add options that people won't use.

You can find some discussion about using the API to set custom values at: #1462

**Comment by janWilejan** [comment]
If your source stream is 48fps, you can use video passthrough. Otherwise, the only framerate options are the ones in the Framerate slider (50fps is the closest to what you want).

I could add a stop on the slider at 48fps. Or should I add a custom framerate text field?

Can I ask why you want 48fps? Is 50fps not "close enough"?

**Comment by LesTrucsMuches** [comment]
I use 48 because my source is 24 and I double it in obs to have better fluidity. if I use 50fps, sometime there is a little visual glitch. But I will investigate with the API first thank, don't add 48 if I the only to use it.

**Comment by aaronpk** [comment]
If your source frame rate is 24fps, then setting it to 48fps isn't going to give you new video information, it's just showing each of your 24fps frames twice in a row.

It is not surprising that you're seeing a little glitch if you set it to 50fps, because the encoder has to choose 2 of the 24 frames to double up on to stretch it out to 50fps.

**Comment by LesTrucsMuches** [comment]
I know 48fps just doubles every frame, but visually it's smoother. I used the API and it works like a charm to add 48fps to my trancode :)

thank for your help.
