### ISSUE TITLE
Feature Request - Chat user leave event

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3201]
### Share your bug report, feature request, or comment.

Hi there, one thing I'll occasionally run into with my stream is users not realizing another chatter has left.

Granted, being connected doesn't 100% mean they're going to see it - but being disconnected means they absolutely won't see it, right? So that would be a nice-to-have event.

**Comment by gabek** [comment]
It's not something I've heard anybody ask for previously, but I don't see a downside of offering it as an option. Maybe it should be a part of the join setting, "Show join and part messages", as to not add another setting people have to micromanage. 

It would be nice to put some logic around it, though. Sending a message each time somebody simply disconnects doesn't feel right. Like if user X is connected on device A, and then moves to device B, I wouldn't want a leave message when they disconnect from device A because they're still connected elsewhere.

**Comment by jprjr** [comment]
Agree on not showing for every disconnect. Having the leave event generated when they're not connected from any device would make sense to me.

**Comment by janWilejan** [comment]
Maybe the "user has left the chat" messages should be delayed a few seconds in case there's intermittent internet outages or page refreshes as well. We don't want "user has left, has joined, has left, has joined".

Also, if we have an accurate count of chatters we should add that to the viewer info. ":eye: *`v`* | :speech_balloon: *`c`*"

**Comment by gabek** [comment]
I'm totally for delaying the messages, though that might impact the core use case here (knowing the person you're talking to isn't there), but I think being off a few seconds is worth it.

I don't think we should split the chat and viewer counts.  It would be difficult to decide what a "counted chat user" is, anyway. Do chat embeds count? Do webhooks count? The viewer count is what matters, and it's accurate for _most_ scenarios. I'd prefer to address that in #2627. While I don't like adding options like this, I do think having a toggle between "using cdn" and "not using cdn" would mostly address the viewer count in CDN environments. Where it wouldn't help is when people use 3rd party players, and in that case they wouldn't be using chat at all or using the Owncast interface to see the count.

**Comment by jprjr** [comment]
> I'm totally for delaying the messages, though that might impact the core use case here (knowing the person you're talking to isn't there), but I think being off a few seconds is worth it.

I agree - you could probably go say, 5-10 seconds (maybe even higher?). I think that would be long enough to prevent spam from page refreshes, and short enough that it still addresses the use case.

**Comment by glyphscribe** [comment]
Hi, just adding my $0.02 to this -- a chat user leave event would be _very useful_ (for me). I was actually surprised that it wasn't already among the websocket events.

**Context:**
I recently wrote a platform handler for StreamAvatars that adds Owncast support which _mostly_ leans on the websocket data, but it's incomplete and not really in a state to share because of the missing chatter leave event.

Right now I'm listening for joins (and all other meaningful events) via websocket and [hackily] grokking the client table at `api/admin/chat/clients`. In a perfect world I'd like to not have to hand the integration the instance admin password to work.

**Comment by gabek** [comment]
> Right now I'm listening for joins (and all other meaningful events) via websocket

As a heads up, the websocket events aren't guaranteed to be stable for external integrations. There's absolutely nothing stopping you from using it, and you can do whatever you like, but I just waned to make it known that it will change in the future whenever necessary to support frontend updates. 

I would love to support plugins for things like this. Then you wouldn't have to use the websocket (that isn't encouraged anyway) or the webhooks (that is supported, and encouraged, but I realize is a hassle for people). But there's just not enough people involved and time in a day to work on something that only a couple of people would take advantage of. See #1736

Maybe after the backend refactor we can be a step closer to building this functionality, so then you can just tie your code directly into Owncast events. I just hate the idea that you, and maybe a few others, are building really cool things on top of functionality that's guaranteed to change on them in the future and break their projects.

**Comment by glyphscribe** [comment]
@gabek Totally understood; I acknowledge and understand the websockets aren't publicly documented for consumption, at least not in the way that I (and others) are making use of them, and are subject to change. That's a situation I'm OK working around until a more formal solution exists.

... But as long as a similar conversation was happening in this thread, I just thought I'd add some notes :)

**Comment by gabek** [comment]
On it! I love the kind of thing you're doing, so please don't hesitate to reach out with changes or additions that would continue to make it possible for you to build cool stuff. It'd be nice to work to a formalized platform to build more elaborate tools on top of.
