### ISSUE TITLE
Embed heights seem to still be off

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3210]
### Share your bug report, feature request, or comment.

A change was made in #3104 to fix the statusbar not showing on embeds due to an incorrect height. But it seems now it only _kind of_ shows. I'm not sure if the problem is with the embedded content, or if the opengraph tags saying how large the frame should be needs to increased.

Embedded into a Mastodon timeline
![image](https://github.com/owncast/owncast/assets/414923/ee1127d5-ff58-48eb-9c89-0a562ed0830b)

From https://web.batstationrad.io/
![image](https://github.com/owncast/owncast/assets/414923/d29ea175-6361-452a-8d2e-ceb82e0110c5)

**Comment by jprjr** [comment]
It looks like there's a style somewhere overriding the `96vh` on the div that contains the video player - `VideoEmbed_onlineContainer__5XevB` - see screenshot, looks like a media query

![Screenshot_2023-07-25_13-33-12](https://github.com/owncast/owncast/assets/4265148/49d1f87f-2861-409c-aa79-97b5a5b75bdf)

**Comment by jprjr** [comment]
I think this is the culprit:

https://github.com/owncast/owncast/blob/bdd7711c1b2f59b6c614205e39e26f95b1ce0795/web/pages/embed/video/VideoEmbed.module.scss#L5-L7

EDIT: maybe not, I'm unsure.

Second edit: I believe it's the content padding on the status bar - at smaller sizes like this, the top padding (14.24px) exceeds the max-height of 4vh (13.8px) and its pushed out of the iframe.

May be worth changing to a flexbox rather than viewport units?

**Comment by jprjr** [comment]
I *think* these are the CSS changes that will make the video embed do what you want. These are just changes I made client-side using the dev tools:

On the `VideoEmbed` container, set the `display` to `flex` and `flex-direction` to `column`. Set the `height` to `100vh`

On the `OwncastPlayer` container, remove the `width: 100%` (this enforces a minimum height so flex won't shrink it as much as needed). (maybe?) set `margin` to `auto` to re-center, and set `max-width` to `100%`

After those changes here's how the embed appears -

![Screenshot_2023-07-25_14-25-27](https://github.com/owncast/owncast/assets/4265148/3db1a5ae-4c26-4b88-81c6-ea4098f6a7d5)

**Comment by gabek** [comment]
I think I'm misinterpreting something. I'm looking through the video embed CSS and I don't see the classes you're referring to. Is that not what you're talking about?

**Comment by jprjr** [comment]
I'm referring to the elements I see in the "inspect" tab of the browser dev tools. I think these names may correspond to component/module names, I hadn't dug into the code - just tweaking element attributes on-the-fly

**Comment by gabek** [comment]
So I was planning on releasing v0.1.1 tomorrow, and while this fix feels like it's super small, it would be changing core layout CSS of the player everywhere (not just embeds). In theory it should work fine, but it would have no testing, and layout changes often break other things, only is broken on mobile, etc etc. So I'm always super hesitant to make core page layout changes without a lot of testing on multiple screen sizes, platforms, browsers, etc.

It's likely we'll have a v0.1.2 with more fixes soon anyway I'm sure, and this can be included in that.

**Comment by jprjr** [comment]
I think that's a good call, and I'm excited for v0.1.1!

**Comment by janWilejan** [comment]
It looks like the theory is that the player's height is 96vh, and the bar is 4vh. But in practise, the player height is overridden by `@media` and the bar height is overridden by needing to be tall enough to fit its padding. jprjr was definitely on the right track with using flexbox to fix this

**Comment by pjbollinger** [comment]
I can pick up this issue if it helps.

I started to play around with it but I'm wondering does the attached look right and/or match expected behavior? The coloring is my own to demonstrate elements. Red is my video streaming, black is the video element but bars due to mismatch aspect ratio, blue is the status bar, and yellow is the background of the iframe that is not being covered by the video or status bar.

<img width="1666" alt="Screenshot 2023-10-09 at 8 55 44 PM" src="https://github.com/owncast/owncast/assets/5209474/d5392a3e-894f-40ae-941c-7fd776d65b7d">

**Comment by gabek** [comment]
Hey there! Glancing at that, it looks correct.

So I think, as was mentioned above, laying this out with Flexbox is the solution to this embed fix. The problem is, to fix the player embed, it also impacts the non-embedded version in the main web UI.

Some background: In the road to get v0.1.0 out the door, _many_ layout problems and fixes went in. Months of stuff being broken, and then fixing, and that breaking mobile, and fixing mobile, and that breaking desktop, and fixing that, breaking something else, over and over. So I'm afraid at this point to make fundamental layout changes that impact the most important functionality of the page. You can see the first PR attempting to fix this caused issues on mobile.

I know I can't be scared forever to make changes to this, but the idea of the break/fix/break/fix iteration cycle is something I'm really scared of getting into again. Hopefully we have better tests now than we did back then to catch issues, but it's still hard to feel confident after all the issues that had to be resolved to get to where we are.

**Comment by pjbollinger** [comment]
Thanks for the context. I can understand the scariness of CSS. 😆 

Hopefully you'll like the fix I'm about to propose since it doesn't need to touch the styling of the non-embedded components. In fact, we'll be able to remove the concept of being embedded in the main player component `<OwncastPlayer>`, which I think is the "right" way to handle things (quotes because who ever knows how to handle things correctly with CSS).

I think the trickiness is making sure a parent component is responsible for setting the boundary for its children components without telling them what to do exactly. At the same time, making sure the children feel the boundaries set by the parent but take up as much space as they'd like given the boundary. Like in this example, why should `<OwncastPlayer>` care if it's embedded or not?

Thanks for developing a cool project, I hope my contributions will help rather than hinder. 😄
