### ISSUE TITLE
RSS feed for live notifications

### ISSUE THREAD

**Issue by elouin** [owncast/owncast#3305]
### Share your bug report, feature request, or comment.

It would be quite handy to have an RSS feed one can follow to be notified, when the stream goes live(even though that might not be RSSs intentional purpose).

**Comment by gabek** [comment]
RSS isn't a great tool for this because it's not real-time and the model of feed items wouldn't make a lot of sense. Would we keep a history of each time a stream went live and have that show up in a feed reader?  That doesn't sound particularly useful to know you missed a stream an hour ago. 

However, I would like to offer future stream replays and clips as RSS feeds, since that makes a lot more sense.

**Comment by ffaf1** [comment]
> RSS isn't a great tool for this because it's not real-time and the model of feed items wouldn't make a lot of sense. 

I would disagree on this. RSS has a `<ttl>` tag which specifies how long the feed can stay cached before having to refresh ([source](https://www.rssboard.org/rss-specification#ltttlgtSubelementOfLtchannelgt)). A low-enough value would fit the bill.

I follow [this channel](https://tv.aethernaut.eu/#) via my mastodon client, but having an RSS feed would be much more handy to me.

**Comment by gabek** [comment]
To set the ttl value correctly we would have to know, ahead of time, how long the stream is going to be, so it can expire when it's over. And it's not possible to know that.

I apologize, but it's just not the right tool for the job. Building and maintaining a feature that would only be used by a couple people, in ways that it's not built to be used for in the first place, just isn't a worthwhile addition.

But like I mentioned, stream replays and clips, in the future, should have this functionality because then it could be treated like a Podcast, something RSS is good at and is built for. Maybe even _literally_ structure it like a podcast, if clients support an `enclosure` that is HLS.

**Comment by i2** [comment]
> However, I would like to offer future stream replays and clips as RSS feeds, since that makes a lot more sense.

@gabek and others: Apologies for commenting on a closed issue! I was just wondering if this _modified feature_ that you mentioned above can be added to owncast?

As the OwnCast Extension (on Chrome) now says: "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.", this could be the second-best thing possible!

**Comment by gabek** [comment]
Stream replays and clips don't yet exist, but I'm still interested in adding an RSS interface to them when it gets built.
