### ISSUE TITLE
/data folder empty? Where is data being stored?

### ISSUE THREAD

**Issue by mjessa12** [owncast/owncast#3347]
### Share your bug report, feature request, or comment.

My owncast is working perfectly but I wanted to do a backup of the data folder and when I went to it, there was nothing in the folder. 

I deployed owncast thru portainer/docker compose with the following file:

![image](https://github.com/owncast/owncast/assets/72001246/3ebaf3a8-e54f-4399-88df-963f9ce30ca1)

When I go to /home/maysam/docker/owncast - it is empty.  Did I do something wrong during the setup? Like I said, everything is working fine...

**Comment by gabek** [comment]
You might want to shell into your Docker container to help troubleshoot where your `data` directory might be.

As a guess, because the `owncast` binary is in `/app` maybe your `data` directory is `/app/data`? But this is more of a Docker issue. If Owncast is functioning correctly for you, then the `data` directory must exist somewhere.
