### ISSUE TITLE
Owncast is restarting my stream periodically but it is unclear why this happens, and the logs are wiped each time

### ISSUE THREAD

**Issue by philnelson** [owncast/owncast#3370]
I'm running owncast on one of the bigger channels at https://live.retrostrange.com. I'm running the server on a Linode and have been for about 2 years. I send the upstream video from a minipc in my apartment with gigabit internet. It broadcasts 24 hours per day.

Lately owncast has been restarting the feed multiple times per day. You can see this on the go-live notifications on our fediverse account here https://wrestling.social/@rstv@live.retrostrange.com

I've tried debugging by looking at the log files, but owncast.log appears to be wiped clean each time this restart occurs. I'm not sure what to do to dig deeper. This issue seems to have only come up since the update to the latest stable Owncast but I'm not 100% sure on that.

**Comment by gabek** [comment]
Not to be pedantic, but I want to make sure I understand specifics. You say "restarting", could you elaborate? Does that mean the RTMP connection is dropping? Is Owncast restarting? Or the entire machine? Or something else?

As for logs, I'm not sure how you have Owncast running, but if it's under systemd you can access service logs. Here's some documentation: https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

While I'm not aware of any kind of widespread issue, I'd never rule anything out, but I haven't heard anything similar from any other instances, including the ones I run myself.

So if you can elaborate on what the actual issue is, it would at least narrow down the conversation.

<blockquote><img src="https://www.digitalocean.com/_next/static/media/intro-to-cloud.d49bc5f7.jpeg" width="48" align="right"><div><strong><a href="https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs">How To Use Journalctl to View and Manipulate Systemd Logs  | DigitalOcean</a></strong></div><div>Some of the most compelling advantages of systemd are those involved with process and system logging. Using other systems, logs are usually dispersed through… </div></blockquote>

**Comment by rmens** [comment]
I run two 24/7 Owncast channels for a public TV station and am not seeing this problem. There are days when the connection is dropped because the upstream provider isn't too stable but it can run for days.

One simple route to see if this is your upstream or Owncast hard restarting is via the command `systemctl status owncast` (assuming you run Owncast as a service). That should say something like `Active: active (running) since Thu 2023-10-05 11:42:53 CEST; 1 week 5 days ago`
