### ISSUE TITLE
Invalid streaming key

### ISSUE THREAD

**Issue by E8LL4IQuU** [owncast/owncast#3393]
### Share your bug report, feature request, or comment.

Specifying wrong server address, e.g "rtmp://10.132.1.107:1935/liveabcd" in streaming software(i.e. obs) triggers `invalid streaming key; rejecting incoming stream` in logs, as though the key itself is correct. It makes it harder to investigate the problem as obs recommends checking stream key in this situation as well

**Comment by gabek** [comment]
What would you expect Owncast to log out in this case? To Owncast it is an incorrect key, since you passed nothing as the key. I'm not sure optimizing for people making typos generally makes a lot of sense, since there are an infinite number of ways people can type things in wrong. But if there's something relatively straightforward that addresses multiple use cases, maybe it's worth putting in.
