### ISSUE TITLE
Update Next.js static export setting

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3413]
### Share your bug report, feature request, or comment.

`next.config.js` needs to be updated to add `output: export`.

```
The "next export" command has been removed in favor of "output: export" in next.config.js. Learn more: https://nextjs.org/docs/advanced-features/static-html-export

**Comment by wisnuwijo** [comment]
Removing `next export` command should work. For example, if you are using Github Action, you can comment out `next export` line 

<img width="734" alt="Screenshot 2023-11-05 at 13 40 39" src="https://github.com/owncast/owncast/assets/29016859/896a7091-2f27-43ec-9fb3-a6340fe4fb96">

**Comment by yukiyamazaki** [comment]
@gabek 
Hello

I was in the same situation.
However, I was able to solve the problem easily with the following method.
In conclusion, I think it is better to use only "next build" instead of "next build && next export".

### Before
Previously, Static Exports were performed by executing the next export command.

```
// package.json
"export": "next build && next export"
```

### After
Since v13.3, the next export command has been eliminated, and instead, the specification seems to have been changed to specify the output mode in next.config.js, as shown below.

```
//next.config.js

const nextConfig = {
...
  output: 'export', ... 
...
}; } 

```

Static Export functionality can be used by executing the next build command with the output mode set to "export".

More information can be found on the official website below
https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

**Comment by gabek** [comment]
I have it taken care of in https://github.com/owncast/owncast/pull/3404/commits/5089f0dfb2f2169bd7a109e0b80fcd6157d57e90. I just am waiting to merge it in until v0.1.2 is released. Thanks for chiming in, though!
