### ISSUE TITLE
Sanitize Fediverse username

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3424]
### Share your bug report, feature request, or comment.

Apparently we allow people to type whatever they want, creating a mess like the following where somebody put an `@` in their actual username.

We should reject usernames that have special characters in them.

![image](https://github.com/owncast/owncast/assets/414923/616cb123-4813-46d7-be4f-88da56faf8ce)

**Comment by varungujarathi9** [comment]
Hello, I would like to work on this

**Comment by gabek** [comment]
Great! Thanks, @varungujarathi9!

**Comment by jhimanish** [comment]
Hello,
We are a group of 4 students from the University of Toronto. We're currently looking to contribute to an Open-Source project and are looking for our first few issues.

We were wondering if this issue is still available to be worked on. If so, could you please assign this issue to us?
Thanks!

Team members: @jhimanish @EthanZheng11, @AsherHounsell, @TashanManiyalaghan

**Comment by gabek** [comment]
Hi @jhimanish, I believe @varungujarathi9 is still looking at this, but thank you for offering!

**Comment by jhimanish** [comment]
Hello, thank you for letting us know. We'll look at some of the other open issues for contribution!
