### ISSUE TITLE
Replace Twitter social link icon with the stupid 𝕏 one

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3427]
### Share your bug report, feature request, or comment.

I guess it has to happen at some point.

**Comment by averheecke-scottlogic** [comment]
I would like to work on this task as my first issue :)

**Comment by gabek** [comment]
Awesome, thanks @averheecke-scottlogic!

**Comment by jhimanish** [comment]
Hello,
We are a group of 4 students from the University of Toronto. We're currently looking to contribute to an Open-Source project and are looking for our first few issues.

We were wondering if this issue is still available to be worked on. If so, could you please assign this issue to us?
Thanks!

Team members: @jhimanish @EthanZheng11, @AsherHounsell, @TashanManiyalaghan

**Comment by gabek** [comment]
Hey @averheecke-scottlogic, are you still looking at this?

**Comment by gabek** [comment]
@jhimanish I went ahead and assigned you since I didn't hear back if it was still being worked on. Thank you!
