### ISSUE TITLE
Integration of WebRTC via broadcast-box?

### ISSUE THREAD

**Issue by zaggynl** [owncast/owncast#3429]
### Share your bug report, feature request, or comment.

OBS now includes WebRTC/WHIP support in version 30:

https://news.ycombinator.com/item?id=36273075
https://github.com/Glimesh/broadcast-box

This should allow for very low latency streaming.

**Comment by rmens** [comment]
I would say SRT is far more preferable. It's an already very robust broadcast grade protocol that can have sub second latency too https://github.com/owncast/owncast/issues/980

**Comment by gabek** [comment]
Latency will always exist with HLS.

**Comment by ca1f** [comment]
> Latency will always exist with HLS.

Would it then be of interest to support [Media over QUIC](https://quic.video/) as an alternative transport as a secondary option to HLS for clients that support it?

**Comment by gabek** [comment]
Owncast uses HLS because it's universally supported as a standard. You can point any player to an Owncast server and watch the stream, that's a part of the value. With other, non-standard, options, this isn't possible.

**Comment by ca1f** [comment]
I saw the importance with backwards compatibility and that's also important to me, that's why I specifically tried to phrase my suggestion as a secondary solution to the widely supported option.

It would be really nice to offer a low latency stream to those who use software that allows for it and still be compatible with the wide spectrum of different users out there at the same time. Sometimes a low latency stream is crucial for interacting with viewers. But maybe that's just not feasible if it costs too much effort to implement and support.

**Comment by gabek** [comment]
I guess it makes sense to clarify a bit here. I think the original suggestion was for WebRTC ingest to reduce latency. Since video ingest accounts for a very small amount of latency, I wanted to mention that it wouldn't help much.

That being said, I'd be much more interested in supporting different ingest options than different playback options since ingest doesn't impact the viewer experience, and doesn't require specialized, non-standard players. It only impacts the streamer. But, like I said, it probably won't help latency much.

**Comment by cyprus1spirit** [comment]
I think there is a bit of confusion here and gabek knows it better than us. The well known WebRTC is a real-time communication API using a direct peer-to-peer connection and is not known to be used in stream contribution. I understand that gabek was referring to "WHIP", the WebRTC HTTP Ingest Protocol, developed by http://millicast.com/ to solve the biggest pain point with adopting WebRTC as a contribution protocol.

<blockquote><img src="https://dolby.io/wp-content/uploads/2022/08/dolby.io-real-time-streaming-social-share.png" width="48" align="right"><div><img src="https://dolby.io/wp-content/uploads/2021/07/cropped-DolbyIO-favicon-1-192x192.png" height="14"> Dolby.io</div><div><strong><a href="https://dolby.io/products/real-time-streaming/">Real-time Streaming</a></strong></div><div>Dolby Millicast Real-time streaming for massive global audiences Dolby Millicast delivers lightning fast, broadcast quality, real-time streaming to</div></blockquote>

**Comment by Sean-Der** [comment]
Happy to answer any questions about WebRTC + Broadcasting (I work on OBS WebRTC and Broadcast Box). Responding to some points in the thread, would love to discuss more though :)

* Publish+Playback is standardized via WebRTC. Using OBS/GStreamer/Larix etc... you can publish+pull from a URL

* WebRTC has a bunch of things that will make it easier to self host. One big thing is Simulcast. Clients can publish low/med/high feeds so servers don't have to do transcodes. Makes it way easier (and cheaper) to run a server!

* I care/believe in WebRTC because it is an Open Standard and has community governance. I am not satisfied with protocols that companies just throw over the wall. WebRTC is great because you can go to W3C/IETF and discuss it.

* A 100% pure Go implementation of WebRTC exists https://github.com/pion/webrtc

* I would love to contribute/add it myself if that is welcome @gabek

**Comment by gabek** [comment]
Hi there, thanks for chiming in.

WebRTC seems like a different solution to a different problem. Owncast exists to do server-side transcoding and distribute video via standard web infrastructure. I can understand why somebody might not want that, but in that case, Owncast wouldn't be what you're looking for. The fact that you can leverage CDNs, object storage providers and treat video like you would any other web asset is a true benefit that Owncast users appreciate and rely on.

HLS allows playback on a vast number of video players across many platforms, it's a standard that has been standardized. While WebRTC might be a documented standard, it's not standardized across platforms or players. How would you play a WebRTC stream on a Roku?

WebRTC also would not be compatible with future replay functionality (that has already been built, but not integrated yet).

In general, it's just a very different thing that isn't compatible with what Owncast is doing. But I appreciate your passion for WebRTC!

**Comment by Sean-Der** [comment]
Thanks for the response @gabek! This is your project, I am not saying you are wrong about anything. This is just my opinion/how I feel about the broadcasting space.

> WebRTC seems like a different solution to a different problem.

I don't believe so! Owncast cares about solving these right?

* Live video + Chat
* Using existing tools and protocols/not locking in users 
* Open Source and Self-hosted
* Easy to use 

For some users WebRTC will get them closer to those goals.

* Broadcast from the browser. They don't need to install additional tools/understand RTMP
* Chat+Video will be more in-sync. The latency of RTMP+HLS makes it hard to have interactive experiences
* More affordable. If I can use my local GPU to generate transcodes why pay a hosting provider?

>  Owncast exists to do server-side transcoding

I don't think 'server-side transcoding' is best for ALL use Owncast users. Client-side transcoding is a thing with RTMP now also see [Enhanced Broadcasting](https://help.twitch.tv/s/article/multiple-encodes?language=en_US), in some cases it makes more sense.

> distribute video via standard web infrastructure

Agree! WebRTC is standard web infrastructure. If Owncast supports WHIP/WHEP I could just replicate it to something like [Cloudflare Stream](https://developers.cloudflare.com/stream/webrtc-beta/) or any other WebRTC provider (Millicast, IVS etc..)

> How would you play a WebRTC stream on a Roku?

Roku doesn't support WHEP yet. I hope it can someday! WebRTC playback exists in [GStreamer](https://gstreamer.freedesktop.org/documentation/webrtchttp/whepsrc.html) and [Eyevinn](https://github.com/Eyevinn/webrtc-player)'s player. Just googling around it looks like [video.js](https://dolby.io/blog/building-a-whep-viewer-with-video-js/) also not upstreamed though.

> WebRTC also would not be compatible with future replay functionality
I can't speak to that. WebRTC is server driven (instead of client). So when I do replay stuff I am usually having the server re-send old video buffers. You can see an example with [rtwatch](https://github.com/pion/rtwatch)

----

I don't think WebRTC can/should replace everything. If you want to serve a pre-recorded video cheaply and have a larger latency budget HLS and a CDN is better fit. I just see gaps in the broadcasting space that can be filled today with WebRTC. 
If WebRTC costs more then it adds to Owncast I 100% agree that it shouldn't be added.

**Comment by rmens** [comment]
Again. I don’t see anything of value that SRT can’t do.

**Comment by Sean-Der** [comment]
@rmens SRT can’t broadcast (or watch) from browser.

Does SRT (MPEG-TS) have Simulcast? I don’t know the space.

**Comment by rmens** [comment]
@Sean-Der Clearly our perspective on what’s of value differs a lot.

**Comment by Sean-Der** [comment]
@rmens What is of value to you? I think those two things are valuable. Would love to know the things I am missing!

**Comment by rmens** [comment]
@Sean-Der I hold the belief that it's about making choices, rather than merely having options. Owncast is a small project excels in a few key areas and did that by making some necessary choices. 

Some featured that SRT and WebRTC bring are beneficial to existing broadcasters like myself. These include:

- Lower latency (SRT does this pretty well)
- More robust connection (SRT does this pretty well)

Regarding transcoding on a local GPU, my opinion is neutral. Cloud services are particularly adept at handling such tasks, offering the capacity and infrastructure to ensure consistent performance. They are typically more capable than, say, my Mac, which also does tasks such as photo categorization using the GPU. If it were to do that while also transcoding, the results could be problematic. Additionally, I use a small Blackmagic encoder for its energy efficiency. Operating a GPU continuously would incur significant costs, especially with the current high energy prices in my country.

While Owncast is not my project, I am among its larger broadcasters and know its scope and resources pretty well. Onboarding lots of new users through more user-friendly tools would be ideal. However, it's important to acknowledge that even platforms like Twitch require an encoder such as OBS, and Owncast is a considerably smaller project. The majority of Owncast users either already have a following or have the technical knowledge to manage a stream.

In my view, SRT could introduce two significant improvements without major changes to Owncast's structure. Such alterations could impact future developments, like recording capabilities.

Nonetheless, these are just my perspectives on the broadcasting landscape.

**Comment by Sean-Der** [comment]
> However, it's important to acknowledge that even platforms like Twitch require an encoder such as OBS

Twitch allows broadcasting from the browser. [Stream Together](https://help.twitch.tv/s/article/guest-star?language=en_US) is what I worked on at Twitch. My hope was that it would bring on a whole new group of broadcasters that couldn't stream before!

[LiveSpace](https://about.live.space/old-home?lng=en) is another that allows it.

> without major changes to Owncast's structure

The impact for WebRTC and SRT should be the same. I would just do WebRTC ingestion. In the same way you have to process the `mpegts` coming from SRT we would do the same for WebRTC. I would keep the entire code base the same, just also allow WebRTC in and have it use the same code paths that RTMP uses after depacketization. 

----

Totally agree on `choices vs options`. I don't want to negatively impact the project.

**Comment by aaronpk** [comment]
Just to be clear, you're talking about WebRTC ingestion only, not changing the frontend player to distribute the video via WebRTC? That sounds like a much smaller scope change in that case.

**Comment by Sean-Der** [comment]
@aaronpk yea!

Whatever is best for the project/users I am happy to implement. 

When I respond originally I thought Ingestion and Playback was what people wanted. If people don’t need the latency decrease on the viewer side I don’t see any other benefit.

**Comment by gabek** [comment]
Oh I wasn't thinking ingestion only, that absolutely is different in my mind. There would be no administration overhead required where somebody using Owncast would have to understand the "correct" choice between RTMP and WebRTC, something I think could be confusing, running a live streaming server can be confusing enough on its own for new people. This is the same opinion I had about maybe adding SRT at some point. You can use it if you'd like, if not, it wouldn't get in the way or add complexity for the users. Just additional maintenance for the codebase.

Would you still require the overhead of additional ICE and STUN servers for ingest, like you would for playback?

**Comment by Sean-Der** [comment]
> Would you still require the overhead of additional ICE and STUN servers for ingest, like you would for playback?

Nope! ICE/STUN servers are only needed if you are doing P2P and need NAT Traversal. Since Owncast will be running on a directly addressable host it is much easier.

You can use WebRTC via UDP or TCP (via ICE-TCP) https://github.com/pion/webrtc/tree/master/examples/ice-tcp

**Comment by Sean-Der** [comment]
I would love to implement this! Can I open a PR for this?

**Comment by gabek** [comment]
I'd love to chat a bit more, just because this is a huge change.

What would the long term maintenance cost to this be? I know nothing about WebRTC, and to be honest, it's not something I've ever really cared to learn much about since it did not have any obvious overlap with Owncast functionality. So I do fear that something like this would go in, two people would be using it, something would go wrong, and I'd have to become a WebRTC expert overnight to try to troubleshoot it to support a barely used feature and I'd just want to remove it.

Also, the current Owncast infrastructure assumes only one ingest option. So some major refactoring around the video pipeline would have to take place to support this. Discussion around how that would/should work should happen before throwing a PR together.

There are currently plans (that are in the works) for a backend refactor/cleanup. Much of the Owncast backend code is how it was when it was first written, and more stuff was just added as time went on. No true architecture for the project ever took form. So before I felt comfortable building any of the next large features in the roadmap, I wanted to go through this, and position the backend in a better place to be worked on.

This will take a while, however, as it's likely going to be one service and subsystem at a time instead of the one huge change like I previously thought. None of this is changing how anything works, just finally adding structure, data repositories, injected dependencies instead of globals, etc etc.

This is to say, adding another video ingest would be easier after that work is done.

**Comment by rmens** [comment]
Here's my obligatory mention of SRT and https://github.com/owncast/owncast/issues/980 every time this ticket comes alive.

**Comment by Sean-Der** [comment]
@gabek Where is the best place to have this discussion? I would love to do a intro call/talk the details out sync I think it will help a lot. I have a scheduling setup https://siobud.com/meeting

Also happy to talk on IRC/Discord! Whatever you prefer

<blockquote><div><strong><a href="https://siobud.com/meeting">Sean Calendar</a></strong></div></blockquote>

**Comment by gabek** [comment]
> Here's my obligatory mention of SRT and https://github.com/owncast/owncast/issues/980 every time this ticket comes alive.

The above message applies the same to SRT :). But this does demonstrate a concern of a slippery slope. If one is added, then why not add another? And then I should learn about SRT as well and maintain that additional codebase. The next request will be HLS ingest, and that would be the fourth. I think you guys see where I'm coming from.

Everyone thinks their favorite tech stack is the exception, and the other ones aren't needed, but theirs would be super useful to everyone. But the reality of the situation is right now the single ingest works for everyone, even if it's not the most optimal option that has ever existed, it is the industry standard. When another gets added, it's all over for me and my maintenance burden will grow exponentially. 

It's sometimes difficult to remember, since it's been a while. But a lot of the initial challenge in the earliest days of Owncast was with RTMP ingest. There had to be so much testing with so many different people with so many different pieces of software. At first, only OBS worked, but software X didn't, so I'd have to figure out what was up with software X. And then software Y didn't work. So I'd figure that out. And software Z. And a GoPro. And some other random hardware camera. Eventually, over time, it all seemed to work and these problems don't occur anymore.

That's not something I look forward to again.

**Comment by Sean-Der** [comment]
> Everyone thinks their favorite tech stack is the exception.

I agree. Everyone has biases. I am just trying to solve the singular problem of 'Users want to broadcast from a web browser', it reduces the barrier of entry. Having to setup OBS etc... excludes a large amount of users.

I am not suggesting WebRTC because I want to write more WebRTC code. I see a immediate benefit for users. 

>  single ingest works for everyone, even if it's not the most optimal option that has ever existed, it is the industry standard

Single ingest doesn't work for everyone. Users on cellular/don't have the internet coverage affluent countries aren't being served well by RTMP/TCP.

RTMP is an industry standard. I personally feel responsible for pushing the industry forward. I don't like that a patent encumbered (and now abandoned) protocol is keeping us on old codecs and doesn't enable people to have real-time broadcasts. I am not happy with the status quo, we can do better!

**Comment by gabek** [comment]
I think it makes sense to clarify who this feature would be for.

It does seem like broadcasting from a web browser might be the killer feature of WebRTC. But I would argue somebody who's running Owncast is not having problems setting up OBS and is not looking to broadcast from a web browser, that they have a system in place they want to use. This would be clearly different if we were talking about Jitsi or Zoom or if Owncast was a service (Like Twitch or YouTube), not a server.

If we are talking about WebRTC helping more "normal people" be able to stream with fewer dependencies and get running easier without broadcasting software/hardware, or something like SRT becoming more of a professional standard for broadcasters, it does feel like Owncast would benefit more from the latter given what Owncast is targeted at and currently used for.

**Comment by Sean-Der** [comment]
>  I would argue somebody who's running Owncast is not having problems setting up OBS and is not looking to broadcast from a web browser

Why not make it more accessible if we can? Do you see users setting up Owncast for friends/family/teams? Or do you think that only the installer of Owncast will be using it?

> SRT becoming more of a professional standard for broadcasters

I would rather just talk about the positives of WebRTC and not do pros/cons. This is my take though.

SRT and WebRTC are fundamentally the same. They send media over UDP and use features like Retranmissions and Forward Error Correction. I am using/advocating for WebRTC because it is an Open Standard (IETF/W3C) and does not have corporate ownership. WebRTC is like Linux  (compared to propietary Unixes). It might not have the acceleration that comes from corporate backing in the short term. It will continue on no matter what corporate backing comes and goes though. 

-----

I don't want to use this thread to badger you on this! I am passionate about this (created Pion the Go library owncast will be using) and created WebRTC support in OBS. I am willing to write all the code and explain it and the concepts around WebRTC. If/when you are interested I am always available.

**Comment by gabek** [comment]
> I don't want to use this thread to badger you on this!

No, that's absolutely not happening. I just want to be informed. I don't pretend to know everything, and something that I might not understand, or think that nobody would use, might actually be very popular and helpful for a lot of people. But usually that happens when multiple people chime in over some amount of time saying the same thing, and it helps me understand that a specific group of users of Owncast, or a use case, would benefit more than I thought.

> I would rather just talk about the positives of WebRTC and not do pros/cons. This is my take though.

Completely understood.

> Why not make it more accessible if we can? Do you see users setting up Owncast for friends/family/teams? Or do you think that only the installer of Owncast will be using it?

I rarely see that type of setup. It happens, definitely, and that use case is supported, but more often than not, I've seen instead of sharing, people just end setting up their own server to have control and flexibility instead. But I also have visibility into very few Owncast instances. I only know about what's in the directory. So if people are using Owncast for live vlogging and just want to spin up a web page and hit stream, but all those servers are private, I wouldn't know about them.

The most successful uses of Owncast are primarily organizations or companies that have a livestreaming need, and they have their broadcasting pipeline setup that is built to fulfill that need. Often with dedicated hardware. We certainly see a lot of the hobbiest "gamer" style streams, definitely, but the people getting the most value out of Owncast are those who have a true livestreaming requirement and use Owncast to fulfill it (conferences, events, broadcast of offline venues such as churches, concerts, weddings and other misc broadcast media).

I was thinking about the people who use Owncast to livestream their podcast recordings, and maybe that's an example where they might just want to press stream and not have to set anything up. But even in that case they always have custom graphics, and transitions, embedded scenes, lower thirds with their names on them, etc.

Because Owncast is built to be single-user software, I think it's successful in what it's set out to be. Single users set it up and use it. And other people get turned on to it from those streams, and set their own up instead of sharing a server.

It's very possible I'm being overly conservative, and it's time to open up Owncast to a couple more ingest options. Or at least give them a shot. Many things have been pulled from Owncast after it seems like nobody used them or wasn't worth the effort to keep it in. And given that this would be purely an option from the broadcasting side, without additional customization or complexity required in the admin, it can be ignored by the streamer if they don't use it and not get in the way. So maybe it's worth trying. Especially since you're willing to give it a go. There's also a benefit of having a knowledgeable set of eyes touch the video pipeline, and that's always a good thing.

And I feel the same about SRT, except I'm on my own with that one.

**Comment by Sean-Der** [comment]
I personally believe it is a chicken and egg problem. Owncast isn't being used by 'just want to press stream' users because they can not do it.

I don't think users even understand what is possible! We have been so conditioned to believe we have to setup a broadcast tool and it is 1:1 with a few seconds of latency.

I understand the concerns about maintaining things long term. I am in the same position with https://github.com/pion/webrtc. It is frustrating when I get code thrown over the wall without tests and the author doesn't stay. I don't want to do that with owncast.

Whatever you think is best I am happy to do. I can build a prototype (not offended if you do not merge it!), we can do a short video call and go through fine details or I can just leave it and you can think about it some more! No urgency on my side. I am passionate about the problem, but I don't want to force things/make you uncomfortable. 

<blockquote><img src="https://opengraph.githubassets.com/f3538cf36ea6a4d3da6b1e0404aba756f0553a5914a3e21325a7e3ad214878f9/pion/webrtc" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pion/webrtc">GitHub - pion/webrtc: Pure Go implementation of the WebRTC API</a></strong></div><div>Pure Go implementation of the WebRTC API. Contribute to pion/webrtc development by creating an account on GitHub.</div></blockquote>

**Comment by crovaxon** [comment]
Please feel free to disregard my post and even remove it if participants feel that it does not add value to the discussion or might incite unproductive posts. I am not posting with the goal to disrupt, just would love to voice my thoughts.

And I absolutely understand if the development team is not considering Owncast to be targeted at users like me. For me that is just a "that's how it is" thing then, so I am not posting with the aim to criticize. I am one of those privately hosting users, I don't plan to expose myself to a wide viewership, just to my friends. But if awareness of people like me might be served by me posting, here I go. ;)

I would love to point out that I have disregarded Owncast because I am precisely looking for an as low latency as it can get streaming option that ideally is easy to serve to others and could replace my usage of Discord streaming (which is WebRTC based AFAIK and thus crazy fast). No specific reason other than that I like selfhosting all the things I can to stay independent and in control. I have 100 Mbit/s upstream fiber with a nice ping time and hoped to make more use of it than I already do with my current server infrastructure.

In all other aspects (easy to configure and host on my server, easy to stream towards via OBS, easy for people to consume my stream via web browser), Owncast was really good and I have not found anything comparable in that department. But my top priority is the latency as I want to directly engage with my handful of friends via voice chat as they watch and comment or react to my gameplay.

The closest other project that would have resulted in a basic web page for my viewers to consume my stream while being low latency is/was Project Lightspeed but that one is based on the abandoned FTL protocol and I did not manage to host that one successfully and the project itself also seems abandoned now. My questions for help did not gain any traction at least.

I haven't found anything else that seems "easy enough" to set up for a tech affine user like me, or at least a user that would love the low effort solution vs having to tinker something myself. 😁 

So for my specific use case, Owncast gaining the ability to serve as low latency as can be would be incredible and I'd happily return to using it. Hoping for this change is why I still have my docker container with Owncast prepped and not removed and a subdomain ready to go for it. ;)

**Comment by gabek** [comment]
@crovaxon I'm afraid the above thread won't be much help to you. The discussion is for WebRTC ingest, and that doesn't sound like what you're looking for.

In general, Owncast's primary goal is to be a general purpose video server that is highly compatible with most players, and the focus isn't to target the space that video conferencing software like Discord, Jitsi, or Zoom occupies. But I appreciate the kind words, and I'm sorry it's not exactly what you're looking for.

**Comment by Sean-Der** [comment]
Hi @crovaxon have you looked at https://github.com/glimesh/broadcast-box yet? I am the author of OBS+WebRTC and that is the reference server

Low latency broadcasting is going to bring on the next generation of users. I see it in APAC already. The connection you get with your audience I think will replace the old way people thought about things 

but try it out! I also hope to get WHIP support in Discord itself. I have a meeting with them mid Aug

<blockquote><img src="https://opengraph.githubassets.com/34b2d296cbd8d78f65b0f7f732ef26a97a468554ab8a8b019f2f6557248f1a50/Glimesh/broadcast-box" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Glimesh/broadcast-box">GitHub - Glimesh/broadcast-box: A broadcast, in a box.</a></strong></div><div>A broadcast, in a box. . Contribute to Glimesh/broadcast-box development by creating an account on GitHub.</div></blockquote>

**Comment by nico198x** [comment]
I don't know where discussions on this have gone since July, but as a user I'd enjoy this feature.

Lower latency, freedom in my options on how to stream, AV1, these all sound like good things to me. I'm just a layman, however.

Thanks for all you do!
