### ISSUE TITLE
[Security] GitHub Security Lab (GHSL) Vulnerability Report, Owncast: GHSL-2023-261

### ISSUE THREAD

**Issue by Kwstubbs** [owncast/owncast#3472]
GitHub Security  Lab has found a security vulnerability in owncast. Please let us know the best point of contact for reporting security issues. If you don't currently have one, we recommend enabling [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

Kevin

**Comment by gabek** [comment]
Hi, Kevin. I wish we had a central place to manage these kinds of things, but I haven't been able to find a solution, so emailing me is about the best option right now: gabek@real-ity.com

For reference, I prefer not to use the GitHub security management interface because even after security issues are resolved and/or closed, it shows on the "Security" tab an open security issue indefinitely, making it look like the project never addressed it. To not make the project seem like we have a ton of open security issues, when it's not true, I won't use GitHub for this particular use case.

**Comment by Kwstubbs** [comment]
@gabek Understood. I will offer this suggestion to the appropriate team. I will email you the report.
