### ISSUE TITLE
When embedding Owncast chat via iframe the page jumps to where the iframe is

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#3500]
### Share your bug report, feature request, or comment.

Hello.
My Englisch ist not Good. 

If you add the chat to your own website, the website always scrolls down to where the text input field is. 2 videos show this here. If I leave out the chat and only have the video player, there is no problem.  So our users don't find the login area because they don't expect to scroll up. That's what you do for downwards.

 Text error? it is deepl translator :-)
 
 https://www.youtube.com/shorts/m-6CIvgTFcY?feature=share
 
Post for Owncast v0.1.2

**Comment by gabek** [comment]
I don't even know how this is possible, since iframes should be sandboxed. A browser window should not be impacted by the content of what is in the iframe. And even if it were, I don't know what is in the iframe that is making it do this. Very odd.

Reproducible here:

https://owncast.online/docs/embed/

![image](https://github.com/owncast/owncast/assets/414923/cb0852dc-9811-4aee-afe5-761bd5d8daea)

**Comment by gabek** [comment]
Doing a quick search online, it seems to be a really common problem, but I've yet to see a solution for it.

**Comment by DarkFalc0n** [comment]
@gabek I can look into this

**Comment by gabek** [comment]
That would be awesome, thanks so much @DarkFalc0n!
