### ISSUE TITLE
Support NDI streams

### ISSUE THREAD

**Issue by pinpox** [owncast/owncast#3514]
### Share your bug report, feature request, or comment.

I would like to stream NDI streams on owncast. NDI is already supported in OBS, Twitch, Skype and other applications and allows for professional-grade video and audio streams. 

The SDK is free, further details and discussion can be found here: https://github.com/jitsi/jitsi-meet-electron/issues/226

**Comment by aaronpk** [comment]
It does not make sense for a livestream player like Owncast to implement NDI. NDI is for video ingestion at the time of creating a livestream, but doesn't make sense to use it to broadcast directly to viewers. You should take your NDI sources into a video mixer like OBS or a hardware switcher that has NDI support and have that streaming encoder push to Owncast instead.

For example Skype can output NDI feeds for individual participants, which would then be brought in to a video switcher to choose which participant is visible on the actual livestream.

In addition, while the NDI SDK is free, the protocol is entirely proprietary and requires royalty payments to use in hardware devices. Cameras and encoders that support NDI will typically have an extra fee associated with NDI support because of the fees the manufacturers are required to pay to NewTek.

**Comment by gabek** [comment]
Thanks for some additional details, Aaron! The only time I've only time I've used NDI for anything is to get video output from Pioneer DJ Rekordbox into OBS. It does work great for that kind of thing, but I agree, it doesn't sound like the right tool for the job anywhere in the Owncast pipeline.

Thanks for chiming in, though, @pinpox!

**Comment by pinpox** [comment]
Fair enough, thanks for clarifying! I thought owncast would have been the tool to ingest NDI and display it as stream, but understand there should be something in between mixing it. Do you by any chance know of a tool/software that can be used in conjunction with owncast to proxy NDI streams to owncast?  I know I could use OBS for that but was looking for something headless that can be deployed alongside owncast on my server.

**Comment by gabek** [comment]
I feel like the answer is always "ffmpeg", but in this case, there appears to be no binaries of ffmpeg with NDI support built in, you have to build it yourself. My guess because of the above, while the SDK is free (as in beer), you're probably not allowed to freely distribute it without a license.

**Comment by aaronpk** [comment]
[ffmpeg and NewTek got in a big fight](https://trac.ffmpeg.org/ticket/7589) a few years ago. NewTek initially distributed a binary of ffmpeg with NDI built in, but that goes against the licensing terms of ffmpeg since they weren't making the source code of what they were distributing available.

@pinpox another option is a hardware device, although that is going to cost you a bit. For example the [OSEE GoStream Deck](https://osee-tech.com/products/gostream-deck) can take an NDI video feed in and stream it out via RTMP. There's also the [Kiloview MG300](https://www.kiloview.com/en/video-gateway/) which can convert video between many different formats and platforms.

But in your case I would probably just stick to OBS.
