### ISSUE TITLE
Feature request: put thumbnail and master m3u8 file on object storage too

### ISSUE THREAD

**Issue by rmens** [owncast/owncast#3537]
### Share your bug report, feature request, or comment.

I'm thinking about putting my Owncast instances fully behind a firewall and only using object storage to serve video. Right now, what's missing for this setup is the main m3u8 file and the thumbnail.

This plan might not fit with what Owncast is usually used for. Honestly, I mainly use it as flexible transcoder and to serve streams for my own front-end. I don't use the Owncast front-end or chat at all.

I thought it might be good to ask for this as a new feature. But I get it if this isn't how it's supposed to be used, and it's my job to figure out how to make it work.

**Comment by gabek** [comment]
While putting the master playlist on object storage is possible, it would break basic playback.  If somebody opens https://your.stream in a player, it would return a 404 because there's nothing there to play. Currently, we need the master playlist on the server to reference the media playlists so it knows what to play.

A redirect might be possible, but that would feel hacky, and I wouldn't feel comfortable that every player would respect it. 

As for the thumbnail, a lot of tooling and extensions expect the thumbnail to live at that location on every Owncast server, and again it would have to be a redirect to try to work around that.

**Comment by rmens** [comment]
That doesn't sound feasible. I'll close this. Thanks!
