### ISSUE TITLE
Multiuser Instances 

### ISSUE THREAD

**Issue by SamuDifferent** [owncast/owncast#3541]
### Share your bug report, feature request, or comment.

Would it be possible to add a feature, so that some people could host their own servers that run 24/7, that other users could use too. Kinda similar to the way peertube does it. I believe, that this 
1.  Would make it easier for non-power users to stream.
2.  Would give the server operators the possibility to create their own iteration of the directory website.
3.  Would open up the possibility for different Instance-Policies (SFW/NSFW; Political/Non-Political;...etc. )

**Comment by gabek** [comment]
Hi there, thanks for chiming in.

Owncast is specifically built for individuals, as mentioned in our [product definition](https://github.com/owncast/owncast/blob/develop/docs/product-definition.md). Much of what people love about Owncast is because of this design decision. Owncast would be a very different piece of software otherwise.

As for directories, there are plans to allow people to have their own style of directory. It's in our [roadmap](https://owncast.online/roadmap/) as "federated instance follows", but it might take a while to get to. But as it stands, there's nothing stopping people from building a site that links to other Owncast servers. See [ownroll](https://codeberg.org/yarmo/ownroll) as an example.

You can still run as many Owncast servers as you like, and each server has its own policies because it is your server, and you decide what it is used for.

I hope you understand. Some software is built for building service providers. Some software is for people. Owncast is for people.
