### ISSUE TITLE
No chat notifications for Rebased's / Pleroma's quoted_id statuses

### ISSUE THREAD

**Issue by tassoman** [owncast/owncast#3542]
### Share your bug report, feature request, or comment.

When owncast actor gets quoted, the status goes inside `quote_id` attribute of [Pleroma's quoting status ](https://api.pleroma.social/#operation/StatusController.create). The activity is ignored in chat. No notifications.

**Comment by tassoman** [comment]
I guess also [reaction](https://api.pleroma.social/#operation/EmojiReactionController.create) notification are missing, maybe?

**Comment by gabek** [comment]
You're making it sound like these are bugs, but I'm not sure I would agree. A bug would assume it's not functioning as designed. As far as I'm aware, Owncast's Fediverse functionality is working as designed. 

I don't know what a `quote` in Pleroma is, and I'm a Pleroma user. Please add some detail about what you believe is not working.

As for reaction support, Owncast has no reaction support, because it has no reaction support. I don't plan on adding it.

**Comment by tassoman** [comment]
Hello there, thanks for your fast feedback.  
If it's bug or feature, it depends by Rebased/Pleroma/Akkoma kind of integration. If would be a complete ActivityPub actions integration, it's correct to keep in mind they expose a more wide range of interactions.

This Issue address to in page chat events popping up when a federated account promotes a post from Owncast actor.  
If happens to miss reaction or quoting, while in chat, notification are missing and stremer can't have optimal feedback about the spreading of their live transmission.

It's just for adding promotion. I'd say the same should happen while Misskey events are triggered, but can be deal in a different issue.

`quote_id` attribute, as said before and noted in pleroma's API documentation, is the reference to quoted status (owncast action)

**Comment by gabek** [comment]
Just because you can do something doesn't mean you necessarily should. In this case, Owncast specifically limits inbound actions to things that do not support free-form feedback. While the obvious example of this is somebody responding with "this stream sucks" and that showing up in the chat, this would be no different from somebody reacting with an emoji of somebody vomiting. This is why this has never been supported and have no plans to be supported. Nothing positive would come from this, it would not help to spread somebody's stream, and only open an avenue for negativity and harassment.
