### ISSUE TITLE
Any stream I watch buffers every 5 seconds

### ISSUE THREAD

**Issue by pres146** [owncast/owncast#3660]
### Share your bug report, feature request, or comment.

Any stream I watch buffers every 5 seconds. I am the only one who watches the stream with this issue that has been ongoing since December. This is also the only platform I experience this issue on. Nothing seems to fix it. What should I do?

**Comment by gabek** [comment]
Unfortunately, I don't know if I'm going to have an answer for you. Owncast isn't a platform, it's server software, so there is no central set of instances running the servers that can troubleshoot for you.

If there is something specific about your environment, then I encourage you to do some basic troubleshooting to find the core issue with your playback. Try different things, look for more information. Does it happen on all players or just the web? What errors are you seeing?

Maybe the people running the servers you're trying to watch can help troubleshoot with you: https://owncast.online/troubleshoot/

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/troubleshoot/">Troubleshoot Common Problems</a></strong></div><div>Find solutions to common issues.</div></blockquote>

**Comment by pres146** [comment]
> Unfortunately, I don't know if I'm going to have an answer for you. Owncast isn't a platform, it's server software, so there is no central set of instances running the servers that can troubleshoot for you.
> 
> If there is something specific about your environment, then I encourage you to do some basic troubleshooting to find the core issue with your playback. Try different things, look for more information. Does it happen on all players or just the web? What errors are you seeing?
> 
> Maybe the people running the servers you're trying to watch can help troubleshoot with you: https://owncast.online/troubleshoot/
> 
> > <img alt="" width="48" src="/images/owncast-logo-1000x1000.png"><img alt="" height="14" src="https://camo.githubusercontent.com/cb738fa49dbe8e850d6d412224dc28af6d2627c5c0e4fca9f243cde04bc804a0/68747470733a2f2f6f776e636173742e6f6e6c696e652f66617669636f6e2e706e67"> Owncast**[Troubleshoot Common Problems](/troubleshoot/)**Find solutions to common issues.

I don't know exactly what is going on. But none of my other friends have this issue. What information should I be looking for? There's no settings for me to be choosing. I don't get an error. The stream just buffers constantly and has like 4 seconds of playtime in between buffers. 

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/troubleshoot/">Troubleshoot Common Problems</a></strong></div><div>Find solutions to common issues.</div></blockquote>

**Comment by gabek** [comment]
By errors, I mean errors in your browser console. I also highly recommend you to look at your browser developer tools, under network, and see the specifics behind the actual network requests and find out why the requests are failing.

By other players, I mean test with VLC, mpv, Quicktime, etc. Whatever other streaming video players you might have available or want to download to compare to the web.

I assume you've tried this already, but under the player settings, as long as the streamer has configured multiple output qualities, you should try selecting the lowest one to make sure you're playing a quality that is most likely to succeed if you have a slow network connection.

And like I suggested before, I recommend speaking with the streamers you're trying to watch, as they have a diagnostics screen that will tell them if one of their viewers is unable to consume their stream due to network performance. You will want to ask them for assistance.
