### ISSUE TITLE
Total number of viewers -ever (feature request)

### ISSUE THREAD

**Issue by ozgurkazancci** [owncast/owncast#3711]
Is it possible to have a tiny column in "Viewers" page showing the total number of viewers ever connected? The closest thing to this is: "All-time max viewers" however it's unknown how many connections/watchings have been made as total, so far.

Regards.

**Comment by gabek** [comment]
Hi there. I'm not sure if I totally understand the details of what you're thinking. To clarify: If viewer X connects to your stream, the counter goes to 1. If they disconnect and reconnect, it goes to 2?

**Comment by ozgurkazancci** [comment]
Hi @gabek, exactly! Imagine my stream is embedded into an IPTV player&channel list of a TV.

Then, the people in the house today played my channel for a while, they later changed the channel, and in the evening they returned to my channel again, and so on. These actually counts how many times the channel (stream) was watched, which is actually an important detail worth to be located in "Viewers" page.

Kindest regards.

**Comment by gabek** [comment]
For most people, while I could see that being maybe an interesting number, I don't think it would be very useful to them. It would just be some magical big number that doesn't really mean anything. If a streamer sees 4,528, what does that mean? Nothing, really. It depends on how many times they streamed. And then the streamer would probably do the math to figure out the average viewers per stream in that case. And even having an average number of viewers per stream isn't that useful because you already know the number of viewers for each stream.

So unfortunately, I don't see the utility in this number. But I will leave this issue open in case others want to chime in if maybe I'm just missing something and there are use cases I'm not thinking of.

**Comment by frzqwerty** [comment]
Hi,

I think such feature would be useful.. 

> For most people, while I could see that being maybe an interesting number, I don't think it would be very useful to them. It would just be some magical big number that doesn't really mean anything. 

Well, **how many people watched the stream in total?** This would really give an idea to the streamer. So +1

**Comment by gabek** [comment]
It wouldn't give the number of people who watched a single stream in total, that already exists. What is being asked for is a number for the all-time history of the server. And I'm afraid I don't understand how that would be useful. It would just be a number without context. It wouldn't tell you unique users, you wouldn't know if 1000 was the same 100 people connecting 10 times, or if it means it's 1000 different people. You wouldn't know the number of times you streamed, so 1000... is that big or small? It depends on how many times you've streamed.

If you said all-time watch time or something, I could see how that would be interesting. Still not useful, but at least interesting.

**Comment by markcy0** [comment]
All-time watch time would be valuable thing. I think the statistics page could be better-detailed.
For instance, top locations/countries/cities.. Daily, weekly, monthly statistics.

**Comment by gabek** [comment]
I wasn't trying to brainstorm new ideas to add to Owncast here. I was sharing examples of things I could come up with off the top of my head that would make more sense. I wasn't looking to build them just because I mentioned them.

If you have feature requests, however, please do open a request with specifics.
