### ISSUE TITLE
Owncast Mastodon error caught in sidekiq

### ISSUE THREAD

**Issue by shleeable** [owncast/owncast#3774]
### Share your bug report, feature request, or comment.

My mastodon instance caught this error recently.. 

`110997814916124935, "{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"actor\":\"https://stream.labr.online/federation/user/video\",\"id\":\"https://stream.labr.online/federation/OL5KD9yIg\",\"type\":\"Accept\"}", 109432497774090692, "Account"`

![image](https://github.com/owncast/owncast/assets/17537000/3cb38732-fc73-451b-8df1-2b0103a3c06f)

**Comment by gabek** [comment]
Could you point out the specific error with Owncast? Upon looking at that screenshot it's not clear what exactly you're talking about, I'm just seeing Ruby errors.

**Comment by mahmed2000** [comment]
Owncast didn't send a valid message it looks like? The `object` key is missing here and mastodon can't index the value since its `nil`. Owncast's apub code definitely tries to add it however, so some lacking error checking on owncast's end I think.

**Comment by gabek** [comment]
How are you able to see the full payload? I'm getting a 404 when I try to look at https://stream.labr.online/federation/OL5KD9yIg. Unless I made a typo?

<blockquote><img src="https://stream.labr.online/logo/external" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> LABR LIVE</div><div><strong><a href="https://stream.labr.online/">LABR LIVE</a></strong></div><div>live dj sets, soulful house music, eclectic jams

#music #dj #mashups #house #dance #rock #LABR #housemusic #soulful #footwork #jungle #juke #fediwave #freeform #mixes #80s #livesets #djsets</div></blockquote>

**Comment by mahmed2000** [comment]
> "{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"actor\":\"https://stream.labr.online/federation/user/video\",\"id\":\"https://stream.labr.online/federation/OL5KD9yIg\",\"type\":\"Accept\"}"

I'm going off of mastodon's code. It errors here:
https://github.com/mastodon/mastodon/blob/929b9fdaff1e6d4223efd8f00bd0b53fae1c7ce1/app/lib/activitypub/activity/accept.rb#L8

`@object` is set here:
https://github.com/mastodon/mastodon/blob/929b9fdaff1e6d4223efd8f00bd0b53fae1c7ce1/app/lib/activitypub/activity.rb#L14

Takes the json, indexes it for the `object` key which gives `nil`. Then tries to index the `nil` for `type` but can't since `nil` can't be indexed.

The `object` key needs to be at the same level as `type` and `actor`. I don't see any code that would work with an `id` at that level, but there might be? Would need working examples to check if they have the `object` property or if mastodon works with this syntax and this is an edge case.

Owncast constructs an object here:
https://github.com/owncast/owncast/blob/4c0233a6019eedc03b3fe6ab98ba081c7bd0b708/activitypub/requests/acceptFollow.go#L47
It should match up with mastodon since it tries to append an object specifically of type "Follow" in the next line

<blockquote><img src="https://opengraph.githubassets.com/9500811033305f68d68385a94de36cf12b9e8786a150f0e9fb73508afbad1e0a/mastodon/mastodon" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/mastodon/mastodon/blob/929b9fdaff1e6d4223efd8f00bd0b53fae1c7ce1/app/lib/activitypub/activity/accept.rb">mastodon/app/lib/activitypub/activity/accept.rb at 929b9fdaff1e6d4223efd8f00bd0b53fae1c7ce1 · mastodon/mastodon</a></strong></div><div>Your self-hosted, globally interconnected microblogging community - mastodon/mastodon</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/9500811033305f68d68385a94de36cf12b9e8786a150f0e9fb73508afbad1e0a/mastodon/mastodon" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/mastodon/mastodon/blob/929b9fdaff1e6d4223efd8f00bd0b53fae1c7ce1/app/lib/activitypub/activity.rb">mastodon/app/lib/activitypub/activity.rb at 929b9fdaff1e6d4223efd8f00bd0b53fae1c7ce1 · mastodon/mastodon</a></strong></div><div>Your self-hosted, globally interconnected microblogging community - mastodon/mastodon</div></blockquote>

**Comment by gabek** [comment]
I just don't know if that message is showing the entire payload or not. It's difficult to know exactly what was sent to that server without being able to see the entire thing. If it said it was explicitly missing an object, or it was looking for a specific key that would be helpful, but it's not giving anything to work with. All we have is a truncated message and no example of the raw message it's acting upon.

If we were confident that the message shows the entire payload, then yes, object is missing, but I don't know what I'm looking at in this case.
