### ISSUE TITLE
Research and possibly do a visual overhaul of Owncast website

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3797]
### Share your bug report, feature request, or comment.

Public facing [owncast.online](https://owncast.online/) Website design looks dated and it would be nice to “re-skin" the website with a new theme or template.

Putting this out there for anyone to brainstorm resources that gives the website a modern look.

**Comment by gabek** [comment]
I'm slightly biased, as it took a while for us to land on this website design as it is, and it would probably take a lot of work to do it again, since there was a lot of customization involved. It wasn't just installing a theme.

But one thing to think about is how successful this current website is at doing what it's supposed to do. If you look at the [analytics](https://plausible.io/owncast.online), the top page (other than the home page) is the quick start. That means the majority of people who go to the website are successfully routed to installing Owncast, and that's awesome. That doesn't necessarily mean they do install it, and that process can always be improved, but it at least shows them how easy it is to get running, and that's a success.

So, while I'm not opposed to a facelift, if it's something that we can do without much of a hassle, it would have to be at least as good as the current site is at doing its job. And the current one seems to be good at its job.

**Comment by germainelee** [comment]
I had this thought and wanted to pen it down as I was impressed by the website design of [Huly app](https://huly.io/), [Pixelfed](https://pixelfed.org/), and other self-hosted software. It looks so sleek, and the Huly dev shared that it was built with [Astro](https://astro.build/) using a completely custom-made theme. Have not heard of Astro before, but I have heard of Webflow and Wordpress are commonly used by non-profits.

**Comment by gabek** [comment]
The framework that it's built with doesn't matter. We use [Hugo](https://gohugo.io/), it works great. If we changed to another framework it would look the same. If we changed to Astro it would also look the same. The hard work is somebody designing a new web site that meets all of our requirements.

**Comment by germainelee** [comment]
This issue is more of design task first then implementation. So designer working on this should create designs in Penpot.
