### ISSUE TITLE
Admin Edit Social Handle save without name

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3812]
### Share your bug report, feature request, or comment.

When adding a new Social Handle, I'm able to proceed and click Ok without selecting an option in Social Platform field. But, that should not be the case.

## Steps to replicate
1. Navigate to Configuration -> General
2. Leave 'Social Platform' field blank
3. Enter https://directory.owncast.online/ in URL field
4. Observe 'Ok' Button is enabled

![image](https://github.com/owncast/owncast/assets/118464031/69ceb845-fae1-4b6f-814e-3d44c6f027ee)

5. Click 'Ok'
7. Social Link is added to list
![image](https://github.com/owncast/owncast/assets/118464031/6caa3f75-0409-49dc-9211-1d5dc1235306)

## Expected Behavior (Quick Fix)

- All Input fields in this modal should be `required` 
- 'Ok' Button remains disabled until all fields are filled

~~uses Ant Design 4's error design, with the following error message: Required field~~

**Comment by gabek** [comment]
The text input field should be disabled until you select an option from the above dropdown. In theory, no error message should be necessary.

**Comment by germainelee** [comment]
Disabling the URL text field at the start can help guide the user to select the dropdown first, but looking from another perspective, it's like putting in a "do not touch" sign on the input field. Seeing that the input field is disabled by default and figuring out how to enable it is cognitive load. We should minimise cognitive load to maximise usability. 

I proposed the error message because the app needs to communicate that all fields are required. An alternative solution is to put a tooltip when mouse hover the disabled 'Ok' button. So the button remains disabled until user fills in all the fields and there won't be any error state.
![image](https://github.com/owncast/owncast/assets/118464031/2183ccd6-d3ea-49c2-8a2b-f614258e6258)

**Comment by gabek** [comment]
Since this is a regression, fixing the bug is the goal here. Of course, if somebody wants to go over and above, and redesign how it works, that can be discussed, but for something so small I am not convinced that's a good use of somebody's time. But if somebody is passionate about this particular modal, I wouldn't stop them!

**Comment by germainelee** [comment]
If that's the case, then would the quick fix with low amount of effort be:

Having the button remain disabled until user fills in all the fields ?

**Comment by gabek** [comment]
Yup, I believe that's how the other modals should be working too.

**Comment by Manish-Giri** [comment]
Hello, is this open for contributions? Would like to give it a shot, if so.

**Comment by gabek** [comment]
Absolutely, welcome @Manish-Giri! Please let me know if you have any questions, or have any issues getting the project [up and running](https://owncast.online/development).

**Comment by Manish-Giri** [comment]
@gabek Thank you for the kind words!

I was able to set up the repo and get it running. Also located the code for the reported problem, and made a simple fix (`platform` should not be an empty string, otherwise the OK would be disabled). Does this screenshot look like the expected result?

![image](https://github.com/owncast/owncast/assets/11348778/ff94e9eb-3ab7-4e7e-9a9a-1550f9668fcc)

**Comment by gabek** [comment]
Awesome! That looks right to me!
