### ISSUE TITLE
Discuss: Delete Owncast provided Object Storage documentation

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3836]
### Share your bug report, feature request, or comment.

https://owncast.online/docs/storage/

At first, we provided this to make it super easy to follow specific instructions to get Owncast working with popular object storage providers. But then more object storage providers got added, and the specifics with all of them continued to change, and our documentation has always become out of date. It's become impossible to keep in sync with all the different companies, and I think it's causing more harm than help at this point.

Instead, we should have a single document with some generic concepts, but no specific instructions for any provider, and no recommendations. It's up to the user to make purchasing choices, and to read the provider's official documentation.

I'd love to hear any feedback or thoughts on this.

**Comment by germainelee** [comment]
I may not be the right person to comment on this but I'll share my thoughts based on my understanding of the described issue.

It's easier to maintain one S3 Storage document and provide a generic tutorial or key points when configuring the settings. Then just direct them to the respective storage service provider website

**Comment by gabek** [comment]
We can't even reliably direct people to storage service provider's websites, as there are so many now, and we'd still have to keep up to date with a list of all the different providers.

**Comment by germainelee** [comment]
It would be nice to keep the list up to date, but we can say that these 10 are the common ones.

**Comment by gabek** [comment]
There's no way to determine what the most common ones are, either. Everyone has their own preferences of what they would like to use. The obvious choice for me may be something somebody else would never use.

**Comment by germainelee** [comment]
Of course preferences are usually subjective. As long as we tell them that then they might understand. It doesn't need to be a correct list / must follow this list. I believe they are smart enough to decide for themselves as they are many other factors.

**Comment by samwherever** [comment]
@gabek i'll need some time to read the docs and understand requirements, but i think i have a few ideas on how these can be condensed. i'll try to get a PR filed next week.

**Comment by gabek** [comment]
Ran into this being a problem again today. I should just pull the trigger on it.

**Comment by gabek** [comment]
Done.

**Comment by popey** [comment]
(I'm a new user of owncast)

FWIW, this confused me for too long today. I wanted to set up Cloudflare, and was certain I'd seen a doc for it. Search engines also cached it. The fact the docs repo had a deletion of docs, which was matched by a discussion in a completely different repo, also threw me - when looking for why it was deleted.

I used the docs and (I think) successfully set up Cloudflare in front of Downcast. I would not have set that up correctly without finding the original PR and reading the source code.

I get why you removed it, but I think you may be diminishing the usefulness of docs like this, even if they're not 100% accurate always (are any docs?). Because you'll likely never know someone couldn't find docs they couldn't find because they likely won't tell you.

**Comment by gabek** [comment]
It's like if you found a recipe for an apple pie online, and the recipe site had to tell you where in every single grocery store in the world exactly where to find the apples in each store. That would be crazy, and completely out of the scope of the point of the recipe. The grocery store is already there to help you find the apples. Besides, when the store moves the apples, the instructions on where to find them will be wrong, anyway, so just ask the people at the store.

It doesn't make sense for us to write the documentation for random companies, they already write their own documentation and are much better at it. I understand it's inconvenient to have to leave the Owncast website to read documentation elsewhere, but that documentation will be much more helpful than what we can provide. I apologize during this transition it caused confusion, but hopefully, going forward, this will be better for both users of Owncast and for the project itself.

**Comment by popey** [comment]
With respect, poor apple pie analogies aren't needed. This isn't apple pie; it's amazing, niche, open-source software that integrates well with other well-entrenched, incredibly popular software and services from massive companies. 

I stumbled on this discussion too late because I'm not a contributor and became a user in the last 48 hours. Your response was disappointing and dismissive. I just voiced my perspective as a new user, actually looking for the documentation you deleted - seemingly (to me) for no good reason.

Personally, I recognise nine of the 10 companies listed on the deleted documents. Calling them 'random companies' does not serve your point well. The deleted documents were the only useful hit for enabling that integration. 

Looking at the git history of the deleted documents, the maintenance burden on those was minimal, if any. 

![image](https://github.com/user-attachments/assets/ddc12ace-2133-4bfb-9f76-a3f0aae89dd2)

I've only worked in open-source communities for about two decades, though. But in my experience, it is *incredibly* common for small, niche software developers to document how to integrate their products, projects, and services with third-party tools. This is bread-and-butter documentation. Is it a burden? Perhaps, but it doesn't really look like it from the git history. 

Having those brands in your documents also serves the project well, whatever your personal opinion of those organisations. If you didn't want the deleted documents to remain in your repo, they could have been moved to a community-maintained wiki, blog posts, or some other location.

Obviously, I do understand the motivation to delete stuff. My good friend @castrojo did a [lightning talk](https://www.youtube.com/watch?v=IT1yY78J9A0) thirteen years ago at an Ubuntu event encouraging people to delete out-of-date content. I appreciate the sentiment. 

If you were deleting docs on "_How to connect to the Internet on Debian GNU/Linux 3.0 'Woody' using an Orinoco Gold PCMCIA card_," I'd be 100% behind you deleting the docs. But this is contemporary, accurate, and useful documentation. It makes no sense.

At the end of the day, it's your project, and you "do you," as they say. It works both ways, though; don't expect all those "random" companies to write your user docs. They won't. 🙏

**Comment by gabek** [comment]
Again, I apologize, but this is the best move going forward.

It's true those documents were not maintained. That is exactly the problem we're talking about here. There was nobody to keep up with the moving targets that are the different object storage providers. They were clearly not contemporary, nor accurate.

> If you didn't want the deleted documents to remain in your repo, they could have been moved to a community-maintained wiki, blog posts, or some other location.

That sounds like a great idea! If somebody from the community wanted to focus on this and publish guides, I'd happily link to it. Is this something you'd be interested in?

I'm sorry you're disappointed, but I hope it's clear why this makes sense and hasn't been something that is maintainable for a small project with nobody dedicated to something like this. We've already confused more people than helped, and that needed to end. I appreciate in your case that might not have been the case, but I have to think about the big picture.

**Comment by popey** [comment]
> That sounds like a great idea! If somebody from the community wanted to focus on this and publish guides, I'd happily link to it. Is this something you'd be interested in?

Sure. 

Would you want it themed and 'branded' like owncast, or would you prefer it was entirely disassociated with the project, as a separate repo of useful guides and topics?

**Comment by gabek** [comment]
Handfuls of people have written up setup guides that are specific to a certain hosting environment and/or vendors. There are certainly more out there than these, and I wish we were better at knowing about them and linking to them, but there are a few here: https://owncast.online/examples/blogs-tutorials/. If people tell us about something they wrote, then we can link to it, but usually, we don't hear about it.

I see object storage falling into the same category. If somebody uses Vultr for object storage and wants to write a guide on how to use it, great! Minio? Great! Those who actively use those services will be the most knowledgeable about them and will be the most helpful to others.

We have the same situation with hosting providers. Early on with Owncast it seemed like a good idea to have documentation on how to set up Owncast on specific hosting providers with their 1-Click installs. But just like with the storage providers, these went out of date, and so many different hosting companies popped up offering Owncast it was impossible to address them all, and now we're also looking like we're playing favorites by mentioning some providers over others. These providers write their own documentation, so we should let users use that much more accurate information. But I haven't done anything about these, yet.




<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/examples/blogs-tutorials/">Blogs and Tutorials</a></strong></div><div>Blog posts, tutorials, and articles by people sharing their experiences with Owncast.</div></blockquote>

**Comment by popey** [comment]
Ok, I have some time to noodle with these docs over the weekend and come back to you. Where's best? I imagine not on a closed issue :)
