### ISSUE TITLE
Use the chat feature by itself standalone

### ISSUE THREAD

**Issue by nuekaze** [owncast/owncast#3884]
### Share your bug report, feature request, or comment.

I really like the chat feature of Owncast and would love to have it possible to just run the chat by itself so you could embed it on any site. Or is there a way to always enable the chat without the stream running?

**Comment by gabek** [comment]
I'm sorry, but the chat is directly tied to the live stream. It's only available when a stream is live. It was designed this way because if chat was available even when nobody was streaming, it would just become a target of abuse. But there has been discussion in the past of optionally keeping it enabled all the time. But that's not something that's on the roadmap right now. But as more people have asked for it over time, it's likely going to be a change that's made.
