### ISSUE TITLE
Add option to change streaming URL on home page from rmtp to rmtps when using a reverse proxy to provide ssl

### ISSUE THREAD

**Issue by ghost** [owncast/owncast#3951]
### Share your bug report, feature request, or comment.

More of a nice to add feature from an administration perspective. If using a reverse proxy to provide ssl encryption to a rtmp stream (rtmps) it would be nice to have an option in the server settings page that would change the streaming URL on the home page to start with rtmps. Maybe a toggle or checkbox next to the rtmp port that says something like: "using reverse proxy for ssl (rtmps)." When the toggle is checked it will change the URL on the home page to rtmps.

**Comment by gabek** [comment]
Because Owncast doesn't natively support `rmtps` it wouldn't make sense to add support for showing that protocol. Though I understand why it makes sense in your use case.

If there was some way to auto-detect that it was being used, and Owncast could make that change for the user's behalf, then maybe. But adding an admin setting that most people shouldn't ever use, and isn't applicable for Owncast's actual features, is at least not going to happen now.

I imagine people would just check the box, not knowing what it meant, and then complaining when they can't connect to the RTMP url. I'd rather the very small number of people who are proxying RTMP, and who know what they're doing (like you), have to make that tiny change themselves, than the 99.5% of people who aren't doing that, and will be confused.

**Comment by ghost** [comment]
Fair point. Thanks for the consideration!
