### ISSUE TITLE
Websocket doesn't reconnect

### ISSUE THREAD

**Issue by liclac** [owncast/owncast#3958]
### Share your bug report, feature request, or comment.

If the websocket connection gets interrupted for any reason, it doesn't seem to ever reconnect.

Steps to reproduce locally:
- Run Owncast and start a stream. I've got OBS streaming a blank scene to it.
- Open http://localhost:8080/ - or wherever your test instance is running.
- Run a proxy on another port: `socat TCP-LISTEN:8081,reuseaddr,fork TCP:localhost:8080`.
- Open http://localhost:8081/ in a private browsing window.
  - You should now have two users in chat, both able to chat to each other.
- Stop (Ctrl+C) and re-start the proxy.
  - The :8080 tab shows that the :8081 user has left the chat.
  - The :8081 tab shows nothing out of the ordinary, but the websocket has been silently disconnected.

In this disconnected state, everything looks normal, except that no further chat messages are received. On latest develop, attempting to send a message simply does nothing, but on v0.1.3, it will look to the user like it succeeds - it's added to the chat log on the client side, but never actually sent, so they're just stuck talking to themselves.

Opening the dev tools and looking at the websocket connection in the network inspector does show it as disconnected, but nothing is logged to the console, including [this error message](https://github.com/owncast/owncast/blob/c712c5f7939b862cbd6e3516addadd93206c4a2c/web/services/websocket-service.ts#L161-L165), which suggests to me that for some reason, the `onError` handler never gets called.

While "kill socat to disconnect chat" is a bit of a contrived example, we've observed this problem live during a friend's streams, where the embedded chat overlay onscreen would sometimes silently stop showing new messages until manually reloaded.

Confirmed on both latest develop (deb938d52127ecf9fc3474a2489323b9d2ee118b, 2024-10-11) and on v0.1.3.  
The web assets were built with `cd web/ && rm -rf node_modules && npm install && npm run build`, before doing a  `go run .`.

**Comment by alyssais** [comment]
I suspect this is because chat is listening for the WebSocket `error` event, but not the `close` event.

Looking at the [spec](https://websockets.spec.whatwg.org/#closeWebSocket), the `error` event is only fired if the socket is full when it's closed, but the `close` event is always fired. `error` is not mentioned anywhere else in the spec, so any time you see `error`, it will be immediately followed by `close`.

So I think that chat should instead listen for `close`, so it handles disconnections where the socket is not full.  The listener would have to be adapted slightly to handle the case where the reason the socket was closed is that `shutdown` was called — I think the only change to be made would be not calling `handleNetworkingError` in that case.

As an aside, I think the `error` listener calling `close` on the socket is probably redundant, as when we get an error that always means that the socket is already closing.
