### ISSUE TITLE
Create an external version of the user details /api/moderation/chat/user/{userId} API

### ISSUE THREAD

**Issue by AnActualEmerald** [owncast/owncast#4015]
### Share your bug report, feature request, or comment.

The `/api/moderation/chat/user/{userId}` endpoint appears to not use the same bearer authorization scheme as the other external APIs. The [docs](https://owncast.online/api/latest/#tag/External/operation/GetUserDetails) indicate that you should use a query parameter, and the server will give an error if one isn't provided, but even providing one as described the request always returns a 401 `unauthorized` status. This happens when using both the admin stream key and an integration access token in the query parameter and the bearer auth schemes.

I've tested this and gotten the same behavior on the stable v0.1.3 docker image and the develop branch (421cdd069377fb0473991f6ec23b0a2b2b8be0ad)

**Comment by gabek** [comment]
Hi there.

I sincerely apologize, the confusion here seems to be purely on the fact I accidentally labeled that API as an "external" API and I didn't mean to.

All the external APIs are prefixed with `integrations`, and I simply put this one in the wrong category for documentation.

I'll rename this issue as a TODO to create an external version of this API that works the same way as the rest of them do.

**Comment by varungujarathi9** [comment]
Hey @gabek 
Is this still up for grabs? I can work on it

**Comment by gabek** [comment]
Yeah, it's all yours! If you haven't previously taken a look the [API doc](https://owncast.dev/48ba2900908940238f2cb3e1d32e2f85?v=0f6df38e353740e1a8096164f617ea18&p=43f9c6a2f35143fabb6b2036ee6f09ef&pm=s) is helpful on how to add a new route.

In this case, the new route can point to the same handler as the existing one, since the logic is exactly the same. The only difference is the authentication layer.
