### ISSUE TITLE
Nil pointer exception in ReportPlaybackMetrics API

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#4016]
### Share your bug report, feature request, or comment.

```
 panic: runtime error: invalid memory address or nil pointer dereference

 -> github.com/owncast/owncast/webserver/handlers.ReportPlaybackMetrics
 ->   /home/gabek/src/owncast/webserver/handlers/playbackMetrics.go:33

    github.com/owncast/owncast/webserver/handlers.(*ServerInterfaceImpl).ReportPlaybackMetrics
      /home/gabek/src/owncast/webserver/handlers/handler.go:83
    github.com/owncast/owncast/webserver/handlers/generated.(*ServerInterfaceWrapper).ReportPlaybackMetrics.func1
      /home/gabek/src/owncast/webserver/handlers/generated/generated.gen.go:5361
    net/http.HandlerFunc.ServeHTTP
      /home/gabek/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/net/http/server.go:2220
```

**Comment by mahmed2000** [comment]
> github.com/owncast/owncast/webserver/handlers/generated.(*ServerInterfaceWrapper).ReportPlaybackMetrics.func1
      /home/gabek/src/owncast/webserver/handlers/generated/generated.gen.go:5361

Line 5361 in that file isn't Playback metrics, currently, PlaybackMetrics start at 5369 so it should be 5377:

https://github.com/owncast/owncast/blob/e1acfee49d4baa3f67ded96333f0e379e3df123b/webserver/handlers/generated/generated.gen.go#L5352-L5369

Might be a dupe of #3984 from an outdated build? The line number fits if its before eed34b5, might also be before 0fccaa6. Otherwise the nil check would mean its an invalid memory address unless there's a memory corruption between the nil check and the value being read.

**Comment by gabek** [comment]
I'm quite sure I was using `develop`, but I should have documented that. I'm just going to leave this open and if it happens again I'll come back to it, and otherwise it'll just close.

**Comment by gabek** [comment]
I have not experienced this again. Closing.
