### ISSUE TITLE
Add support for configuring RTMP deadline timeout

### ISSUE THREAD

**Issue by gaby** [owncast/owncast#4036]
When running `owncast` in a low-bandwidth environment or behind a firewall there could be times when no data comes through for a few or up to 20-30 seconds. Currently `owncast` creates a `rtmp` server and sets a hard-coded `10 * time.Second()` deadline that auto-disconnects the stream when it's hit. This causes the whole stream to get disconnected, and when new data comes in it has to start-over again. 

This can be seen here: https://github.com/owncast/owncast/blob/develop/core/rtmp/rtmp.go#L122

This timeout should be configurable, probably through a `cli` argument the same way the `rtmp port` can be configured as seen here: https://github.com/owncast/owncast/blob/develop/core/rtmp/rtmp.go#L38

**Comment by gabek** [comment]
In general, I'm not a fan of adding additional settings where people can just input values. Especially when it's a very rare use case. There has been discussion in the past of people wanting the stream to not drop when RTMP drops, and I'm certainly up for discussing how that might be done. But just increasing the timeout more and more isn't a real solution, that's just a workaround.

In the short term, if increasing that timeout from 10 seconds to 15 or 20 would be helpful, then we could make that change.

**Comment by gaby** [comment]
@gabek It's a real-use case when the default approach by `owncast` is very aggressive and disconnects the whole stream/client. I have to manually restart the client `ffmpeg` and also anyone displaying the stream has to click `Play` again on the video player.

When using ffmpeg as a rtmp server it doesn't timeout, it just keeps listening forever.

I really don't want to fork a project because of a hard-coded value.

I had cases of up to `30-45` seconds without data, yes it will start buffering but having the whole stream die and then having to click `Play` again is not user-friendly.

Ideally timeout's should be configurable via `cli`, excluding the UI is fine.

Also, I can do a `PR`, if needed.

**Comment by gabek** [comment]
I didn't say it wasn't a real use case. I said I'm willing to find a solution.

What I did say is I'm not interested in adding new configuration options to work around your problem, instead of finding a holistic solution to make the software better for everyone.

**Comment by gaby** [comment]
@gabek What would be a solution to make the software better for everyone?
- increasing the default timeout?
- removing the timeout completely?

Btw, It took me several hours to figure out the issue was `owncast` and not my stream/client because the only message logged by `owncast` is `Inbound stream disconnect`. The error should be different for timeout reached.

**Comment by gabek** [comment]
See above.

> There has been discussion in the past of people wanting the stream to not drop when RTMP drops, and I'm certainly up for discussing how that might be done.

I understand you have a very specific issue that you're experiencing, and I apologize you're going through that. But adding new settings every time somebody wants something specific isn't the answer. That's when you take a step back, look at what it is that is being discussed, and find a solution that works for everybody out of the box.

That indeed takes longer, and is more complex than simply adding more settings. And that's why I offered to bump up that timeout in the short term if this is something we really want to work towards.

**Comment by gaby** [comment]
Sounds good, I will run a local fork in the meantime.

**Comment by gaby** [comment]
@gabek I bumped the timeout to 5 mins in a local fork, although 60-120s is probably good enough from my testing.

**Comment by gabek** [comment]
Just a heads-up, since it may not be clear what the negative side effect of this may be, even though it's technically what you want.

There are scenarios where the RTMP broadcasting software does not cleanly terminate the connection. So it gets killed on the broadcasting side, but does not tell Owncast it should be closed. Owncast will still hold that connection open, waiting. In your case, it will wait for five minutes.

While this is exactly what you, personally, are looking for, if a connection is intermittent or temporarily lacking. You didn't want Owncast to shut down that socket so it could continue where it left off.

But if your connection were to actually completely drop, and you need to reconnect, and Owncast isn't aware, for five minutes if somebody tries to start a new stream Owncast will reject it, because it believes the old one is still active, and is simply just temporarily waiting. You'd be stuck and unable to stream again for that entire time because you told Owncast not to shut down dead connections.

This is the original issue that brought it up: https://github.com/owncast/owncast/issues/564

**Comment by gaby** [comment]
@gabek That's great information. In that case I will set mine to 60s, which is a typical timeout number for connections.

I have seen the behavior you described when using just plain ffmpeg.

**Comment by flexiondotorg** [comment]
FYI: Twitch's timeout is 60secs.

**Comment by gabek** [comment]
A whole minute is a long time to not be able to reconnect.

**Comment by gaby** [comment]
@gabek It probably takes as long to setup a new stream and wait for the video to show up in case of a 10s timeout.

**Comment by gabek** [comment]
I'm thinking primarily of OBS auto-reconnecting. It would fail for an entire minute.

**Comment by gaby** [comment]
> I'm thinking primarily of OBS auto-reconnecting. It would fail for an entire minute.

Agree, that's why I initially suggested making this configurable.

**Comment by gabek** [comment]
Making it configurable wouldn't fix that problem.

**Comment by flexiondotorg** [comment]
> A whole minute is a long time to not be able to reconnect.

I had a PSU problem that caused my PC to just reboot mid-stream. I was able to rejoin the stream and continue because of this timeout window 🙂

**Comment by gaby** [comment]
> > I'm thinking primarily of OBS auto-reconnecting. It would fail for an entire minute.
> 
> Agree, that's why I initially suggested making this configurable.

The fact that there's so many opinions here further confirms that this should be configurable. Having a hard-coded  `10s` is too aggressive, but at the same time it's perfect for a lot of users, but anyone outside the norm will be affected. Even further the `log` messages for this timeout are `debug` level so you never see them.

I was only able to figure out this was my issue by looking at the code. The logs from `owncast` don't tell you anything other than "Incoming stream has been disconnected`.

**Comment by gabek** [comment]
You only have to look above to see why customizing this value isn't a good idea. Somebody will set it to 5 minutes, and then not be able to connect to Owncast at all, and say Owncast is broken.

Micromanaging every single configuration is not the answer.

**Comment by gaby** [comment]
I will keep running a fork, can't get anywhere here:
- Timeout is hard-coded and very aggressively.
- Increasing timeout was rejected.
- `Owncast` logger is conservative, took me hours to figure out why my stream was dying since all these important messages are hidden with `Debug` level.
- Making this configurable was rejected.

If anyone else is having this issue, feel free to use this https://github.com/gaby/owncast

<blockquote><img src="https://opengraph.githubassets.com/e676d69cfc2f6fb9090551667839ac968ab4b3c54cb29e3b6ca2ece6f7008a2d/gaby/owncast" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/gaby/owncast">GitHub - gaby/owncast: Take control over your live stream video by running it yourself.  Streaming + chat out of the box.</a></strong></div><div>Take control over your live stream video by running it yourself.  Streaming + chat out of the box. - gaby/owncast</div></blockquote>

**Comment by sobujbd** [comment]
> I didn't say it wasn't a real use case. I said I'm willing to find a solution.
> 
> What I did say is I'm not interested in adding new configuration options to work around your problem, instead of finding a holistic solution to make the software better for everyone.

Thank you for your willingness to find a solution! I completely agree that a holistic approach would be best for improving Owncast overall. I’m not looking for additional configuration options—just a built-in way to handle brief disconnections more gracefully.

Are there any current possibilities within Owncast to handle this, or would it require deeper changes to the core? If this can be achieved by rebuilding Owncast, I’d appreciate any guidance on how to approach it.

**Comment by sobujbd** [comment]
> But if your connection were to actually completely drop, and you need to reconnect, and Owncast isn't aware, for five minutes if somebody tries to start a new stream Owncast will reject it, because it believes the old one is still active, and is simply just temporarily waiting. You'd be stuck and unable to stream again for that entire time because you told Owncast not to shut down dead connections.
> 

How about when a stream disconnects, start a short "reconnection window" (e.g., 1-5 min) where Owncast waits for the original broadcaster to return.

If the broadcaster reconnects within this window, continue the stream seamlessly.

If a **new stream key is detected**, assume it’s a different broadcaster and allow the new stream immediately.

**Comment by gabek** [comment]
> How about when a stream disconnects, start a short "reconnection window" (e.g., 1-5 min) where Owncast waits for the original broadcaster to return.

[See above](https://github.com/owncast/owncast/issues/4036#issuecomment-2504140811) for the discussion about large timeout values.

> If a new stream key is detected, assume it’s a different broadcaster and allow the new stream immediately.

That seems like the opposite of what we'd want, as that would mean any other user/piece of software can kick off the current broadcaster at any time.

I understand each person is thinking very specifically about their own problem, but that's not what I'm doing. I'm trying to think about _all_ users.  And I believe we have two use cases.

## Use case number 1

1. User is streaming.
2. User gets disconnected uncleanly for some reason, either from their local side, or from their server side for any number of reasons. [Some broadcasting software is known to always do this](https://github.com/owncast/owncast/issues/564), even when disconnecting on purpose.
3. They press the "Start Stream" button to start streaming again.
4. Currently, they have to wait 10 seconds before they can start streaming due to the timeout.

## Use case number 2

1. User is streaming.
2. User gets a temporary blip in a network connection.
3. If the temporary blip resumes within 10 seconds they transparently resume streaming.
4. Otherwise they press "Start Stream" to stream.

Currently, I believe use case number 1 is more common than use case number 2. And that's why the timeout is aggressive, to allow people to re-connect and get back to streaming faster. But that annoys people like a couple of you. So we could change that and assume use case number 2 is more common and increase the timeout by a little or a lot. But that would mean people in use case number 1 would be locked out from streaming until the timeout expires. 60 or 30 seconds would feel like an eternity of watching OBS keep trying to auto-reconnect while watching your Owncast logs say "Cannot overtake existing stream" and you're locked out.

So to resolve that new problem, we could remove the restriction that if somebody is streaming, somebody else can't connect. That way, even if you were in a timeout, and somebody tried to reconnect from use case 1, they'd just kill the existing connection and restart the stream. However, that would mean that if their software was being weird and attempting to reconnect multiple times, or they had multiple pieces of software running for whatever reason (automated systems or whatever), they'd just keep getting kicked out (I've seen this happen to people, and they were saved due to the 1 connection limitation). Not to mention, if multiple people had access to the server, they could kick off the current streamer any time they felt like it.

So we could go with the original suggestion, that we make the timeout configurable. And I totally get why that makes complete sense to you. But the more settings that are added to Owncast, the more overhead it requires for somebody to understand how to run it. Now we will have to explain what the _RTMP timeout_ is. And if they get the value wrong, it will impact them heavily, as if they set it too high (like in the above thread, multiple people wanting to set it to 5 minutes) it will make Owncast look broken.

So I hope you see where I'm coming from.

**Comment by sobujbd** [comment]
Thanks for considering the different use cases and offering such a thoughtful perspective on the issue. I understand the concerns around adding too many settings, and I agree that simplicity is key for users.

**Comment by gaby** [comment]
I'm still running a fork of  `owncast` because of this setting. Having a hard-coded timeout with a `debug` level message makes debugging impossible.

**Comment by sobujbd** [comment]
> I'm still running a fork of `owncast` because of this setting. Having a hard-coded timeout with a `debug` level message makes debugging impossible.

I’ve set up the auto-recording service for our owncast live stream service. Due to disconnections, it creates multiple files. Would increasing the duration help your case? I’ll leave it for now, as we may find a better approach later today.

**Comment by gaby** [comment]
@sobujbd In my case I had to bump the timeout to 30s. When streaming at home default is fine, while mobile 10s is too agressive and it kills the whole stream, and won't restart unless I close/open the client again.
