### ISSUE TITLE
Can't fix incorrectly entered fediverse account in Offline embed

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#4056]
Error is blocking the input field. 
![Image](https://github.com/user-attachments/assets/70df6b53-d9e1-4875-afe9-50e460eff14d)

Is it possible to do it like this?
![Image](https://github.com/user-attachments/assets/2f403394-dc54-48e0-90fd-71950ba54023)

**Comment by gabek** [comment]
We could make the errors more user friendly, but then they'd be less detailed, and it wouldn't be clear what the actual problem is. If we simply said "Server error" or something, it could mean anything. If we really wanted to spend a bunch of time on it we could _try_ and figure out every possible failure case, and try to make a user friendly version of each, but even then we'd absolutely miss a lot.

So while how it is isn't great, it at least tells you what is wrong. If there was a low lift improvement I'd be up for it, but it's not simple to add clear instructions unless we went really generic with something like "Cannot connect", and that may be less helpful because we don't tell them why. But if that's better we can do that. But I know personally I've found the detailed messages very helpful.

"Invalid input" also isn't going to necessarily be correct. They may have typed it in correctly, but the server isn't working, or it doesn't support the correct protocol, or any number of other things.

**Comment by germainelee** [comment]
I see. Idm the error message being lengthy as long as it provides clarity. 

I'm not sure how fediverse stuff works and the various failure cases, so do you think it is possible to display the error message in browser alert or this crude way (in image below)?
![Image](https://github.com/user-attachments/assets/9644e1f0-a317-4cdc-8aa7-8f689cd40541)

**Comment by mahmed2000** [comment]
There's a simple band-aid for now to make the Alert component closable. antd disables that by default. The callback for the button to submit also sets the `EmbedMode` enum to `CannotFollow`. That hides everything below the server info, so technically the error isn't hiding the input field, it doesn't exist at that point. Would need to set the Alert to be closable and add a `onClose` callback to reset the state to `CanFollow` again, since there's no other way to reset currently anyway other than reloading.

There might still be a problem with the close button being offscreen, but that's more general overflow problems. The case in the screenshot wouldn't be affected, for example.
