### ISSUE TITLE
Subscription Tier Support

### ISSUE THREAD

**Issue by maksrago** [owncast/owncast#456]
Would you consider integrating something that would allow for subscription options?

The most comprehensive project that I can think of that does something similar to Owncast is Destiny.gg, and on that site there are various subscription options, is this something that could be/is a focus of the development team? -> Example: https://www.destiny.gg/subscribe

(tl:dr -> can you add PayPal business subscription options, or some sort of more libre alternative to PayPal?)

**Comment by gabek** [comment]
Good question!

It's unlikely that we'll be addressing this in the near term.  And not because I don't care, or I don't want to, but there's a lot of things that have to be in place to make that happen.

First, we have no notion of accounts or users, and we don't have plans to change that.  So for a "user" to subscribe, a user needs to exist.

Secondly, I'd like to build any kind of payment integration in a flexible way where people can use different processors for payments.  I don't want to just build PayPal directly into Owncast and force everyone to use that.  But I also don't want to have a ton of different providers all in the code base.  I'd like to build this kind of integration as a plugin of some sort, and that's not something we have right now.

Hopefully the answers your question and clarifies some thoughts around it.  Sorry it's probably not the answer you want to hear :)

**Comment by gabek** [comment]
Closing as we won't be adding paid subscriptions to the core product.

**Comment by aaronpk** [comment]
See #667 for some ideas on how you could do this outside the project
