### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by Gargron** [owncast/owncast#464]
I've read in one of the issues that you [do not intend to have user account functionality](https://github.com/owncast/owncast/issues/456#issuecomment-745043909), but I want to present two arguments for why it is unavoidable:

- First, as the streamer, you want to participate in chat (and viewers need indication that you are indeed the real streamer, since people can choose their own nickname it could be easily impersonated!), you want to have access to (future) mod tools like timeouts and kicks using chat commands. HTTP auth using the stream key is not sufficient for this, you'd want a login session
- Second, any large streamer needs multiple mods to help moderate chat, since the streamer is busy performing the actual stream. You could maybe mod anonymous users every time you start a stream, but it would be really bothersome to repeat every time and you'd never know the anonymous person is who you think they are, mods could be easily impersonated

I understand the desire to not have a whole account management system. My personal wish would be a system where you can authenticate using your fediverse account, using OAuth or maybe OpenID (though OpenID would have to first be added to Mastodon). Like, I don't think it makes sense *federating* an ephermal chat, but it'd be cool if you could use your existing identity to use the chat on the site.

Otherwise I do agree that the UX flow where you pick your nickname and can start chatting immediately should be kept, as sign-up-before-chatting on every single owncast would be too disruptive; I just think this could essentially become a user account you then get a choice of setting a password for (or maybe e-mail and then use magic links to sign-in).

**Comment by SeaLife** [comment]
I would also like a implementation of OAuth2 or OpenID.
You could easily use Keycload if u want a custom user management but you could also just use Twitch or Steam as login providers and dont force user to register in every stream they wanna watch and participate in Chat.

But i also think, "secured" chatting is a must-have. Currently i cant block or mute spammers or smth like that.. :/ 

To your last point, i think the owncast owner should decider what should be allowed. I would love to see options like: "Allow all to view and to chat", "Allow all to view and chat with custom nicknames", "Allow all to watch but only signed in users can chat", "Allow all to watch but not to chat (disables chat)", "Require login for everthing", ...

Even a "VIP" Status for a user could be implemented by their OAuth2 identity and easily applied to their session i think.. 
This could allow for something like "VIP only chatting" and - if implemented later - "Sub only mode"...

Regards
SeaLife

**Comment by aaronpk** [comment]
Just to throw this out there, [IndieAuth](https://indieauth.net) is a very small addition to OAuth 2.0 which adds identity into the system in a much lighter weight way than OpenID Connect. Mastodon could easily add this extension to return the user ID of the user who just authenticated. The login form on OwnCast would ask the user to enter their server name, and do discovery on the server to send the user there to log in.

I did a talk about how Mastodon/ActivityPub apps can use IndieAuth to accomplish this kind of thing. The video is available -- of course -- on my website: https://aaronparecki.com/2020/09/22/25/activitypub-oauth-2-1

**Comment by aaronpk** [comment]
Just to throw this out there, IndieAuth is a very small addition to OAuth 2.0 which adds identity into the system in a much lighter weight way than OpenID Connect. Mastodon could easily add this extension to return the user ID of the user who just authenticated. The login form on OwnCast would ask the user to enter their server name, and do discovery on the server to send the user there to log in.

I did a talk about how Mastodon/ActivityPub apps can use IndieAuth to accomplish this kind of thing. The video is available -- of course -- on my website: https://aaronparecki.com/2020/09/22/25/activitypub-oauth-2-1

**Comment by gabek** [comment]
Do we know how far along any providers are with oauth 2.1 + IndieAuth integration?   When I tried it with my personal web site the only provider that supported it was Github and I couldn't find a list of other mainstream providers that support it.

**Comment by gabek** [comment]
Oh found a list!  Looks like Twitter and Github.  https://indielogin.com/setup

**Comment by aaronpk** [comment]
> Do we know how far along any providers are with oauth 2.1 + IndieAuth integration? When I tried it with my personal web site the only provider that supported it was Github and I couldn't find a list of other mainstream providers that support it.

If you have a WordPress website, you can install the IndieAuth plugin and then your website becomes its own provider. That's the real goal here rather than relying on Github/Twitter or "mainstream" providers. The idea is to let everyone bring their own OAuth provider to the table. Micro.blog is another service that supports IndieAuth natively.

**Comment by gabek** [comment]
Got it, thanks for the clarification!

**Comment by geekgonecrazy** [comment]
What does the ui usually look like to allow indie auth?  Is there a set of buttons that are recognizable?  Cause I can see on my instance where I’d gladly offer indieauth plus maybe Google/Twitter auth.  Just for options

**Comment by aaronpk** [comment]
> What does the ui usually look like to allow indie auth? Is there a set of buttons that are recognizable?

The prompt needs to ask the user to enter their server name. There can't be a button for it because there isn't a fixed list of providers. The client does discovery on the domain to find the server to redirect the user to.

**Comment by geekgonecrazy** [comment]
Hm.. so I guess people normally create their own button to sit beside other auth and then show a pop up to gather server address.  

I was hoping maybe there was a button style with logo that users would recognize that we could incorporate.    Even the pop up if it was familiar or we could show logo and provide useful info around it about indie auth.

**Comment by aaronpk** [comment]
ahh I like that idea. Usually we call it "web sign-in" in the UI for it, and in most of the places it's used it's the only option given. (The other main use of IndieAuth is for people to be able to use apps to post stuff to their websites, so those apps don't really have any other option.) 

Right now the only logo we have for this is:

<img src="https://indieauth.com/img/indieauth-logo-color.png" width="40">

I'm not a designer, it was my best attempt :wink: I'd really welcome some help from someone with better design skills to figure out how to make this look good on a button!

**Comment by geekgonecrazy** [comment]
I'm studying up on how indie auth works now.  I enjoy working with OAuth so might try and tackle this.  

I'm definitely no designer.  But I really like the idea of letting people add this as an option.

I'm envisioning a login button that pops up with the login options.  When the others start it kicks off to authorize page.  When indie auth button pressed takes to page with logo at top and description of indie auth + input for server.  Then kicks off into authorize.

@gingervitis @gabek i think both of you are more UI/UX Savy.  What do you think?  🤔

**Comment by gabek** [comment]
My concern is surfacing a login method that most people will be unable to use.  While it would be optional, just adding a "login" button implies that if you don't login you're somehow getting a worse experience.  So if we're going to add auth it better really be valuable to most people, not just people who support IndieAuth.  Sadly the number of people who would be able to login with IndieAuth would be in the vast minority.

I think IndieAuth is cool, and I support all of it, but I fear the value most users (or us) would get out of it wouldn't offset the confusion it could create when they see "Web sign-in" that doesn't do anything for them.

If I'm interpreting IndieAuth incorrectly please let me know.  I'd love to see it as a solution, but it kind of feels like a niche thing.

**Comment by aaronpk** [comment]
@gabek that's totally fair, and I agree I wouldn't want to make people feel like not logging in is somehow worse. But at the point that you're offering any sort of login that opens up the whole world of possible login options, at which point you're always going to be excluding some people. e.g. offering only Twitter login or only Facebook login is just as bad as offering only IndieAuth login. 

The original points brought up at the beginning of this issue won't go away, so at this point the question is more how should user accounts be handled at all rather than which particular method should be used to authenticate users.

**Comment by geekgonecrazy** [comment]
I think it's worth trying to fit along our other authentication methods.  Make it something very explicit to enable.  From what I can tell it's really not much different from regular oauth.

If we support using oauth with pkce then with 1 or 2 tiny things additionally and we support indieauth.

But I guess this is off-topic.  If we implement accounts we can see what demand and contributions bring

**Comment by Amolith** [comment]
If there's going to be user functionality at all, I would argue that local accounts are far more important than IndieAuth or OAuth or anything else that offloads the feature to some other service. Owncast is already a niche tool and adding niche authentication methods that most people don't understand (or even care to understand) would likely turn them away. Everyone knows how a register dialogue with username and password fields works but I think far fewer would "Login with Pleroma" or "Login with Mastodon" or "Login with `<insert fediverse platform here>`". Sure, using Google or Facebook or Twitch or GitHub or Twitter or Steam or `<insert commercial service that collects user data here>` would "solve" the issue but, from a privacy standpoint, I wouldn't even consider enabling those. When you go down the route of requiring users to log in with third parties, you have to decide which third parties to support and there are a million* of those, but fewer than 20* of them are privacy-respecting and none of those would be understood by regular people.

*Completely arbitrary numbers to demonstrate my point

This leaves "normal" viewers with 1) something niche they don't understand or 2) … ?

Adding account functionality locally avoids the whole problem in the first place. I'm not saying this should come *first*, rather that, if there are going to be accounts, users need to be *able* to register directly with the instance. From there, maybe they can log into another Owncast server with credentials from the first through some sort of embedded OpenID or OAuth implementation in Owncast, I don't know. Local just needs to be *an option* imo.

**Comment by aaronpk** [comment]
@Amolith check out the discussion in https://github.com/owncast/owncast/discussions/440

There's a big difference between the admin logging in to their own site and letting viewers log in for chat and other purposes.

For example, personally I'd absolutely not want viewers to have a password login to my instance at all, I would want to require viewers log in with third party providers.

**Comment by Amolith** [comment]
> There's a big difference between the admin logging in to their own site and letting viewers log in for chat and other purposes.

Sure, but I'm talking about viewers for all of this. The admin logging into `/admin` should be enough to verify their session without requiring any third parties or even built-in user management. They could also reserve usernames from there so no one in chat can ever claim it.

> For example, personally I'd absolutely not want viewers to have a password login to my instance at all, I would want to require viewers log in with third party providers.

In my opinion, users should absolutely be able to log into Owncast without requiring any third parties whatsoever. I would rather have no moderation and no user management at all than require my viewers to log in with Google or GitHub. Why wouldn't you want them logging into Owncast from Owncast?

**Comment by aaronpk** [comment]
If we're talking only about viewers here then I have a few strong opinions:

I actually would specifically want a viewer to log in to _my_ Owncast instance by using their _own_ Owncast instance. That's one of the things being discussed in the main thread in #440.

I absolutely do not want to manage user accounts for viewers, for many reasons including:

* I don't want to have users create a password on a site I manage for all the normal risk management issues around storing passwords
* I don't want anything to do with GDPR, which as soon as someone can "make an account" it starts getting messy there
* I don't want to have to deal with users' requests for "forgot password" flows or if they lose access to their email and want to reset it
* A signup flow will almost certainly require that an activation email is sent to the user. Now you would have to go set up an email provider in order to set up Owncast
* Signup flows that send activation emails often end up getting abused by spammers, since they can enter whatever email they want and attempt to get a message delivered. Depending on how the signup flow works, this is sometimes used to test the validity of emails, or is used to send spam messages if there is any way to customize the text sent in the activation email (e.g. `To: "donkey butts" <you@example.com>`)

If Owncast does ever build in a full on account system for viewers, I would want the option to disable it completely.

**Comment by Amolith** [comment]
> If Owncast does ever build in a full on account system for viewers, I would want the option to disable it completely.

I agree that having the ability to disable the functionality would be good.

> I actually would specifically want a viewer to log in to my Owncast instance by using their own Owncast instance.

That would be cool but we can't expect people to set Owncast up just to log in and reserve their username on another instance.

> I don't want to have users create a password on a site I manage for all the normal risk management issues around storing passwords

It's one Owncast instance. Should you accidentally drop the database, the only data that would be lost is their username, their email, and a hash of their password. It's not like this is a big service users would rely on to store important data.

> I don't want anything to do with GDPR, which as soon as someone can "make an account" it starts getting messy there

It really wouldn't get messy because the only user data being stored is username, email, and a hash of the user's password. From my understanding, the only way it *could* get messy is if Owncast were to store more user data than is strictly necessary to provide the service (username, email, hash of password).

> I don't want to have to deal with users' requests for "forgot password" flows or if they lose access to their email and want to reset it

Should Owncast have account support, that should be built in. If it's not, it should have a warning above the registration dialogue saying `NO PASSWORD RESETS; STORE THIS IS YOUR PASSWORD MANAGER` or something along those lines.

> A signup flow will almost certainly require that an activation email is sent to the user. Now you would have to go set up an email provider in order to set up Owncast

Only if local registration is enabled and I've already said that I think the admin should have the option to disable it. If you enable it, it should go without saying that you need some way to send email. Anyone who does any self-hosting should expect that.

> Signup flows that send activation emails often end up getting abused by spammers

I see how this *could* be an issue but I've been running services with open registration for over three years and used my own mail server for validation, password resets, notifications, etc. for two of those and never had a single problem with this.

---

Again, I do agree that local account management should be optional. However, I *absolutely* think it's *essential* functionality any time a service has anything to do with users. I firmly believe that logging in with a third party should ***never*** be an absolute requirement.

**Comment by aaronpk** [comment]
> That would be cool but we can't expect people to set Owncast up just to log in and reserve their username on another instance.

That's a strawperson argument, that's not what I said at all. This would be for convenience, and would also happen to work in such a way that other software could be used to log in the same way as well (micro.blog, wordpress, etc)

>> I don't want to have users create a password on a site I manage for all the normal risk management issues around storing passwords

> It's one Owncast instance. Should you accidentally drop the database, the only data that would be lost is their username, their email, and a hash of their password. It's not like this is a big service users would rely on to store important data.

I'm talking about the risk to the site owner if data is leaked/exposed. Not just if the data is lost. 

> It really wouldn't get messy because the only user data being stored is username, email, and a hash of the user's password.

We are both from the US, so I would prefer it someone more familiar with the GDPR would chime in on this matter.

> it should go without saying that you need some way to send email. Anyone who does any self-hosting should expect that.

I completely disagree, I think it's perfectly acceptable to not expect that self-hosted things are going to need to send email. Email opens up a huge can of worms and adds a significant barrier to configuring an application. 

> I see how this could be an issue but I've been running services with open registration for over three years and used my own mail server for validation, password resets, notifications, etc. for two of those and never had a single problem with this.

Your experiences are not necessarily reflective of everyone who is going to be using this software.

> However, I absolutely think it's essential functionality any time a service has anything to do with users. I firmly believe that logging in with a third party should never be an absolute requirement.

This is why the current functionality of avoiding all concepts of user accounts is great!

The other part of the discussion here is enabling offloading user management to an external service for example with an nginx auth proxy, which means you'd be able to set it up however you want! I'm a big fan of keeping things simple within OwnCast itself, and user account management is far from simple.

**Comment by Gargron** [comment]
I'll be real with you I am not going to sign up and manage an account on some random streamer's site. If it lets me authenticate with my Mastodon account to chat, cool, otherwise I will not bother. @aaronpk laid out very good reasons why you would want to avoid e-mail/password accounts in Owncast.

**Comment by Amolith** [comment]
> This is why the current functionality of avoiding all concepts of user accounts is great!

I would be perfectly fine keeping the current functionality. My *only* concern is ensuring that, should some form of accounts be implemented, viewers don't have to log in with third parties if they would rather not.

**Comment by gabek** [comment]
[First step](https://github.com/owncast/owncast/pull/1163) of having backing users will be available in 0.0.8.  There will be no way to login or identify yourself.  Future work to continue adding functionality will continue in 0.0.9.

**Comment by bugz8unny69** [comment]
Here just to provide my input, I'm the complete opposite, I'd like the whole shebang. I manage my own openid connect provider via UCS.  Being able to moderate, while not a requirement, is still essential when I come around and explore this project.

**Comment by gabek** [comment]
Moderation is currently available.

**Comment by hollunder** [comment]
Just one moderation idea we have had in case user accounts are available in some fashion:
Temporarily disable chat for users without account.
Assuming a spammer does not have an account he would be stopped there while at least a part of the regular audience could still chat. Most likely some non-spammers would be caught in that, but that's why I think it should just be a temporary measure, for example for some minutes, until the spammer has lost interest.

In addition there should be the possibility to ban accounts, but that's a rather obvious one.

**Comment by tacerus** [comment]
OpenID or SAML integration would be fantastic for people using OwnCast in an environment with other self-hosted services, and possibly an existing identity management solution in place. It does not need to be made prominent turning people away who do not know how to use it, and it does not need to ship with default support for identification with X commercial service. It would rather be an optional option, without which the system works just as it did before.

**Comment by pengu-fr** [comment]
Owncast could use the X-Forwarded-User header (if defined) to set the username.

In my configuration : I have a keycloak server, traefik reverse proxy with forward-auth OIDC middleware. Only authenticated user can acces to Owncast. And after user authenthication, the reverse proxy sends X-Forwarded-User header, which would be easy to read from Owncast to define the username.

It would also be nice to configure Owncast to use that header and forbid username change.

**Comment by jeyemwey** [comment]
> Owncast could use the X-Forwarded-User header (if defined) to set the username.

This has been implemented recently (https://github.com/owncast/owncast/pull/1633) and should be published with the next release of Owncast. You can try running a nightly build from the develop branch for the time being.

> It would also be nice to configure Owncast to use that header and forbid username change.

Would you mind creating a new issue for this feature? I can imagine that this is useful for your use case, however we had previously not implemented it.

**Comment by pengu-fr** [comment]
Nightly build works as expected ! Thank you very much.

I created an issue for the feature request #1723 to add a parameter to disable username change.

**Comment by jprjr** [comment]
Hi there, just thought I'd chime in with a use case for accounts/authentication.

I have an interactive livestream where chatters can play a music guessing game, similar to Name That Tune. When a user guesses the song, a chatbot will award them points. Then they can use those points for other interactive features (make a gif appear on screen).

I track everything on the user id field, but it seems like this is based to the device the user is on - they can log in from their phone and set their username, but now their points are tracked separately.

So, having some way to tie these multiple sessions to a common user, such that message events use the same user id despite being on multiple devices - would be a great feature.

**Comment by gabek** [comment]
Since I've heard a lot of confusion lately coming my way and I'm constantly getting the "I'm not going to use Owncast because you don't have accounts" I guess I should reiterate some things.

Owncast already has user accounts.  Every user taking part in chat has an account that is persistent. It has user metadata and is representative of a single person. You can ban them, you can make them moderators, you can see details about their account. They are real users. They are saved in a database. They are not just display names, and they are not just local data saved in a client's browser. Real real real real real user accounts saved on the server.

Yes, it doesn't work like Twitch or YouTube does. I know it may be weird because you don't have to "log in" and that might confuse people. But users and accounts exist. 100%. 

With that clarification out of the way.

What _doesn't_ exist is a way to restore users.  There's a million ways to go about this. But the one way I still have no interest in  is creating a local email/password system for Owncast. I don't want to manage email password resets, I don't want Owncast to be storing your email address or phone number or anything like that so we can identify you at all. That's just not going to happen.

What is being added, however, is ways to authenticate yourself so you can restore your already existing account. You can see multiple items related to this in the 0.0.12 milestone because it's being worked on for 0.0.12.

**Comment by gabek** [comment]
If anybody wants to follow along at home: https://github.com/owncast/owncast/issues/1273#issuecomment-1085069984
