### ISSUE TITLE
Support text input of :emoji:, and show the title of emoji in title attribute

### ISSUE THREAD

**Issue by mattwilson888** [owncast/owncast#480]

**Comment by gabek** [comment]
Hey there!  Could you add some additional detail around this request?  I don't exactly follow it.  Could you provide an example?

**Comment by graywolf336** [comment]
If I understand it correctly, I think the request is to add a title attribute to the emojis that show how to reproduce and use it. Like hover of it and it’ll display something like: `:smile:`

**Comment by gabek** [comment]
Ah!  We don't currently have a way to input an emoji outside the emoji picker.  But that's a valid thing to have going forward.

**Comment by mattwilson888** [comment]
@graywolf336 Ahh yes that was what I intended to explain.

**Comment by gabek** [comment]
If anybody wanted to work on this, this could probably be accomplished in a simple way with the following:

- Add the `title` attribute to emoji img tags with the name of the emoji.
- Do a simple substring replacement of `:emojiname:` strings with the full emoji img tag when composing a message.  For bonus points do a validation of the the name of the emoji to make sure it's valid.

**Comment by gingervitis** [comment]
Extra bonus points for being able to copy/paste a rendered emoji into a message!

**Comment by MFTabriz** [comment]
@gabek For implementing this feature, I was thinking about simply adding a function call inside the [RenderAndSanitize()](https://github.com/owncast/owncast/blob/0c6378976cb3efd2eed1b5e12bfd99b507434cde/models/chatMessage.go#L66) [in models package] to replace `:emoji:` with the corresponding HTML img tags. Ideally, this function would call the [getCustomEmojiList()](https://github.com/owncast/owncast/blob/0c6378976cb3efd2eed1b5e12bfd99b507434cde/controllers/emoji.go#L26) [in controllers package] and receive a list of custom emojis. But doing so creates a cyclic dependency as the controllers package already depends on the models. Can you guide me how to get around this?

**Comment by gabek** [comment]
Sounds like a good approach!  The only note is doing it server-side makes it so when composing the message we can't replace the :emoji: with the image while you're typing, so you won't know if you typed the emoji name correctly until you hit enter.  Probably not a big deal for right now.

There's a **lot** of chat work going on, so I'm not sure if you want to start making changes involving chat from the develop branch due to conflicts.  For example, `RenderAndSanitize()` has been moved to the `chat/events` package.  So if you want to actively work on this now you might just want to branch off of `gek/chat-rebuild-with-access-tokens`, though it's still being actively updated, but likely won't impact emoji.

As for `getCustomEmojiList()` the controller probably shouldn't be directly reading the filesystem anyway.  So maybe move that logic to the `data` package since it probably fits better there. Then the controller, and `RenderAndSanitize()` can fire `data.GetCustomEmojiList()` without any cyclic references.

**Comment by MFTabriz** [comment]
Thanks for your helps. Let me see what can I do client-side in the `gek/chat-rebuild-with-access-tokens` branch. This will take longer than my usual turn-around as I try to find my way around the js. But I’m on it!

**Comment by MFTabriz** [comment]
@gabek I think this issue should be closed now.
