### ISSUE TITLE
Check validity of specified ffmpeg in config at launch.

### ISSUE THREAD

**Issue by cirrusflyer** [owncast/owncast#490]
I've setup Owncast on two different Synology NAS under Docker.  Using the custom YAML file.  WebUI load fine.  But when I try to stream with OBS or Zoom, I get constant drop and reconnect.  I can see the Owncast logs showing the connection and then drop immediately.  I've tried OBS in Ubuntu and Windows 10.  Same behavior.  I'm wondering if it's related to running in Docker or Docker on Synology.  Anyone else configured like this?

**Comment by graywolf336** [comment]
Can you grab the `transcoder.log` file? Should give us some more insight into what is happening.

**Comment by ztgasdf** [comment]
If your transcoder.log has anything like `Unrecognized option 'var_stream_map'.` then that means you have an outdated version of ffmpeg.

**Comment by gabek** [comment]
Are you using the image already up on Dockerhub, or are you creating your own Docker image?  If you're creating your own, are you just using the provided `Dockerfile`?

I would guess all the Docker installations should end up with the same version of `ffmpeg` since we provide it in the image, and it's installed in the `Dockerfile`.  But maybe there's other wildcards somewhere in there.

**Comment by cirrusflyer** [comment]
I'm using the Dockerhub version, and wondering if the Synology has issues with using ffmpeg in that way.  I did test the non-docker version and it works great.

**Comment by YarmoM** [comment]
I have just solved the same issue on my instance. Here's what solved it for me, hoping it's the exact same problem as OP.

I also use the docker variant (though not on synology), and OBS kept disconnecting and reconnecting. `transcoder.log` simply stated:

```
sh: /usr/local/bin/ffmpeg: not found
```

So I changed `ffmpegPath: /usr/local/bin/ffmpeg` (which is the example on the website) to `ffmpegPath: /usr/bin/ffmpeg` in the `config.yaml` and voila, now it works. Hope this works.

**Comment by gabek** [comment]
Nice catch!  In 0.0.3 and forward you actually shouldn't have to specify it at all (as long as it lives in your path), so you might even want to try removing that line all together.

**Comment by JMTK** [comment]
Yep that fixed same issue here. The only logs I was getting from the Docker container was 
I am running the server via Docker For Windows on WSL. 

I get Incoming RTMP connected. followed immediately by RTMP disconnected. 
I have OBS set to look at localhost:1935 but the OBS logs show a successful connection but immediately get a socket thread windows abort `Aborting due to FD_CLOSE, error 0`

OBS Logs:
```
C:\WINDOWS\system32>docker run -v (redacted)/config.yaml:/app/config.yaml -p 8080:8080 -p 1935:1935 -it gabekangas/owncast:latest
INFO[2020-12-21T20:34:37Z] Owncast v0.0.3-docker (97a86ec388725f5c867cf88e172a59a71d0baf5a)
INFO[2020-12-21T20:34:37Z] Web server is listening on port 8080, RTMP is accepting inbound streams on port 1935.
INFO[2020-12-21T20:34:37Z] The web admin interface is available at /admin.
INFO[2020-12-21T20:34:41Z] Incoming RTMP connected.
INFO[2020-12-21T20:34:41Z] RTMP disconnected.
INFO[2020-12-21T20:34:45Z] Incoming RTMP connected.
INFO[2020-12-21T20:34:45Z] RTMP disconnected.
```

Would be helpful to get error logs here I think

**Comment by gabek** [comment]
Absolutely.  We currently throw an error if `ffmpeg` can't be found, but not in the case where it's explicitly set, but the path isn't valid.  We need to check validity of it in both cases.  Thank you for all the troubleshooting and feedback!
