### ISSUE TITLE
Support s3 virtual hosted-style host

### ISSUE THREAD

**Issue by deluxghost** [owncast/owncast#497]
Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

The s3-compatible provider I'm using doesn't support path-style

It's easy to make this line configurable:

https://github.com/owncast/owncast/blob/959482e41a306f54ad2a829433613504a8fb4e12/core/storageproviders/s3Storage.go#L179

**Comment by gabek** [comment]
Nice!  Are there any down sides to enabling this that we should be aware of in testing?

**Comment by deluxghost** [comment]
> Nice!  Are there any down sides to enabling this that we should be aware of in testing?

I was using a local build, with that value set to false (hardcoded). I don't see anything wrong yet, at lease the streaming and the log is ok. I'm not sure aws or other providers tho.

**Comment by gabek** [comment]
Oh also, what provider do you use?  Just curious.

**Comment by pierreozoux** [comment]
@gabek ok, I understand now :)

Actually the initial bug/feature request report is about having this param configurable.
In ObjectStore implementations like ceph, you have to have path_style to true (or it is more complicated to configure it in the first place).

I switch to use minio instead of ceph, and in the future as well, so on my side I'm fine, but I understand that some implementations of objectstore will require to be able to configure that.
