### ISSUE TITLE
Promote chat participants to moderators

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#499]
Once the ability to delete chat messages exists, it'd be great to be able to promote other chat participants to moderators so that they can also help delete messages.

This doesn't need to rely on any sort of authentication system, and doesn't need to persist between streams. The minimum viable feature for this would be to give the site admin the ability to give individual chat participants the ability to delete messages.

**Comment by gabek** [comment]
Slimming down the 0.0.8 milestone by limiting just to core functionality that can continue to be built upon.  Moderation is its own thing and can't just get thrown in.

**Comment by gabek** [comment]
- Expand the user object to support the existing `scopes` database field.
- Add an API that adds a `MODERATOR` scope to the user.
- Add new button to User Info modal in the admin to fire this new API and add/remove the access scope to this user.
- Append the `ConnectedUserInfo` event to send along the current user's scope on connect and scope change much like happens when a user's display name changes.
- Add a version of the hide message API and ban user API that supports user access tokens just like it accepts 3rd party api access tokens.

[+ frontend work](https://github.com/owncast/owncast/issues/1291)
