### ISSUE TITLE
Add help section to admin with links to documentation and troubleshooting docs

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#541]
We can make some high level links to common things people might want to read up on, as well as some general links to documentation that might be helpful.

**Comment by thilobillerbeck** [comment]
I just started working on this as part of getting into the codebase. Awesome project btw.

**Comment by gabek** [comment]
cc'ing @gingervitis since she might have some layout ideas of what this should consist of.

**Comment by thilobillerbeck** [comment]
Thx. 👍 This is how my current progress looks like. _(Please keep in mind, that this is just a prototype and not finished by any design means)_

![image](https://user-images.githubusercontent.com/7442383/103298755-49e07d80-49fb-11eb-80e3-344e2428f025.png)

**Comment by gabek** [comment]
That's awesome, thanks for sharing!

**Comment by gingervitis** [comment]
Hey @thilobillerbeck thanks for getting this started! I honestly hadn't started thinking about it yet, but what you have is looking like a great start!

Playing off of what you have so far, I could see the "Common tasks" being a part of Documentation.  Or maybe we could call it "Using Owncast".

We could also have a similar sort of "Common issues/questions" section under Troubleshooting.

Random, since we're already using Ant Design components in this project, if you want to get more designy and spice up the page, maybe we can throw in their help-looking graphic somewhere! But that's totally up to you.
https://ant.design/components/result/#components-result-demo-404
<img width="368" alt="image" src="https://user-images.githubusercontent.com/9563255/103311235-a4afb000-49ce-11eb-8814-7373439aba3a.png">

**Comment by thilobillerbeck** [comment]
![image](https://user-images.githubusercontent.com/7442383/103312425-478f1b00-4a1d-11eb-9a49-67b37cd04145.png)
Including the Result graphics into the page looks like this.

Including a section similar to this in the documentation seems like a good idea. 👍
