### ISSUE TITLE
Support streaming privately

### ISSUE THREAD

**Issue by rdtq** [owncast/owncast#630]
Currently, ff a user wishes to stream privately, he could put reverse proxy server such as Nginx or Caddy in front of owncast instance and either enable Basic authorization, or do url rewrites:

1. Putting Basic authorization in front of Owncast instance works in Firefox and Chrome, but not Safari. Safari won't send authorization headers to websocket requests, and there's nothing we can do about it.
2. Doing url rewrites. Consider the following Caddy (or similar Nginx) config:
```
my-owncast-domain.xyz


handle_path /secret_path/* {
        uri strip_prefix /secret_path/
        reverse_proxy 127.0.0.1:8080
}
```
Now, only those with a secret link http://my-owncast-domain.xyz/secret_path/ can view the stream. 

The problem is most paths in Owncast frontend use hard-coded absolute paths, e.g. `/js/modules/app.js` instead of `./js/modules/app.js`, so the application breaks.

I have changed  paths to use relative values, so the application supports this use case (without breaking default configuration on `/` of course) and gonna submit pull request for consideration some time later.

**Comment by gabek** [comment]
Allowing running from an arbitrary path was requested in #505, but it's not something we've had a chance to look at since it's not something we've heard much need for.  The admin also assumes it's living in `/admin` so I'm not sure how easy it would be to change that, but thank you for being willing to take a look!

One other person seems to have found a workaround for their password-protected stream in #489.  I'm not sure of the details.

I'm going to close this issue in favor of the two existing issues, since they're two separate things to track.  Feel free to jump in on the above issues.
