### ISSUE TITLE
Add option to replace chat with embed code

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#636]
I'm a heavy user of [Slido](https://slido.com) for certain kinds of events, and I'd love to be able to embed the Slido page into the owncast page, it would fit perfectly in place of the sidebar chat. I'm imagining a new config option that would turn off the chat feature and stick an iframe in its place. That would open up the possibility of using other kinds of chat platforms as well without any additional work in owncast.

**Comment by gabek** [comment]
Instead of removing chat from the full layout it sounds more like you'd be better off creating your own layout and throwing the embedable  player in there, using whatever chat you'd like.  As an example of somebody doing this successfully is https://jnktn.tv/.  In general I don't think building a completely replaceable chat would be something most people would use, so I don't think it's something that should be built into the software when there's other routes to go.  Sorry about that!

**Comment by aaronpk** [comment]
ah that works too, thanks! I guess that gives me even more flexibility with it

**Comment by aaronpk** [comment]
@gabek before I open a new issue, is there a way to disable the little footer at the bottom of the standalone embed that shows the number of viewers? I suppose I can edit the CSS to hide that element.

**Comment by gabek** [comment]
Unfortunately there isn't, so yeah, css would be your best bet.  We've talked about changing the UI of that so it's not so in the way for the embed player, but haven't made any changes yet.

**Comment by jeyemwey** [comment]
Hiding the viewers count with CSS will not remove this information effectively from your site. The information will still be publicly available with the `/api/status` endpoint [1]!

You can try modifying the backend code to always return `1` or `0` or something.

[1]: https://owncast.online/api/latest/#tag/Server/paths/~1api~1config/get

**Comment by aaronpk** [comment]
Oh I don't care about that, I just don't want it cluttering the UI for this use case
