### ISSUE TITLE
Support audio only stream

### ISSUE THREAD

**Issue by pierreozoux** [owncast/owncast#654]
For ecological reason, and sometimes, related to content, would it be possible to have audio only?

For the time being, I'll put a really low resolution :)

**Comment by aaronpk** [comment]
Interesting idea, but it’s a completely different protocol and also a completely different UI you’d expect for an audio stream. A low res non-moving picture will take almost no bandwidth so that’s a good solution in the mean time.

**Comment by gabek** [comment]
Right now our pipeline expects both audio and video and audio-only is probably not in the cards right now.  Like Aaron said, just throwing in a static image is probably the best solution.  If other people had this requirement maybe we can look into it down the road.

**Comment by pierreozoux** [comment]
The workaround is indeed fine for me.

Maybe I could rephrase the feature to have a static low res image possibility?

I'm wondering if it is actually efficient in bandwidth saving.

I'll try with a 2px video stream also :)

**Comment by gabek** [comment]
Going to close this since it sounds like you have a workaround.  Hope that's working out for you!

**Comment by MFTabriz** [comment]
@gabek What needs to be done for implementing this feature? This really valuable for the users who are using a cellular network and to limit their data usage, only want to listen to the stream.

**Comment by gabek** [comment]
In the above use case I believe it was somebody wanting to broadcast audio-only, but it sounds like you're talking about wanting to offer an audio-only output variant to viewers who only want to listen to it.

While I totally understand why you'd want this, for the amount of things we'd have to address to make it work, it's a pretty niche use case.  And if you're specifically talking about a mobile use case with cellular, iOS doesn't allow you to play a video stream in the background anyway.  I'm not sure about android. So it's likely we'd have to have a completely different player that is an actual audio player, not a video player (I'm not sure what videojs would do with a stream without a video track anyway).  And in this case it mostly just sounds like icecast.

So I get it, but at this particular time I'm not wanting to go down that road to make this work due to the vast amount of added complexity when it would benefit few people.  You can add an output variant right now with a very low frame rate and bitrate and save bandwidth that way.

**Comment by MFTabriz** [comment]
You are right. My query was about having an audio-only output variant. Thanks for your through explanation. Just for the future reference: the android does support playing the media inside the browsers in the background. And there are browsers which can play the owncast’s HLS links out of the box (for example brave).
