### ISSUE TITLE
Useful error messages for file descriptor limits

### ISSUE THREAD

**Issue by jeyemwey** [owncast/owncast#775]
When Owncast has too many open connections (http/ws/file handles), the OS won't allow any more connections. Currently, Owncast writes this to its logs (stolen from Rocket.Chat):

![Log output describing too many open files](https://user-images.githubusercontent.com/2796271/109427015-b3c3d600-79f0-11eb-8b8f-7b56957aabab.png)

It would be great to have a more useful error message and maybe a link to the documentation where we describe how to modify the limit.

The original reporter said that they had around 200 concurrent viewers when this bug appeared.

**Comment by gabek** [comment]
This is a rough one because it's an operating system thing, and there's no single point in Owncast where we'd be able to intercept this specific error.  Realistically if this state is happening it's happening across the board on their machine and not just in owncast, so I don't think treating it as an owncast issue makes sense, it's certainly not an owncast bug, it's just a way of life on any machine when you max it out.  I think the best we can do is make sure it's documented.
