### ISSUE TITLE
Owncast fails on multiple video configurations while streaming

### ISSUE THREAD

**Issue by Jerlag01** [owncast/owncast#795]
When I created a second video configuration I got the following error multiple times within 15 seconds (10 times). error goes as follows: 

Unable to generate thumbnail: open webroot/hls/1: no such file or directory

**Comment by gabek** [comment]
Is it any second video configuration, or just a specific configuration?  Is it with any broadcasting client?  If you only have a single output configuration are there any issues?  Is playback with working?  Does the error ever stop showing?  Could you share your configuration?

**Comment by gabek** [comment]
If you're still experiencing this, is there anything else you can share that would be helpful?  If you could, it might be useful for you to join our Rocket.Chat so we can troubleshoot with you in real-time using your actual stream.  https://owncast.rocket.chat.  

This isn't something we've seen with anybody else, so that's why it's a bit puzzling.

**Comment by gabek** [comment]
Closing since there doesn't seem to be any actionable details.  Please re-open if you can help troubleshoot with us.
