### ISSUE TITLE
Being able to have custom Offline image

### ISSUE THREAD

**Issue by Daxcor69** [owncast/owncast#840]
It would be nice to be able to have a custom png/jpg for a offline image placeholder.  If it has to be svg, then allow that separate selection to be made.

Thank  you,
Awesome product!

**Comment by aaronpk** [comment]
I was just thinking this the other day!

**Comment by Daxcor69** [comment]
To add to this, it would be nice to be able to upload the svg via the admin webpage. Would make it so much easier for non tech people.

**Comment by gabek** [comment]
Logo uploads will be added in the next release: https://github.com/owncast/owncast/issues/716

**Comment by MFTabriz** [comment]
@gabek is this issue completely solved?

**Comment by gabek** [comment]
No, but it's been tabled.  Forest put in a PR but I had concerns about the admin UI becoming overly complex with the user having to understand the difference between the different images.  If we were to do this I think we'd have to re-interpret how the image uploads should work, where you select what type of image you want to upload and then you upload it instead of having two identical upload components next to each other that could very easily confuse somebody.

So not a priority and eventually we can work out something that makes sense.

**Comment by working-name** [comment]
Any updates on this?

**Comment by gabek** [comment]
This is no longer applicable with the new web interface in v0.1.0.
