### ISSUE TITLE
Provide RTMP URL in the admin page next to the stream key

### ISSUE THREAD

**Issue by aaronpk** [owncast/owncast#861]
Normally streaming services will have the RTMP URL available for quickly copypaste into streaming software. Right now I have to click through to the external owncast documentation page in order to find out the path to stream to (`/live`). Ideally this would be shown in the server settings page along with the stream key.

**Comment by thilobillerbeck** [comment]
Just started working on this

**Comment by thilobillerbeck** [comment]
This is what I came up with.

![image](https://user-images.githubusercontent.com/7442383/113328182-373c5400-931c-11eb-9d6d-1342fe7b55ae.png)

**Comment by gabek** [comment]
I'm not sure how other services do it, but I think this comes off a bit misleading because it looks like it can be edited like the rest of the fields on the page.  I would think I'm supposed to type something in there.

What do you think about something simpler, where just above "Save this key somewhere.." maybe it's there, just in plain text?  Maybe you click on it and it auto-copies?

**Comment by thilobillerbeck** [comment]
As far as I know, other services also use a read-only text field for that. But you're right, this can be misleading.

**Comment by aaronpk** [comment]
Here's what it looks like in YouTube:

![image](https://user-images.githubusercontent.com/113001/113330054-2ddac980-92d3-11eb-9854-e08997d115b1.png)

Restream:

![image](https://user-images.githubusercontent.com/113001/113330272-64b0df80-92d3-11eb-9073-ba00796b65a7.png)

Interestingly in both those cases the stream URL and key are not editable and also not mixed with other editable form fields.

**Comment by gingervitis** [comment]
Maybe you can render the text in one of these informational Ant "Alert" components instead?
https://ant.design/components/alert/

**Comment by thilobillerbeck** [comment]
@aaronpk but they all look like form fields, which is really weird. :/
@gingervitis good idea :+1:

**Comment by thilobillerbeck** [comment]
But I'm not really sure where to put it. Aligning it with the rest of the options would look good, but could possibly irritate the user. But putting it anywhere else would look a bit out of place... :thinking:

**Comment by aaronpk** [comment]
Personally I don't see anything wrong with read-only form fields. Especially if there's a "copy" button next to it where the editable ones don't have a copy button.

**Comment by gabek** [comment]
Another idea, since this isn't really a setting, maybe we could put it on the admin home page instead?  There's literally a block there that says "Use your broadcasting software. Learn how to point your existing software to your new server and start streaming your content."

Maybe we could prominently place it there since it's trying to help the user start streaming?

**Comment by aaronpk** [comment]
Good point! I really like that idea. It's likely going to be something people need to look up very often anyway, not to mention it's something they'll need to find before they can broadcast the first time too.

**Comment by thilobillerbeck** [comment]
I experimented a bit. What do you think about this? (Just a prototype)

![image](https://user-images.githubusercontent.com/7442383/113432564-e42ad580-93dd-11eb-8492-6780e2eaaa4b.png)

**Comment by gabek** [comment]
That area is actually about to be taken over by this "news" feature: https://github.com/owncast/owncast/issues/865.  Can we put it in that block where it says "Use your broadcasting software" and make it not so large?  That's a list of things the user can do next on the right column there, so having the RTMP URL makes sense to add it to that top block.

**Comment by thilobillerbeck** [comment]
So, something more like this?
![image](https://user-images.githubusercontent.com/7442383/113441234-3a077980-93ee-11eb-8293-34385e3f42c4.png)
or
![image](https://user-images.githubusercontent.com/7442383/113441329-5d322900-93ee-11eb-8113-acd437fa6719.png)

**Comment by gabek** [comment]
Those form fields still look like something that is intended to be editable to me, especially since it matches all of the other form fields in the admin where you are supposed to type in them.

Mocking up is not my strong suit, but this is kind of what I was thinking.   Click on the url to copy it, and then there's a way to copy the stream key.  Or we could have two buttons if the "click to copy" isn't clear.  Instead of an underline we could put a box around it or something to make it look different, or just buttons.  I think there's options where we don't use the form.  As a bonus it won't take up a third of the page.

![image](https://user-images.githubusercontent.com/414923/113447904-a2833600-93af-11eb-8402-17a0024bf645.png)

**Comment by aaronpk** [comment]
Personally I prefer the form field version. I think it's okay that they're not editable, read-only fields are a normal thing, but especially now that these aren't next to other _editable_ form fields. I think the confusing part on the first mockup was that the non-editable fields were mixed in with editable fields.

**Comment by gingervitis** [comment]
Looks like Ant might have the best of both worlds! Check out this copyable `Paragraph` component they have. Maybe that could work for this purpose?
https://ant.design/components/typography/

**Comment by thilobillerbeck** [comment]
This looks good. But I am still thinking about a way to direct the users view to it relatively quickly, when opening the admin panel for the first time, since this is something many users will look for, as mentioned above.

**Comment by thilobillerbeck** [comment]
Maybe I could put some borders around the paragraph to make it (stand out) from the rest of the text.

**Comment by thilobillerbeck** [comment]
This is a version with the Paragraph and some styling to make it more "visible".

![image](https://user-images.githubusercontent.com/7442383/113511386-cdac8780-955f-11eb-9fbf-7aaeebaf23ba.png)

**Comment by thilobillerbeck** [comment]
An alternative approach, which differs more from form elements:

![image](https://user-images.githubusercontent.com/7442383/113511456-23812f80-9560-11eb-9480-a5a5b321d9cf.png)

**Comment by thilobillerbeck** [comment]
So I'll stick with the last approach I presented. PR coming soon.

**Comment by aaronpk** [comment]
I like it!
