### ISSUE TITLE
hls.js and maybe ll-hls?

### ISSUE THREAD

**Issue by andreweff** [owncast/owncast#870]
You guys doing a really great Job with owncast!
There are so many big things and small details which are really great. I love the admin panel and things like stream detection in player and of course transcoder and the overall integration with chat!

However, I wish player could detect it's position in time and do a jump to more live when it detects a position to far in the past. hls.js is capable of doing this with [liveSyncDurationCount](https://github.com/video-dev/hls.js/blob/master/docs/API.md#livesyncdurationcount) in combination with [liveMaxLatencyDurationCount](https://github.com/video-dev/hls.js/blob/master/docs/API.md#livemaxlatencydurationcount)

I saw you already discussed the use of low latency HLS. Even if you don't need a latency around 2 seconds or so, due to it's utilisation of modern standards (http/2) it is maybe a good choice? I tested it with nimble streamer/wmspanel and hls.js and in this combination I was able to utilise [maxLiveSyncPlaybackRate](https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxlivesyncplaybackrate) which allowed player even to catch up slowly to live (N-3 chunks/parts). It's like a player synchronisation for viewers. I wasn't able to use maxLiveSyncPlaybackRate without ll-hls. But for standard hls the jump to live with liveMaxLatencyDurationCount was also a great feature.

In my opinion this would be great additions for this great project.

Greetings

**Comment by gabek** [comment]
Thank you, I'm glad you're enjoying it!

So I've thought a little bit about this and hope to find some time in the future to look at it.

While we're probably not going to change the entire player for this feature, there is some work filed to look at trying to do our own playback rate adjustment.  https://github.com/owncast/owncast/issues/837

As far as LL-HLS, it'll probably be some time until it's solidified enough for us to jump on it.  One big piece of the puzzle is using it with external storage providers.  If you store segments externally then we can't build the required things like the blocking playlist functionality, because we no longer own the web server serving it.

Closing this in favor of https://github.com/owncast/owncast/issues/837, but keep an eye on that issue in the future!
