### ISSUE TITLE
Keep persistent logs on disk

### ISSUE THREAD

**Issue by GTXCrusader** [owncast/owncast#908]
Simply put, it would be nice to be able to export the admin/logs from the Web interface directly without having to go in through the server directly.

The export could use a standard delimiter between columns (such as a comma or semi-colon) into a raw text document.

**Comment by gabek** [comment]
Just curious, but what is the use case that you'd want to save off old logs?  Just want to understand what you're going for so we can try to address it in a useful way.

**Comment by GTXCrusader** [comment]
Currently any time the Owncast service shuts down it does not appear to keep any old logs (at least within itself that I can tell). If there is a shutdown of any kind (even if the server itself shut off for whatever reason, due to a crash or user), any old logs would be nowhere to be found.

This could be useful to look back on if there are errors that cause the service to stop unexpectedly or for checking against multiple usage situations to look for patterns or odd behaviors.

**Comment by gabek** [comment]
Oh! So it sounds like you want a persistent logs, not just a way to download the logs from the current session?  As it stands if we were to add log downloading, if you restarted the server, it would still get cleared because we don't keep logs around.

While we could totally add persistent logs, if Owncast were to crash then the logs around the crash would probably never get successfully written to disk... because Owncast crashed.  But outside of that scenario, we could keep logs on disk.

So it sounds like the real problem here is Owncast is crashing for you!  So we need to fix that ASAP, so please let us know what's going on there.

**Comment by GTXCrusader** [comment]
Persistent logs could be quite useful, and not all logs would be used specifically for crashes either (as far as crashes go, I'm going to see if 0.0.7 resolves many of them and hit you up in the chat if not).

Sometimes if I'm "breaking things" on my own end it's nice to see logs after a manual restart as well. Logs could be appended to a file in real time as they're created which would preserve them in the result of a shutdown, and then either create a new file when the service is restarted or continue appending to the existing file.

Whilst this would require some kind of manual cleanup over time to prevent massive log files sizes, that would take an exceedingly long time on even a modest storage platform, or there could be options for the service to automatically create logs every user-defined time (eg: 7 days) and after a set period (eg: 30 days) it begins deleting the oldest log file.

**Comment by gabek** [comment]
Instead of persisting these logs in the admin it sounds like it would be more useful to save them as just a regular old log file on disk, so that's what I'll do.
