### ISSUE TITLE
Feature request Automatic systemd support

### ISSUE THREAD

**Issue by aral** [owncast/owncast#923]
It would make deployments entirely seamless if Owncast set up its own systemd configuration.

e.g., In [Site.js](https://sitejs.org), you have an `enable` command that does this.

So, if you have a server and you do:

```
site enable
```

That creates the task configuration and installs it and your server is up and running.

Combined with [automatic TLS support](https://github.com/owncast/owncast/issues/922) and [automatic updates](https://github.com/owncast/owncast/issues/924), this would mean that a single command is all you would need to have a production server that survives restarts, crashes, etc., and is always up-to-date.

The same could be implemented for Owncast.

**Comment by aral** [comment]
Note: this is now implemented for Owncast in Site.js. Please feel free to steal and implement natively in Owncast :)

https://github.com/owncast/owncast/discussions/935

**Comment by gabek** [comment]
Adding this to our installer might be a good middle ground. If the environment that it's being installed to has systemd, we could try to set that up. It would require asking for root privileges, and I don't really like that.  I'd rather users do that kind of things themselves, especially since it's an untrusted installer script.  It would be better if we had the bandwidth to package Owncast for distro-specific installs that would include being setup in systemd.

**Comment by gabek** [comment]
Closing because as it stands there's no way to accomplish this without requesting root, and that's not something I'm comfortable doing. Plus not all environments use systemd, so it would add a level of complexity. I could be convinced otherwise, but this doesn't seem to be a big enough deal to make that tradeoff currently.
