### ISSUE TITLE
Add more detailed documentation about client software setups

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#996]
Related to https://github.com/owncast/owncast/issues/955.

- Recommended bitrates for different resolutions
- iframe settings
- optimization tips

**Comment by GTXCrusader** [comment]
I tend to base a lot of my streaming standards off of YouTube's ingest recommendations (not for their uploads, but for their live-streaming).

Only downside is.... currently Owncast is limited to 6mbps.... and YouTube has that as a recommended for 720/60p. 2160/60p's recommended is as high as 51mbps.

Could be worth looking across different platforms and comparing standards to broadcasting too (eg: Twitch limits non-partnered streams to 6mbps but allows higher for partnered channels. Broadcast companies like Comcast send 1080/24p signals at roughly 8mbps. Picarto limits you to 2mbps no matter what.)

**Comment by gabek** [comment]
For reference this is what I've been using as a guide: https://stream.twitch.tv/encoding/

I very much look at things in the vein of the 80/20 rule.  Almost nobody who uses Owncast could ever support 51mbps and it would cause more problems than it would solve.  I've found bad things happen when you say "just let people set it to whatever!" and then _they do_.  We already see people crank up their CPU usage to as high as possible and their latency to as low as possible just because they can, and then they report issues simply saying "it doesn't work".  How many people can actually use that compared to the number people who would try to use it?  We can't stop people from making bad config choices, but we we can stop them from making config choices that would almost never make sense to almost anybody.

I understand it limits the target usage group of Owncast from "anybody" to "most", but it allows most people to have a better experience.


<blockquote><img src="https://s.jtvnw.net/jtv_user_pictures/hosted_images/GlitchIcon_purple.png" width="48" align="right"><div><strong><a href="https://stream.twitch.tv/encoding/">Twitch Streamers - Twitch Video Encoding/Bitrates/And Stuff</a></strong></div></blockquote>

**Comment by GTXCrusader** [comment]
Duly noted. That's why I mentioned the differences in how a variety of other platforms gauge performance and quality.

For what it's worth, I've been able to get Owncast to work with 50mbps ingest for 4k at 30fps. That's on an AMD Epyc 32-core rig though, so yeah...

IMO I think being able to get to at least 10-12mbps would cover all practical uses for 1080/60p. As 4K is still kind of pointless there's not much reason to go any higher at this time. We also do not see much use for anything above 60fps as well. My only curiosity would be how much more CPU load would be on a machine if it was encoding out at 12mbps, but I would imagine it's likely not too much more than 6mbps.
